### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by iw1gfv** [Maproom/qmapshack#102]
Support <trkseg> tag

**Is your feature request related to a problem? Please describe.**
Many gpx files contains the trkseg tag, this is very useful to split a  track in many parts.
If a track <trk> contains many not contiguous <trkseg> , qmapshack joins these segments with a straight line.
This behavior make the map cluttered with non useful straight lines.
![Schermata da 2020-02-03 00-20-08](https://user-images.githubusercontent.com/16556552/73617065-2d856680-461b-11ea-8b3e-4d658ba3406b.png)

**Describe the solution you'd like**
Different <trkseg>  should not be joined with a line

Many thanks

**Comment by kiozen** [comment]
You are aware of the split rack filter?
https://github.com/Maproom/qmapshack/wiki/DocGisItemsTrk2#split-track

There is no real specification about what track segments are. For some devices a segment is another round within a course. Others start a new segment after the GPS receiver had bad reception. Those want to have segments linked with a line.

And then there are other devices that do not start a new track when started a new. And there are users that are unable to start a new track with each tour. Those want do not want to have segments linked. 

QMapShack favours the first use-case and provides the filter for the second one.

**Comment by iw1gfv** [comment]
Hi
I used to split tracks with the filter, but it's not very confortable.
many thanks for the response.

**Comment by kiozen** [comment]
I assume you have a Garmin outdoor GPS. At least these devices produce something like your screenshot. They record a single track (current) and start a new segment when loosing GPS reception or when restarting the device. 

The intended way to operate them is to reset the track and the trip computer with every new tour including height calibration. At the end of the tour the user saves the current track. By that you have several GPX files. Each with a clean track.

By that you do not run into the problem described. And if you have GPS drops during your recording combining the segments is what you want.
