### ISSUE TITLE
Problem with offline Brouter

### ISSUE THREAD

**Issue by swdick** [Maproom/qmapshack#103]
On my Xubuntu laptop I installed Qmapshack. I would like to use BRouter to plan routes, but I get the following messages installing it.
The steps I take are the following:
* I choose BRouter (offline) in the routing tab and press Seup
* then the active map is loaded (again)
* I choose local installation  and press Next
* I create the map Brouter in the same map as the QMS maps and install it from the latest zip-file (java is already installed)
* then follows the BRouter setup window with no Profiles on the left, all the profiles in the installed window and an error (Network error: http://brouter.de/brouter/profiles2/ invalid result)
* clicking Next leads to the segment installation , showing the active map but without the option to download segments
* then I click Finish

After this process I have the BRouter map containing 3 maps (profiles2, segments4 and standalone), and .jar, apk, .txt and .zip files
The profiles2 map contains the usual .brf files. The segments4 map is empty.

What am I doing wrong?

**Comment by kiozen** [comment]
Please use the templates for big reporting:
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

Usually I close issues that do not stick to these rules asap. As this is rather detailed I make an exception. But be aware that next time I will even close a detailed issue if it does not use templates.

**Comment by kiozen** [comment]
On second thought I should close that bug report because it lacks the installed QMapShack version. So much to "I ignore templates and o my own inferior report"

**Comment by swdick** [comment]
Sorry for the inconvenience. Shall I make a new posting?

**Comment by swdick** [comment]
Problem: the offline BRouter installation in QMapShack in Xubuntu does not work. It seems it can not connect to BRouter web to obtain profiles and sections.

Steps to reproduce: follow the installation instructions in QmapShack

Expected behaviour: a working BRouter installation in QMapShack containn the required profiles and map sections.

Desktop: Xubuntu 1.18.04.4
QMapShack version: 1.10.0 installed from the Xubuntu installer. I tried to install a more recent version but could not get it done.

**Comment by kiozen** [comment]
1.10.0 is too old. BRouter switched from `http` to `https` in the meantime.

I just tested on the actual release and everything works as expected.

**Comment by swdick** [comment]
I can not get the recent version installed though I follow your instructions on the Issue page

**Comment by kiozen** [comment]
Then it's an issue of your distribution to provide up-to-date packages. Version 1.10.0 is from December 2017(!).

It's really recommended to update your Linux installation frequently. It's just a waste of time for everyone to run into bugs that have been fixed for ages.
