### ISSUE TITLE
Importing from GPX files incredibly slow

### ISSUE THREAD

**Issue by mbirth** [Maproom/qmapshack#106]
**Describe the bug**
Importing GPX files into a database (SQLite) folder takes ages. E.g. importing 123 GPX files (~1.4 MB total) takes ~3:30min until the "open files" dialog vanishes. Then, an empty "Copy item..." dialog appears and it takes another 50 seconds until the dialog becomes usable. This applies for any further duplicate items as well. First, an empty frame appears, then 50 seconds later, the dialog gets clickable.

Total time for importing 123 GPX files: 27 minutes 40 seconds. That's 13.5 seconds per GPX file which only contains a bunch of waypoints, nothing fancy. Broken down to waypoints, it's 2.3 seconds for one(!) single waypoint. On an Intel Core i5-6200U.

**To Reproduce**
1. Have SQLite database opened
2. Right-click an empty folder in the database
3. Select "Import from files..."
4. Select a bunch of GPX files

**Expected behavior**
A fast import of files into the database.

**Desktop (please complete the following information):**
 - OS: xUbuntu 19.10
 - QMapShack Version 1.13.1

**Additional context**
Database size is ~30 MB. During import, 1 CPU core is at 100%, the other 3 are bored.

**Comment by kiozen** [comment]
I can' t confirm. I imported ~150 GPX files with 1112 items (waypoints and tracks) into the database. It took less than 30 seconds. Hard to tell as there where dialogs to confirm because of duplicated elements.

**Comment by mbirth** [comment]
I've tried with an empty database and it was not really faster. I don't know, why the database import is so slow for me - hence this ticket. Is there anything I can check?

This is the folder with those 123 files: [F.zip](https://github.com/Maproom/qmapshack/files/4213572/F.zip)

**Comment by kiozen** [comment]
Well this takes a bit longer as it has 5172 items to import, however it's still below a minute. But I agree that a process bar would be nice.

Usually file access should be cached by your operating system. However if the system is low on memory it's using swap memory which is especially on Linux slow.

If it's not memory you could try to optimize the database access. Have a look at:
```
bool IDBSqlite::setupDB(const QString& filename, const QString& connectionName, QString &error)
...
    QUERY_RUN("PRAGMA locking_mode=NORMAL",    return false)
    QUERY_RUN("PRAGMA temp_store=MEMORY",      return false)
    QUERY_RUN("PRAGMA default_cache_size=50",  return false)
    QUERY_RUN("PRAGMA page_size=8192",         return false)
    QUERY_RUN("PRAGMA synchronous=off",        return false)

```
There is probably space to improve. This code is quite old. Some of the settings are deprecated by now.

**Comment by kiozen** [comment]
Could it be that on your PC all theses routes are calculated? On mine there aren't as I do not have routing data for that area. 

If that is the case they are probably re-calculated when loaded. That would explain the long time.

**Comment by mbirth** [comment]
I also only have a small Routine database for the area around Berlin, Germany. The imports I've done are from France, Italy, etc. So it shouldn't re-calculate anything.

The SQLite PRAGMAs above also don't look bad. If I find some time, I might have to set up the current dev version to see if that changes anything.

**Comment by kiozen** [comment]
Any news on that? If not I would close the issue.

**Comment by mbirth** [comment]
Yeah, let's close that for now as I currently don't have time to investigate further.
