### ISSUE TITLE
Unable to install latest version

### ISSUE THREAD

**Issue by swdick** [Maproom/qmapshack#107]
**Describe the bug**
I'm sure it's not a bug but as a simple user I am not able to install the latest version.
Too complicated for me. I followed the instructions and run into QT5 problems. After that I am at a loss. 

**To Reproduce**
I followed the instructions: 
    git clone https://github.com/Maproom/qmapshack.git QMapShack
    cd QMapShack
    git checkout dev
    cd ..
    mkdir build_QMapShack
    cd build_QMapShack
    ccmake ../QMapShack
    make

**Expected behavior**
I would very much prefer a file I can install with the Xubuntu software centre.

**Screenshots**
![Schermafdruk_2020-02-12_17-46-34](https://user-images.githubusercontent.com/55924950/74674409-92ab9100-51b1-11ea-9104-0f300f9e5cc3.png)

**Desktop (please complete the following information):**
 - OS: Xubuntu 19
 - QMapShack Version 1.13.1

**Additional context**

**Comment by kiozen** [comment]
Did you consider a tiny glance into the wiki?

https://github.com/Maproom/qmapshack/wiki/DocMain

If you are missing a package of a certain software it make no sense to ask for it at the development site. Packages are the responsibility of the distribution's package maintainers. As a consequence the right place to file a request is the issue tracker of the distribution you are using.

Usually distributions offer alternative package repositories with more up-to-date packages than the official distribution repository. Google is your friend to find out if there is such an alternative repository.

Additionally each distribution has a forum which is also the right place to ask distribution dependent questions.
