### ISSUE TITLE
Geocaching logging page - only 1 server used

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#111]
**Is your feature request related to a problem? Please describe.**
This new feature assumes that geocaches are linked to www.geocaching.com what is by far not true for all geocaches. As soon as a geocache is taken from a different geocache server the new button nevertheless tries to find it at www.geocaching.com and fails with a 404 message.

**Describe the solution you'd like**
Try to identify geocaches not linked to www.geocaching.com and deactivate button " Visit website" in this case or link to the correct server.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by kiozen** [comment]
@pingurus Can you please take care of this one?

**Comment by pingurus** [comment]
Yes, sure

**Comment by pingurus** [comment]
@wthaemelt how do you load geocaches from other services? I'm not sure how the code handles OC caches right now. As far as I can see there is no code in the gpx serialization file directed to non-groundspeak geocaches.

**Comment by wthaem** [comment]
Once I'm taking care of the Russian version of QMS and the Russian quickstart page of the QMS Wiki I'm looking from time to time to https://geocaching.su/?pn=12# (sorry for the Russian content), too. Just to see, if the Russian version works fine. From this server I downloaded a few geocaches. Thus, I have gc*, oc*, tc*, ... geocaches.

I don't know, if there is a fixed rule for naming geocaches. If so, it should be possible to identify those not belonging to geocaching.com. Deactivating the new button should then be easy. With a 404 message from geocaching.com the user things: woops, what happened here with my geocache. In my opinion the 404 should be avoided as much as possible.

BTW: there have been earlier discussions about the contents of the geocache (edit) window in QMS concerning attribute handling in case of geocaches not sticking to the geocache.com rules.

**Comment by pingurus** [comment]
Could you please send me a gpx file of the geocaching.su geocaches, so I can check how they are formatted? I could then properly do the differentiation of the geocaching services in code and fix the server issue.

> BTW: there have been earlier discussions about the contents of the geocache (edit) window in QMS concerning attribute handling in case of geocaches not sticking to the geocache.com rules.

Yes, I know. We have the icons and attribute pictograms of other services [here](https://github.com/Maproom/qmapshack/tree/dev/src/icons/geocaching), the code just needs to be tweaked, to use those aswell.

**Comment by wthaem** [comment]
@pingurus: Attached you find some non-gc and non-oc geocaches:

[TestGeocaches.zip](https://github.com/Maproom/qmapshack/files/4267013/TestGeocaches.zip)
