### ISSUE TITLE
menu is lost after full screen mode

### ISSUE THREAD

**Issue by pva** [Maproom/qmapshack#114]
If I enter fullscreen mode (F11) and select from right-click on the map "Add WayPoint" qmapshack loses menu and all other dockable windows. So I'm able to do is to close the application and then start it again to see the menu again (but not dockable windows).

**To Reproduce**
1. Open qmapshack and activate some Map in maps window. E.g. goolge maps, Sat map.
2. Enter full screen with F11.
3. Press add a Waypoint. A window "Select a Project..." will appear. Press cancel there.
4. Press F11 again - you'll see a window with one tab "View 1" and no menu and Maps window closed as well.

**Expected behavior**
I expect to see the menu and Maps dockable window.

**Screenshots**

This is the window I see at the end:

![Снимок экрана от 2020-03-10 19-15-49](https://user-images.githubusercontent.com/92356/76334544-3c3ef780-6304-11ea-8ed8-3232286e531d.png)
.

**Desktop (please complete the following information):**
 - OS: Gentoo Linux, i3 tile window manager
 - QMapShack Version:  1.14.0 with a patch for the current git HEAD (ec889f90)

**Comment by kiozen** [comment]
I can't reproduce. However I use KDE as window manager.

**Comment by pva** [comment]
Is there anything I can do to help and find what causes this issue?

**Comment by kiozen** [comment]
There are two ways to fix a bug:

1. Developers can reproduce the bug. If that is possible it's usually fixed. However in this case I can not reproduce it. 

2. The user is trying to debug the problem. In this special case debug messages to stdout (qDebug()) should do the trick. But that takes a but of knowledge how to compile. And how to read the code. It's not  that hard and I can give pointers and hints. But in the end you have to be creative on how to circle down the issue.

**Comment by pva** [comment]
>     2\. . In this special case debug messages to stdout (qDebug()) should do the trick.

Could you give me a starting point? Where it is better to put qDebug()? Compile software from sources and print debugging messages is not a problem here.

**Comment by kiozen** [comment]
I close the ticket for now. This seems to be no issue to anyone else.
