### ISSUE TITLE
Filter edit field lost

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#116]
**Describe the bug**
* Select entry `Filter project` in a project context menu.
* In older QMS versions an edit field with some decoration is shown below the project name in the workspace, in the latest commit (star waypoints) this field is missing and thus filtering doesn't work anymore. Compare attached image which shows the 2 different layouts.

**To Reproduce**

see description of bug

**Expected behavior**

Old behavior should be re-established

**Screenshots**
![Filter](https://user-images.githubusercontent.com/55309218/76507924-e2e2df80-644d-11ea-8c38-52b1a332f893.jpg)

**Desktop (please complete the following information):**
 - OS: Windows10
 - QMapShack latest commit (star waypoints)

**Additional context**

None

**Comment by pingurus** [comment]
Ah :man_facepalming: :man_facepalming: 
I didn't think of that. It's a quick fix though.
