### ISSUE TITLE
Too much whitespace in extended search help window

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#118]
**Is your feature request related to a problem? Please describe.**

The extended search help window displays a long list in its lower part. When trying to make this window higher to see the complete list the upper part of the window is getting higher, too, and a lot of unnessary whitespace is added before the last entry in the lower part can be seen (compare screenshot)

.

**Describe the solution you'd like**

Add possibility to change height of upper and lower part separately to avoid unnecessary whitespace in window.

**Describe alternatives you've considered**

None

**Additional context**

 None

![HelpExtSearch](https://user-images.githubusercontent.com/55309218/76524234-ff8d1080-6469-11ea-8231-5e6428c0067b.png)

**Comment by kiozen** [comment]
@pingurus can you please have a look at that?

**Comment by pingurus** [comment]
Problem is, I can't pull the window long enough on my screen :laughing: 
I can create a pull request with a guess what would fix it and @wthaem has to test it.

**Comment by pingurus** [comment]
@wthaem do you have access to my fork? If yes, can you please test the current version? It is just a try, maybe it works good enough.

**Comment by wthaem** [comment]
Yes, I do have access. I'll have a look.

BTW: If you have a second (old) monitor, you might plug it in to your computer and if it runs under Windows, you can easily extend the display area (use Windows key - P).

**Comment by wthaem** [comment]
Whitespace still there (maybe, with slightly different behavior).

**Comment by pingurus** [comment]
And now?

**Comment by wthaem** [comment]
The latest commit I found on the server is c79681b. And this is the one I used for my test. Timestamps on files: 13.03.20 00:09. What is the commit I have to test?

**Comment by pingurus** [comment]
The latest commit is ec889f9, that is the new one (I made a commit --amend and the forcce pushed)

**Comment by wthaem** [comment]
Got compiler errors:

~~~

1>------ Erstellen gestartet: Projekt: qmapshack, Konfiguration: Release x64 ------
1>Automatic MOC for target qmapshack
1>Generating qrc_resources.cpp
1>mocs_compilation.cpp
1>...\src\qmapshack\qmapshack_autogen\include_Release\KMTMJ3IBZ2/moc_CGisListWks.cpp(292): error C2039: "slotTagItem": Ist kein Element von "CGisListWks"
~~~

plus a few similar ones.

**Comment by pingurus** [comment]
I just checked, it compiles to me and my version is equal to the one on the server

**Comment by wthaem** [comment]
Your link brings me to

https://github.com/Maproom/qmapshack/commit/ec889f90fb639c9dfc57de761eafe369c3b4d948

Here I click "Browse files" and come to 

https://github.com/Maproom/qmapshack/tree/ec889f90fb639c9dfc57de761eafe369c3b4d948

Both links show your commit label ec889f9.

The last window tells me: "Latest commit ec889f9 17 days ago"!

Where is my misunderstanding? The short commit label should be unique and should point to a unique long commit label - shouldn't it?

**Comment by pingurus** [comment]
My mistake, it's c79681b, sorry

**Comment by wthaem** [comment]
With this commit the whitespace issue has gone.

In my original proposal I had in mind to change the relative size of the upper and the lower part of the window, too. This should imply a cursor of the form shown in the attached image (don't know, how it is called). Would this imply a lot of additional work? Advantage: currently, the size of the upper part seems to be limited and there is no chance to see the full text in the upper part at once (keeping the window small). Using the additional possibility of changing the relative sizes it would be possible to increase the size of the upper part while decreasing the size of the lower part. Thus, one could have the full text in the upper part.

![resize](https://user-images.githubusercontent.com/55309218/76677413-4c89f780-65ce-11ea-990b-97debdfd3c96.png)

**Comment by pingurus** [comment]
@kiozen what is the Qt widget to make this possible?

**Comment by kiozen** [comment]
QSplitter
