### ISSUE TITLE
Wrong search path for Qt help files?

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#122]
**Describe the bug**
(Not noticed earlier - sorry)
In the QMS Windows version the QMS files are stored in the directory `msvc_64/Files`. But the qmapshack.exe can be started from a different directory, say `cwd`, using the full path to call it.

Currently, QMS tries to find its Qt help files relative to `cwd`. This file distribution can't be handled by the QMS installation because `cwd` is not known.

**To Reproduce**
1. Save Qt help files in `msvc_64/Files/doc/...`
1. Start QMS from outside `msvc_64/files`and press F1 - result: empty help window.

**Expected behavior**
QMS should search its help files relative to `msvc_64/files` ( the location of qmapshack.exe).

**Screenshots**

not necessary
**Desktop (please complete the following information):**
 - OS: Windows 10
 - QMapShack latest commit

**Additional context**

none

**Comment by pingurus** [comment]
On my Ubuntu 19.10 VM the help window is empty too, regardless of wether I open it via F1 or the question mark and then help (Started via Qt Debugger).

**Comment by kiozen** [comment]
did you do `make install`? The help files must be copied into the correct path. And this will be done by the install target.

The initial ticket is expected. @huirad has to fix the code for Windows.

**Comment by pingurus** [comment]
> did you do make install? The help files must be copied into the correct path. And this will be done by the install target.

No, I didn't.

**Comment by kiozen** [comment]
try it :smile: It's the same with translation. You have to install to get latest update.

**Comment by pingurus** [comment]
I did do
```
make
sudo make install
qmapshack
```
Same result, also if I start it from the programs screen 🤷‍♂

**Comment by huirad** [comment]
Heeey, no hurry!

**Comment by kiozen** [comment]
Haha, now that you respond to the topic I could assign you. Your fault :imp: :stuck_out_tongue:

**Comment by kiozen** [comment]
@pingurus search the debug log for `search help at:` and cross check the path.

**Comment by pingurus** [comment]
Where do I find the debug log?

**Comment by kiozen** [comment]
start qmapshack with paramter `-d` from console.

**Comment by pingurus** [comment]
```
2020-03-19 9:14:14.242 [debug] search help at: "/usr/local/share/doc/HTML/QMSHelp.qhc"
2020-03-19 9:14:14.315 [debug] QUrl("qthelp://qms/doc/doc/html/DocMain.html")
2020-03-19 9:14:14.316 [warning] QTextBrowser: No document for qthelp://qms/doc/doc/html/DocMain.html

The qhc file exists.
```

**Comment by kiozen** [comment]
Interesting. That's what I get:
```
2020-03-19 9:51:17.896 [debug] search help at: "/usr/share/doc/HTML/QMSHelp.qhc"
2020-03-19 9:51:17.902 [debug] QUrl("qthelp://qms/doc/doc/html/DocMain.html")
2020-03-19 9:51:17.903 [debug] QUrl("qthelp://qms/doc/doc/html/css/qmsstyle.css")
2020-03-19 9:51:17.908 [warning] QMainWindow::addDockWidget: invalid 'area' argument
2020-03-19 9:51:18.021 [debug] QUrl("qthelp://qms/doc/images/maproom1.png")
2020-03-19 9:51:18.062 [debug] QUrl("qthelp://qms/doc/images/DocGettingStarted/FlagUk.jpg")
2020-03-19 9:51:18.063 [debug] QUrl("qthelp://qms/doc/images/DocGettingStarted/FlagDe.jpg")
2020-03-19 9:51:18.063 [debug] QUrl("qthelp://qms/doc/images/DocGettingStarted/FlagRu.jpg")
2020-03-19 9:51:18.123 [debug] QUrl("qthelp://qms/doc/images/DocGettingStarted/FlagEs.jpg")
2020-03-19 9:51:18.151 [debug] indexing started...
2020-03-19 9:51:18.293 [debug] indexing finished...
```

Sure that you did not mess up with `/usr/` vs `/usr/local` and work on outdated files?

**Comment by pingurus** [comment]
Well, at least I didn't mess things up intentionally. :laughing: 
What could have messed it up?

**Comment by kiozen** [comment]
if mix up installations to `/usr` and `/usr/local` you might end up in different parallel versions. Make sure the files in `/usr/local/share/doc/HTML/` are the ones from the current build.

If that does not work you have to check if you can get some error status from the help engine in `CHelp`

**Comment by wthaem** [comment]
My Windows log looks similar to kiozen's one! I haven't updated the Ubuntu version, thus no test yet.

**Comment by pingurus** [comment]
The  files in `/usr/local/share/doc/HTML/` are dated to yesterday, when I did `make install`.
I will try to find some more info later.

**Comment by wthaem** [comment]
QMS with VMWare Ubuntu 18.04 shows Qt help as expected without any additional copying of help files.
