### ISSUE TITLE
Missing translation?

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#123]
**Describe the bug**
The search tab in the Qt help window has a button labeled "Search". This label is not translated. The English term is still there when using a German OS (thus, it isn't a button created by the OS).

**To Reproduce**

* Press F1 to open the help window
* Goto the search tab and check button

**Expected behavior**

The text label shown on the button should be translated.

**Screenshots**

![MissingTranslation](https://user-images.githubusercontent.com/55309218/76833781-42653480-682c-11ea-968b-e1e7e5f12049.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, German
 - QMapShack latest commit

**Additional context**

This might be a Qt problem!

**Comment by kiozen** [comment]
This is nothing to be solved in QMapShack as this part of the dialog is produced by Qt's help engine. Probably some translation files of the Qt library are not in place.
