### ISSUE TITLE
Missing icon for not available geocache

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#125]
**Describe the bug**
After a change of the availability of a geocache in the GPX file to "not available" the geocache doesn't have an icon anymore.

**To Reproduce**

1. Take GPX file of geocache and change property from `available="True"` to `available="False"`
2. Open geocache in QMS and check geocache in map view

**Expected behavior**
Icon should be visible and grayed out.

**Screenshots**

![MissingIcon](https://user-images.githubusercontent.com/55309218/76964375-e9c49300-6922-11ea-9110-04d110698b93.png)

**Desktop (please complete the following information):**
 - OS: Windows10, German
 - QMapShack latest commit, using English language file, but no change, if using German language file.

**Additional context**
none

**Comment by kiozen** [comment]
@pingurus please have a look

**Comment by pingurus** [comment]
@kiozen, can you reproduce the problem? On my Ubuntu 19.10 VM it works.

**Comment by kiozen** [comment]
I have to admit I have to PQ to test. So I merged just by analyzing the code.

**Comment by kiozen** [comment]
I have an idea. QMapShack creates the grayscaled icons on the harddisk in the waypoint icons path. Probably Windows has a problem with the `:` in the name. aka `c:`
