### ISSUE TITLE
Wrong result of status search?

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#126]
**Describe the bug**

Insert `status equals available` into the search field. Search result: waypoints not being geocaches and not having a status are included in the search result.

**To Reproduce**

see previous point.

**Expected behavior**

Only geocaches have a status property. Thus, only geocaches should be included in the search result.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows10
 - QMapShack latest commit with English language file

**Additional context**
none

**Comment by kiozen** [comment]
@pingurus please have a look
