### ISSUE TITLE
Again: Missing geocache icon

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#129]
**Describe the bug**
I don't understand what happened: The icon for a not available geocache is missing again.
I got the latest commits 7a52be4 and 459f6f9 (and others) with a git pull and compiled them (rebuild all). Result: again missing geocache icon. At the moment of pulling there where no pull requests in the repo!

This differs from the result I got this morning with another commit (19bcfaf).

Could somebody try to explain what went wrong?

BTW: The icon is missing in the map view and in the workspace window, too.

**To Reproduce**

see previous discussion on same topic

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. OS X, Debian, Suse, Windows]
 - QMapShack Version [e.g. 1.13.1]

**Additional context**

**Comment by pingurus** [comment]
Could you please check wether there are grayed-out icons in the waypoint icons folder (`C:\Users\your-username\.config\QLandkarte\WaypointIcons`)?

**Comment by wthaem** [comment]
> Could you please check wether there are grayed-out icons in the waypoint icons folder (`C:\Users\your-username\.config\QLandkarte\WaypointIcons`)?

No, directory is empty (even after using both Qt versions).

But I believe I found the reason for the confusion (grey icons can be seen vs. grey icons can't be seen): As soon as I use Qt5.13.2 everything is ok (used when testing pull requests). If I switch to Qt5.14.0 (used when pulling sources with git) the icons disappear. Thus, the  Qt5 version seems to be important and Qt5.14.0 caused trouble on my side more than once.
