### ISSUE TITLE
DEMs: Make the scale range control cut off not only rendering but also loading or requesting the data.

### ISSUE THREAD

**Issue by mitxel-m** [Maproom/qmapshack#132]
**Is your feature request related to a problem? Please describe.**

- For maps: You can control visibility with the scale range controls. Consequently, QMS does not load or request the map out of that range.

- For DEMS: you can control the visibility of hillshading, slopes, and elevation limit with the scale range control. However, even if you limit a scale range, QMS still loads/requests the elevation data for all the canvas area.

This leads to slow down the loading of the map when zooming out, and to avoid it the only remedy is to disable the DEM. Then, after scrolling the map and zooming in, re-activate it, which is tedious and illogical.

**Describe the solution you'd like**

Make the scale range controls work identically for Maps and DEMs.
More specifically, for DEMs make the scale range controls cut off not only rendering but also loading or requesting the data.

**Describe alternatives you've considered**
I honestly haven't found any

**Additional context**

One might want to cut the hillshading but still see the elevation data. However, this makes no sense if you make a very outer zoom with a very dense DEM, because at a distant zoom level you don't have enough precision with the mouse to know what point you are pointing at.

It makes more sense to work as with maps, loading two DEMS with different resolution, one on top of the other, and control which one will be used with the scale range controls. This is really useful to hillshade garmin maps, but for now you are requesting all the data. 

For elevation profiles and status line, QMS gives us the data of the first one it finds, so the logical thing is to place the densest one on top, then another one more coarse.
 
But to make this work smoothly it is essential to limit the data load with the scale range slider.

**Comment by mitxel-m** [comment]
**A bit more of context**

For now, the only effect of the scale range is on the display of hillsade, slopes and elevation limit. Even if we are outside the scale range, QMS always loads/request elevation data, regardless of whether the scale range is enabled or not.

This is good for drawing tracks and waypoints, but has the downside that moving and zooming out on the map slows everything down.

Another problem is that the DEM data request is not visible, this leads some users to think that QMS is very slow loading maps, not realizing that the problem is that they have activated a too dense DEM for the zoom level they are using.

**Alternatives to handle this in the current version:**

- Deactivate/Reactivate the DEM according to the zoom level, which is a bit boring, and then we have already lost the advantage we had to get elevation data while drawing a track.

- A trick for drawing tracks: Use two views. First, a 'dummy view' with a very dense DEM activated and without any map. We would have this dummy view parked. Second, another view without DEM or with a lighter DEM where we draw the track. Once the track is created, we apply the DEM elevation filter, and we choose the 'dummy view' DEM.  

**How could it be improved?**

- For the map view: Make the scale range controls work identically for Maps and DEMs. More specifically, for DEMs make the scale range controls cut off not only rendering but also loading or requesting the data. This would improve the mapView redraw, because we don't request unnecessary data. 

- For drawing tracks/waypoints: Always apply the first DEM at the top of the view, regardless of the scale range. So we don't need to use the trick of the 'dummy view'. This is logical because requested elevation data for a track is not so much. 
 
I don't know if this can be coded in a reasonable way, but IMHO it would be the most practical from the user's point of view.


Of course, if this improvement is implemented, I can take care of updating the wiki with the necessary information

**Comment by kiozen** [comment]
Please test pull request: https://github.com/Maproom/qmapshack/pull/155
