### ISSUE TITLE
Wrapper supporting Mapsforge maps and themes

### ISSUE THREAD

**Issue by JFritzle** [Maproom/qmapshack#133]
Currently, locally installed Mapsforge maps are not directly supported by QMapShack. And it seems, they will not be directly supported in near future. But chapter _Mapsforge Maps_ of QMapShack's wiki document _DocBasicsMapDem_ describes how Mapsforge maps can be made available in QMapShack by setting up a local Mapsforge tiles server. For server installation see document.

For my own purpose, i.e. making Mapsforge and in particular OpenAndroMaps maps available and switching easily maps and themes, I have written a wrapper based on above documentation. Wrapper lets initially select and later on switch maps and/or themes while QMapShack keeps running. Wrapper script _Mapsforge_for_QMapShack.tcl_ is written in Tcl/Tk command language and has been successfully tested on Windows and Linux operating system. Execution requires Tcl/Tk 8.6 or newer command interpreter to be installed. Script gets executed by command:
`wish Mapsforge_for_QMapShack.tcl`
Before, some script variable settings (folders, executables, ...) have to be modified to match local installation and environment. These variables are described and set at the beginning of script. 

Perhaps someone else is interested? Then it may be worth to complement wiki and to provide a download link there.

Script _Mapsforge_for_QMapShack.tcl_:
[Mapsforge_for_QMapShack.zip](https://github.com/Maproom/qmapshack/files/4380602/Mapsforge_for_QMapShack.zip)

Screenshot of wrapper (Windows):
![Wrapper_GUI_Windows](https://user-images.githubusercontent.com/62614244/77532859-0407ef00-6e96-11ea-8966-645238e5b346.png)

Screenshot of wrapper (Linux):
![Wrapper_GUI_Linux](https://user-images.githubusercontent.com/62614244/77532871-08340c80-6e96-11ea-9d23-8c2d9ae82aec.png)

**Comment by kiozen** [comment]
You are always welcome to edit and enhance the Wiki. Just go ahead.

**Comment by kiozen** [comment]
But please stick to the templates next time. Even this is a very decent feature request it encourages others to skip using templates. 

https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
