### ISSUE TITLE
Windows: Compiler error on _MKSTR_1 

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#137]
**Describe the bug**

From MSVC compiler output:

~~~
1>CMainWindow.cpp
1>D:\QtProjects\QMS\QMapShack\src\qmapshack\CMainWindow.cpp(98): warning C4003: Nicht genügend Argumente für den Aufruf des funktionsähnlichen Makros "_MKSTR_1".
1>D:\QtProjects\QMS\QMapShack\src\qmapshack\CMainWindow.cpp(98): error C2059: Syntaxfehler: ")"
~~~

line 98:

~~~
 setWindowTitle(WHAT_STR + (QString(VER_SUFFIX).isEmpty() ? "" : QString(".") + VER_SUFFIX));
~~~

**To Reproduce**

Run MSVC compiler

**Expected behavior**
successful compilation

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows10, MSVC 15.9.5
 - QMapShack latest commit in dev branch

**Additional context**
none

**Comment by kiozen** [comment]
Please consider to use better titles. "Compile error" is as good as "geht nicht" to describe an error.
