### ISSUE TITLE
Progress bar at startup keeps stealing focus

### ISSUE THREAD

**Issue by FabianInostroza** [Maproom/qmapshack#142]
When I open QMapshack there is a popup window with a progress bar that appears/dissapears and it doesn't allow to change to another application because it brings qmapshack to the front.
This only happens when you have a lot of projects open. I have about 100 fit/gpx files open, not all of them shown in the map.

**To Reproduce**
1. Add a lot of files (gpx or fit) to the workspace
2. Close QMapshack
3. Open QMapshack

**Expected behavior**
There should be only one windows with progress bar created and shown and it should not bring QMapshack to the front.

**Screenshots**
Watch this video:
https://drive.google.com/open?id=1seP2DtyyueWJ6vVs6pmzv94pgpYfCqdV

**Desktop (please complete the following information):**
 - OS: Debian testing
 - QMapShack 1.14.1

**Comment by kiozen** [comment]
I really wonder why one wants to have 100 files open in the workspace. That is not the intended use. But anyway this progress dialog is a nuisance for many other reasons, too, and I already spent quite some effort to optimize it but I couldn't find a good solution that satisfied all needs. It works for normal use. 

I will leave that issue open for 6 months. Maybe someone comes up with a good solution.

**Comment by kiozen** [comment]
No one came up with a good solution.
