### ISSUE TITLE
Feature request: GCJ coordinates support.

### ISSUE THREAD

**Issue by d0u9** [Maproom/qmapshack#145]
**Is your feature request related to a problem? Please describe.**

China uses is its own GCJ-02 coordinates to shift the map randomly according to its WSG coordinates. The china region of google map(not satellite map and hybrid map) are based on GCJ coordinates as well, which means that my tracks(recorded in WSG coordinates) are not aligned to routes show on the map.

**Describe the solution you'd like**
Add an option to set the current coordinates when viewing map.

**Describe alternatives you've considered**
A plugin to convert tracks to GCJ and back.

**Additional context**
![image](https://user-images.githubusercontent.com/7038479/78761100-b8386800-79b4-11ea-8248-872e6f8ca23d.png)

**Comment by kiozen** [comment]
In the menu `View->Setup Map View` you can choose the projection and datum of the map. You can enter your own `--towgs84` transformation matrix. Or maybe even `+proj=longlat +datum=GCJ02` does the trick.

**Comment by d0u9** [comment]
Is that mean Qmapshack currently has predefined GCJ02 datum?

**Comment by d0u9** [comment]
Conversion between Wsg and GCJ is not liner, I don't know if it is possible to use --towgs84 parameter to convert back and forth.

**Comment by kiozen** [comment]
QMapShack uses GDAL/PROJ for all calculations. If GDAL/PROJ supports GCJ02 datum QMapShack supports it. You just have to figure out the correct projection string. I already provided a suggestion how that string could look look like. Did you try it before you start complaining?

**Comment by d0u9** [comment]
Thanks kiozen, I have tried that magic string but failed. Qmapshack repots error: 
```
The value
'+proj=longlat +datum=GCJ02 +a=6378137.0000 +b=6356752.3142 +towgs84=0,0,0,0,0,0,0,0 +units=m +no_defs'
is not a valid coordinate system definition:
unknown elliptical parameter name
```

**Comment by kiozen** [comment]
Ok, that was my result of a 2 minute research. Google finds a couple of other discussions related to GCJ02 and Proj4/GDAL. Maybe you find a hint there. If that fails you are more or less out of luck.

**Comment by d0u9** [comment]
Does Qmapshack implements its own coordinates conversion, or uses thridparties libraries? Maybe, I could find some clues out there by commit issues directly in the thirdparties' forum.

**Comment by kiozen** [comment]
QMapShack relies 100% on the PROJ API V4. All conversions are done by pj_transform().  This API is outdated as PROJ has introduced a new API that does not include the old one. So far the QMapShack project lacks the time and resources to convert to the new API. Therefor we are stuck with the old on.

**Comment by kiozen** [comment]
I close it for now.
