### ISSUE TITLE
European Online DEM25 file does not provide valid data anymore

### ISSUE THREAD

**Issue by pdenessen** [Maproom/qmapshack#146]
**Describe the bug**
The provided "Europe_Online_DEM25.vrt" file does not provide valid data anymore. When replacing the elevation data of GPX trace with the data from this source then it does not provide any or invalid data. 

**To Reproduce**
1. Go to a track
2. Click on "Replace Elevation Data by the view's DEM data"
3. Show the one screen profile data with missing data.

**Expected behavior**
The data is present and profile can be displayed.

**Screenshots**
**Desktop (please complete the following information):**
 - OS: Windows
 - QMapShack Version [e.g. 1.14.1]

**Additional context**
Looks like the source is not valid anymore :
 <SourceFilename relativeToVRT="0">/vsicurl/http://published-files.eea.europa.eu/eudem/entr_r_4258_1_arcsec_gsgrda-eudem-dem-europe_2012_rev1/eudem_dem_4258_europe.tif</SourceFilename>

**Comment by mitxel-m** [comment]
Hi pdenessen

The Europe_Online_DEM25.vrt is pointting to a DEM file provided by the The European Environment Agency (EEA). In fact that DEM was intended for downloading (19 Gb !!) .  Instead of downloading Gb and Gb from places we will never visit  our VRT file is able to requesrt online only the part of the data you have on screen. It is a smarter way of requesting only what is needed, but it depends on the EEA DEM. If the 19Gb DEM has been removed or moved from location at the EEA site our VRTt will not get any data.
I'll take a look.

**Comment by pdenessen** [comment]
Hi mixtel-m
That is my understanding as well. I already managed to download some hrt files and create with the included VRT-Tool such a file. But indeed these files are huge. So the on-line option uis much better. I believe that the EEA has changed something on their site.
I also understood that some map files like those from http://garmin.openstreetmap.nl/ contain elevation data. Is it not possible to include the elevation data from such files ?

**Comment by kiozen** [comment]
Is there any progress on this topic? If not I will remove the file from the package.

**Comment by pdenessen** [comment]
I further checked this website where the EEA offers a lot of files but many of them can not be downloaded, and the connection is refused, so I assume it is a problem on their side. There is a contact on their website and I will try check if they can fix this.

https://data.europa.eu/euodp/data/dataset/data_eu-dem

**Comment by mitxel-m** [comment]
@pdenessen  please, before to take that way can you contact me by mail: nodeslatxapa at gmail.com

**Comment by kiozen** [comment]
@pdenessen please do not approach any authorities in the name of the QMapShack project.

**Comment by mitxel-m** [comment]
Since it is not working anymore I think that issue could be closed.
Fortunately there are more and more EU countries that offer much better online data as WCS service.
I think it's best if users who know about WCS services to share them and add them to the wiki.

**Comment by kiozen** [comment]
Removed file
