### ISSUE TITLE
Misplaced track info window

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#148]
**Describe the bug**
Part of the track info window is hidden and can't be made visible

**To Reproduce**

1. Use a track which is close to the workspace docked at the left side
2. Click on a trackpoint near the workspace
3. The track info window with toolbar pops-up
4. Part of this window is hidden underneath the workspace and can't be made visible because map can't be moved at this moment. Changing the workspace width doesn't help either.

**Expected behavior**
Pop-up window should be positioned so that its full size is within the map window

**Screenshots**
![MisplacedWindow](https://user-images.githubusercontent.com/55309218/79220242-f66dd580-7e53-11ea-9b27-d915f95332d1.jpg)

**Desktop (please complete the following information):**
 - OS: Windows10
 - QMapShack Version 14.1.1

**Additional context**

None

**Comment by pingurus** [comment]
> Part of the track info window is hidden and can't be made visible

The way I solve it for waypoints is to click into the map, drag it a bit and then re-select the item. With tracks you can even just select another part of the track without dragging the window. But no doubt, it'd be nice if that wouldn't be necessary.

**Comment by wthaem** [comment]
Track info window now ok. Thanks.

But while testing found a similar one (there is a copy of the visible track, thus, select one item out of 2):

![MultSelHidden](https://user-images.githubusercontent.com/55309218/79328014-afe0af80-7f15-11ea-8cf3-cfe6aa79b827.jpg)

**Comment by kiozen** [comment]
Won't fix. Depending on the name box this could jump quite far. The idea is to have everything grouped around the mouse. If the user preferes to work at the map borders instead of getting the stuff into focus they have to suffer some side effects.
