### ISSUE TITLE
Question marks/help not working in WPT, route and area edit windows

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#150]
**Describe the bug**

The waypoint, route and area edit windows have a question mark button near the upper right corner. Clicking the question mark sign changes the cursor icon to a "forbidden" one.

**To Reproduce**

As described in previous point: open edit window for WPT, route or area.

**Expected behavior**

Either remove the question mark or open the F1 help when question mark clicked.

**Screenshots**

none

**Desktop (please complete the following information):**

 - OS: Windows
 - QMapShack Version 1.14.1

**Additional context**

none

**Comment by kiozen** [comment]
This is just some funny Qt stuff that is displayed by default and probably depending on the window manager, too. Probably intended to give some help if you click on it and click on something else.  

But I will not spend time on that.

**Comment by wthaem** [comment]
Just as an additional piece of information:

While working with PyQt5 on a similar window I found the flag that controls the display of the question mark. After setting up the UI I added the Python line

~~~
self.setWindowFlag(QtCore.Qt.WindowContextHelpButtonHint, False)
~~~

to suppress the question mark (self: object of the class derived from QDialog).  

Not being a C++ programmer I can't translate this line into C++. In the case of  CDetailsWpt.cpp I think a similar line added to the constructor after the `setupUi(this)` line could be the solution to this issue.

**Comment by kiozen** [comment]
The equivalent would be:

```
setWindowFlag(Qt::WindowContextHelpButtonHint, false);
```

But do we really want to go thru the code, find all dialogs and add that line? My time budget is very limited and mostly consumed by answering questions and tickets and reviewing PRs. So I would prefer to concentrate on real issues.

**Comment by wthaem** [comment]
> But do we really want to go thru the code, find all dialogs and add that line?

No! My comment was just an information about a possibility to suppress the question mark. Thanks for the C++ translation!
