### ISSUE TITLE
Optimize extern created GPX files

### ISSUE THREAD

**Issue by pdenessen** [Maproom/qmapshack#157]
Problem description:
When I load and GPX file from a tour which was created with My Garmin watch it loads the file correctly but with a ton of GPX coordinates.

Solution
Include a function to "clean up" and optimize the file so that the number of unnecessary entries are erased and the file size reduced.

**Describe alternatives you've considered**
Eventually this could be done with using a router

**Comment by kiozen** [comment]
no template used:

https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

**Comment by kiozen** [comment]
gosh: Asking others 4 times to work for your requests and just spent minimal effort to write these requests. Would like to be approached that way yourself?

https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

**Comment by pdenessen** [comment]
Aplogies, I submitted these 4 requests in a row for the first time and didnt realize to fully stick to the template. Shall I reopen the issues with the template or raise new issues?
