### ISSUE TITLE
Read elevation data from map which includes elevation data

### ISSUE THREAD

**Issue by pdenessen** [Maproom/qmapshack#159]
Problem
to get elevation data in the track you need to setup and load data from either on online DEM source, or load the large DEM files on your computer. Therefore you have to be online or allocated large disk space for these files. The program only allows to load the data from these DEM files.

Solution:
Various Image maps, like those from http://garmin.openstreetmap.nl/ contain elevation data as well. I see here two options :
A: include in the DEM window a link to the linked online or off line MAP files and treat the MAP files as DEM files.
B: Change the already available "Replace elevation function" in the track to chose between the DEM files or MAP files.

**Comment by kiozen** [comment]
No template used:

https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
