### ISSUE TITLE
Routino route instruction export

### ISSUE THREAD

**Issue by kiozen** [Maproom/qmapshack#16]
From Bitbucket issue:

I’d like to submit the following feature request. When switching to QMapShack I embraced all its wonderful features and flawless communication with GPS devices. However, when converting a route to a track the waypoints with instructions from Routino are lost. Therefore, I propose to extend the route-to-track conversion by adding the Routino waypoints and their instructions for routing on GPS devices.

‌

Many thanks in advance,

Jens

**Comment by kiozen** [comment]
Don't really understand what's wanted.

**Comment by kiozen** [comment]
No answer for about a month.

**Comment by repomaa** [comment]
I think what's wanted (at least that's how i see it):

add actual waypoints to the project from the route instructions so that devices without routing support (eg. etrex10) can use those for (sort of) turn-by-turn navigation.
