### ISSUE TITLE
Set a default source for the DEM file as standard

### ISSUE THREAD

**Issue by pdenessen** [Maproom/qmapshack#160]
Problem:
When you now create or load a track then the default color of the track will be a standard color. I then load the elevation data, if not present, and switch to the style tab of the track info and set the source to "Slope". I need to do this for every track again.

Solution:
Make a default setting for the program to select the slope, or other source, as default for the color of the track. So it is not needed to change this every time manually.

**Comment by kiozen** [comment]
no template used:

https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
