### ISSUE TITLE
Set track color to slope value during creation and routing

### ISSUE THREAD

**Issue by pdenessen** [Maproom/qmapshack#161]
Problem:
When I start creating a track then the router (Routino offline) starts drawing the best route but with a single color in pink. You can at that moment not see the slopes in that track.

Solution:
Color the track to the slope value already during creation of the track so the user can immediately see if there are steep hills or descents. If her does not like it then he immediately can check for alternative ways.

**Comment by kiozen** [comment]
No template used:

https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
