### ISSUE TITLE
Add a function to filter track points

### ISSUE THREAD

**Issue by pdenessen** [Maproom/qmapshack#162]
**Is your feature request related to a problem? Please describe.**
When I load a GPX file with a recorded track then this file containes a lot of recorded trackpoints. This can look very messy on the map if you see all the necessary maps and the file is unnecessary large.

**Describe the solution you'd like**
Various programs,like Garmin Basecamp, offer tools to reduce these number of points.

**Describe alternatives you've considered**
Please check the screenshot and include a function in QMapShack where the tool reduces or filters the number of points.

**Additional context**
![filter trackpoints](https://user-images.githubusercontent.com/11139454/79691186-5c949700-825e-11ea-8b8a-dbf11a2d7ffb.png)

**Comment by kiozen** [comment]
QMapShack already has a large set of filters including those to reduce the number of points:

https://github.com/Maproom/qmapshack/wiki/AdvTrkFilters

Why aren't these filters not useful for you? Didi you even consider using them?

**Comment by pdenessen** [comment]
I knew them for the elevation but overlooked the first filter settings.
I miss however the automatic function and the time function.
The time function is deleting the points between ttwh point sbased on the set interval. 
The automatic function should be a more "intelligent" setting of the zero speeds drift and where you should get a few options (5) and the tool will do the filtering.
Further would it be good to add the filter access directly in the list op options when right clicking on the track in the Workspace window or in the view window.

**Comment by kiozen** [comment]
But there is an automatic function. This is using Douglas Peuker. And there is a zero speed drift filter. If that isn't sufficient for you please provide better algorithms.

Please keep in mind you are asking others to spend their spare time on stuff you want. Don't make them also think for you. If you want something come up with a very detailed and definite request. You won't persuade anyone to sacrifice time with that kind of vague requests. Especially not if it's about a very complex topic like filters. 

> Further would it be good to add the filter access directly in the list op options when right clicking on the track in the Workspace window or in the view window.

This was already requested in the past. After a deep consideration and lengthy discussions it was decided not to do it. Not all filters are fire and forget. And this would have lead to a very inconsistent UX.

**Comment by kiozen** [comment]
No feedback. I guess the topic is resolved. Close it.

**Comment by marco44** [comment]
Hi, sorry to "resurrect" this, I'm having the same question, and I agree the Douglas-Peuker is probably the solution. I'm limited by the UI to removing points separated by 99m (max value the input box will allow), I suppose just allowing to input a larger value would be nice. For instance, in my test track file, I have 2500 points, and 99m makes it possible to trim it to about 200 points, and I'd like to be a bit more aggressive. 

Like being able to do it at 1km, 5km, whatever.

I could do a PR for this, I suppose it's not that complicated to allow for one or two more digits in this input box, but would it be interesting ?

**Comment by kiozen** [comment]
Not sure if you understood the  Douglas-Peucker algorithm. The configuration value is not the distance between points. It's the maximum error the new track can deviate from the original one. With 99m the new track does not have anything to do with the original one.

So I doubt this will result into anything generally usable. Probably there are better algorithms to reduce points by that extent. Even an adaptive algorithm  to fit a target amount of points would be interesting. But I doubt this can be achieved by simply increasing the the  error value in the   Douglas-Peucker algorithm.

**Comment by marco44** [comment]
Yeah, sorry, extremely bad formulation by me about this distance thing... still, raising this "distance" still results in a more "simplified" track right ?

And yeah the track has nothing to do with the original one, maybe I should explain my usecase so that I make more sense (or not, maybe there is a smarter solution to my problem than what I thought of)

I've got a group of friends with whom I'm motorbiking. They most of the time prepare their trips using Basecamp because they own Garmin GPSes. I don't have one, and my GPS is limited to 50 waypoints per route, so I have to redo their routes to suit my GPS. What I can get though is them producing tracks of all the routes so I can import them. But I have like 3000 track points, so I'm looking at trying to simplify this to "about" 50 (I can simplify the rest by removing some by hand), so that I can have a route that is the same as theirs (if I just import their route, I often have some difference...). I want to also thy this as a way to get from a random track recorded by the GPS into routing direction for replaying it another time. It's not perfect, but I figure it would probably do like 90% of the job.

Anyway, I may be totally wrong about the way I'm doing this, so please feel free to correct me

**Comment by kiozen** [comment]
If you raise it to more than a couple if meters results will get more and more unexpected. It really depends on the shape of the track.

I doubt it will solve your problem. Automatic routing is based on an algorithm and the available database. Blindly reducing a track to some arbitrary points on the track and using auto-routing to restore the track hardly works. It might work on some examples. And there will be others that miserably fail. 

Some reasons for failure:

* Stored positions for a street in one database do not match those from another database. On streets with divided lanes (e.g. highway) this can result into very peculiar results.
* One of the databases lacks a street or a connection between two streets. As a result you will get peculiar routing or routing might fail completely 
* Routing results are based on weights. A weight usually is calculated by distance and speed. If there are two options with very close weights it depends on the algorithm. e.g. take the main road or shortcut thru residential area.

Even in the Garmin Universe routes can differ between Basecamp and the devices. You need matching software and the same map.  Exporting those routes into another non-Garmin device is close to impossible unless you spend quite some manual effort.

**Comment by marco44** [comment]
Yes, I'm still doing that manual effort looking at and fixing the final route and comparing it with the track. It's just that starting with my friends tracks (or a real track from a recorded trip) and cleaning it automatically as a first step is much easier than manually removing 2900 out of 3000 points, or starting from scratch. Right now, I still have way too many of those points on some tracks (I totally agree, it's depending on their shape, it's worse with round-trips, which is what I mostly have).

**Comment by kiozen** [comment]
Best practice would be to load the track into the preferred navigation software and draw a route by adding intermediate points until it matches the loaded track. If that is possible with your preferred navigation software.

The problem with routes is that there is no common agreement how to export them between different software solutions. It's always a vendor specific island solution.
