### ISSUE TITLE
Hide invidual tracks within a Project

### ISSUE THREAD

**Issue by pdenessen** [Maproom/qmapshack#163]
**Is your feature request related to a problem? Please describe.**
When I have a project with multiple tracks then I cal select to view or hide this project with all its related tracks. I can not view individual tracks within this project but need to see them all.

**Describe the solution you'd like**
Add select boxes, as you have for the projects, a level deeper to the tracks and give it a option to easily hide or unhide individual tracks

**Describe alternatives you've considered**
You can put the tracks in different projects and select these but this those not works out with many tracks.

**Additional context**

**Comment by kiozen** [comment]
This has been already requested and rejected multiple times. The workspace is not a database to store all your data. That is what the database is intended for. You can load single items from the database into the workspace. Never have more stuff in the workspace than needed. It will slowdown QMapshack. The workspace can easily be corrupted by a crash or by switching between different version of QMapShack. In that case you might loose data.
