### ISSUE TITLE
Workspace filter is not applied to newly loaded projects

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#164]
**Describe the bug**
The Workspace filter is not applied to a project that was loaded to the workspace after the filter was typed in.

**To Reproduce**
1. Type a filter to the workspace
2. Load a project that contains some items that should be excluded
3. Check and see that the items that should be excluded are still there

**Expected behavior**
The filter that applies to the workspace should always apply to all projects.

**Screenshots**
No need

**Tracebacks**
No need

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - QMapShack Version 1.14.1

**Additional context**
If I'm already at it, I will check if I can find some way that the filter is only invoked if some time has passed after the last letter has been typed. Right now it is a bit annoying to filter a list of 1000 Geocaches. (I know @kiozen that you don't think that one should have loaded that many items to the workspace, but there are 1000 Geocaches in my moving radius and I don't want to go to the website all the time to download another small portion :wink:)

**Comment by kiozen** [comment]
:laughing: well yes pocket queries....
