### ISSUE TITLE
Make option to disable map/DEM help

### ISSUE THREAD

**Issue by ford--prefect** [Maproom/qmapshack#170]
Working on small monitors with QMS it is sometimes tedious when switching maps or DEMs, because most of the respective (docked) window is blocked by the respective help overlay (big questionmark and help text) so one can barely see the available objects.
While this help is certainly important for new users and should be shown by default, I propose an option to disable it.

![qms_help_blocking](https://user-images.githubusercontent.com/7083300/80348967-dcc68800-886e-11ea-94ca-e15633c0272d.png)

**Comment by kiozen** [comment]
Please stick to the template policy:

https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

Short: It disappears the moment you activate a map or DEM. I want to keep it that way. By that all users know what to do if there is a list of maps but nothing to see.

**Comment by ford--prefect** [comment]
Sorry for not using the template, will do next time.

As I said, I understand this is a crucial feature for new users and reduces the amount of support requests significantly. But for experienced users this can be a burden, so I kindly ask you to shortly consider my point. I'm also willing to use other workarounds (e.g. invisible always-activated maps/DEMs?), if you give me a hint in what direction to go.
Thank you and sorry for bothering you again on the closed issue.

**Comment by kiozen** [comment]
If you do not want to use DEM why don't you just hide the dock widget? 

menu->Window->Dig. Elev. Model (DEM)

Or use the tool button in the toolbar.

**Comment by ford--prefect** [comment]
Well, I'm occasionally using the DEM as well, but you are right - I don't often change that so I could hide the DEM panel. Thanks for the very obvious solution (didn't occur to me anyways…).

**Comment by kiozen** [comment]
And you can rearrange and stack the dock widgets to save screen real estate.
