### ISSUE TITLE
FIT files not visible if opened with QMS 'Load gis data' menu

### ISSUE THREAD

**Issue by Rawbit** [Maproom/qmapshack#171]
If I like to open Garmin FIT files via the QMS 'Load gis data' menu the FIT files are not visible.

**To Reproduce**

1. Go to Menu 'Data' > 'Load Gis data'
2. Open the folder which contain the FIT files
3. No FIT files are visible

**Expected behavior**
FIT files are visible.

I use Debian stable with QMS 1.14.1 develop self compiled.

Kind regards

Rawbit

**Comment by wthaem** [comment]
Works with Windows10 as expected. Tested with FIT files in source repo - unittest folder. FIT files visible in file selection dialog and after loading in QMS. Be careful, not all features of FIT files can be understood by QMS!

**Comment by kiozen** [comment]
This is just another one of these sloppy bug reports that took 3 seconds to shit into the issue tracker, ignoring most of the templates. So I will handle it the same way. My FIT file is working. Case closed.
