### ISSUE TITLE
Misleading help text for DEM range slider

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#173]
**Is your feature request related to a problem? Please describe.**
The docked DEM window displays a range slider for activated DEM files. The buttons on the left and the right side of the slider show a help text which is taken from the similar slider for maps. This text (in the DEM case) tells something about map visibility what isn't true and thus misleading.

**Describe the solution you'd like**

The help text should tell something about the relation between the selected range and the use/loading of DEM data.

In this context: are the words min/max scale used correctly?

Is scale used in the sense:

scale of a map 1:25000 > scale of a map 1:100 000

max. scale, for example: 1:5000, reached with zoom in
min. scale: 1:1000000, reached with zoom out

compare with move direction of slider handle!

**Describe alternatives you've considered**

None

**Give a reason why someone else should spend time on that request**

The rules for DEM data have been changed slightly with one of the latest commits. Thus, the help text could be a possibility to inform the user about part of these rules.

**Additional context**

There could be yet another issue related to the DEM range slider and which I identified while trying to understand the (irregular?) behavior when clicking the buttons at the left and right side of the slider:

* Save the settings for maps and DEM in a view file `(`File - Store map view`)
* Open the saved file and look at the min/maxScale entries for maps and DEM.
* For maps everything looks nice.
* For DEM I found:

~~~
...
74f0fedfd36942a2259fb7e264bb89ef\minScale=70
74f0fedfd36942a2259fb7e264bb89ef\maxScale=1e+12
...
2a2507e6a0b8397920814a48573cd54d\minScale=1e+12
2a2507e6a0b8397920814a48573cd54d\maxScale=300
...
~~~

The sliders are shown in the attached snapshot.

1e+12 appears twice, once for min, once for max. Should one of them be 0?

![DEM_Range](https://user-images.githubusercontent.com/55309218/80631991-e4488580-8a56-11ea-9868-c113af5b657c.jpg)

**Comment by kiozen** [comment]
I don't really see the problem. But I am happy to accept better phrasing of the tool tips at any time.

1e+12 is the placeholder for "not a number". In config this means the limit has not been set. But config is completely transparent to the user and of no user level concern.

**Comment by wthaem** [comment]
Just a bit more detailed:

The messages shown on the **DEM** slider found in IDemPropSetup.ui are:

~~~
Click to use current scale as minimum scale to display the map.

Click to use current scale as maximum scale to display the map.

Control the range of scale the map is displayed. Use the two buttons left 
and right to define the actual scale as either minimum or maximum scale.
~~~

All of these messages are about "display of map". But the display of maps is not changed or controlled when working with the slider. Thus, the message texts are wrong.

I can't propose a better formulation because my understanding of the work of this slider in the case of one activated DEM file and in the case of more than one activated DEM file is not good enough, even following the discussion in the last time about loading DEM data (example for my difficulties: one activated DEM file, slider handle somewhere in the middle of the slider, a click on the left button has same result (green interval) as a click on the right button).

**Comment by kiozen** [comment]
Well it's the display of the DEM map which consists out of hillshading, slope coloring, etc. We might use `DEM overlay` but I doubt that makes it better.

The discussion of last time might have been lengthy, but didn't really change anything significant :) It's still the same:

* All DEM maps/overlays are drawn as configured by the scale. If the slider is in the green range it is drawn. If it's outside the green range it's skipped. If no limits are set it's always drawn.
* If a component within QMapShack needs an elevation the list of DEM files is parsed topmost first to provide a valid elevation for the given coordinate. The DEM file that's providing an elevation first wins. Regardless of what limits for the scale are set.

That is the behavior since ages.

The new behavior is for the elevation under the mouse cursor. This has been retrieved the same way as any other elevation value so far. Now it also obeys the scale range if any applies. For example if the first DEM in the list would contain the coordinate but it's out of scale, the algorithm iterates to the next one until it finds a DEM with matching scale range and containing the coordinate.

This helps to speed up mouse movement when using online DEM at  more detailed scales and some offline DEM for the less detailed scales. So no big change barely noticeable by the user.

**Comment by wthaem** [comment]
Thanks for the explanation. Nevertheless, from my side some more comments and more importantly, a proposal for reformulating the message texts (the comments should make clear why the changes in the texts are made).

The word "scale" used in the current message texts is ambiguous:

* Normal use: it describes a ratio, e.g. 1:25000
* Other use: it means the bar scale on a map as shown in the lower right corner of a map view in QMS (most likely the meaning used in the discussed texts).

Comparing "normal scales" is obvious.

Comparing "bar scales" makes sense only under some additional assumption. As an example: Assume the length of the bar on the map is the same, say 5cm, for all zoom levels, then use the length on the map belonging to these 5cm at different zoom levels, say 100m, 1km, ... as "scale" and compare these values.

"Smaller" and "bigger" and thus "minimum" and "maximum" for these 2 scale interpretations go into the opposite direction.

Here is a proposal to avoid trouble resulting from this ambiguity:

**For maps:**

*Right button:*

~~~
Click to use the current zoom as maximum zoom-out to display the map.
~~~

*Left button:*

~~~
Click to use the current zoom as maximum zoom-in to display the map.
~~~

*Handle:*

~~~
Control the zoom range for which the map is displayed. Use the two buttons left 
and right to define the actual zoom as either maximum zoom-in or zoom-out.
~~~

**For DEM:**

*Right button:*

~~~
Click to use the current zoom as maximum zoom-out for use of the DEM data.
~~~

*Left button:*

~~~
Click to use the current zoom as maximum zoom-in for use of the DEM data.
~~~

*Handle:*

~~~
Control the zoom range for which the DEM data is used. Use the two buttons left 
and right to define the actual zoom as either maximum zoom-in or zoom-out.
~~~

I think, for the normal user it is not obvious that the DEM data can be interpreted (or is interpreted internally in QMS) as a map . Therefore, I would avoid the word "map" in connection with DEM.

**Comment by kiozen** [comment]
Please check PR and give feedback.

**Comment by mitxel-m** [comment]
@wthaemelt sorry for being missing last week,
I missed this is issue
I started writting something for the wiki at 
DocControlMapDem
Last week I've been too busy to move forward.

I will write you with my notes, or better with the .md text for the wiki, I think I can get it done today
;-)

**Comment by wthaem** [comment]
@mitxel-m: Please have first a look at latest changes in AdvMapDetails. There I tried to summarize this discussion!
