### ISSUE TITLE
Improvements for Search of Workspace and Projects

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#176]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Feature**
**requests that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

There have been some whishes to improve the Search.

**Describe the solution you'd like**

Tell me what you would like!

I'll collect it here:

1. 

**Describe alternatives you've considered**

Any alternatives you suggested:

1. 

**Give a reason why someone else should spend time on that request**

There have been some ideas that would improve the functionality and also may save time for users. I will code the suggestions I find feasible, when I have time and motivation to do so.

**Additional context**

See also: https://www.naviboard.de/thread/64710-filter-anstieg/

**Comment by kiozen** [comment]
I don't want to have such a half cooked issue open for long. I'll close it for now. If there is some feedback that condenses into something we are committing to do it can be opened again.
