### ISSUE TITLE
Access to OSM tiles stopped working - User Agent to be fixed

### ISSUE THREAD

**Issue by meinhardh** [Maproom/qmapshack#177]
QMS offers to install default access to tile servers, including OSM via the file OpenStreetMap.tms.
This file does not seem to have changed recently (my version is definitely not newer than June 2018). Yet recently (since a few weeks) no OSM tiles are loaded when the OSM online maps are activated. Running with debug flag shows that the OSM tile server replies with Error 429: Too Many Requests.

Googling for the problem shows a number of posts that report that OSM has become more serious about enforcing the tile usage policies. They now seem to block the user agent 'Agent Smith' that
the OpenStreetMap.tms file sends.

In fact, replacing that string with the program name, version number, platform and my e-mail address has unblocked the situation; tiles are now loaded correctly again.

While my problem is solved (at least for the time being!), it may well be worth changing the default .tms file that QMS installs, or at least pointing out in the documentation that this string needs to be changed.

In general, HUGE kudos to all those who help maintaining and developing QMS and OSM!

**Comment by kiozen** [comment]
Already fixed:
https://github.com/Maproom/qmapshack/pull/169
