### ISSUE TITLE
Mistake in german translation

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#18]
**Describe the bug**
In the search help window following is written:
> 'Datum gleich' findet alles, was innerhalb von 24 Stunden des aktuellen Tages liegt.

It should be "innerhalb des angegebenen Tages". 

**To Reproduce**
1. Open Help Window for the workspace search
2. Scroll down to (see above)

**Comment by sikmir** [comment]
@kiozen By the way, what about enabling some web-based localization tool for qmapshack (e.g. [Weblate](https://hosted.weblate.org/))? That would help to translators a lot.

**Comment by wthaem** [comment]
Wrong translation is due to wrong English text in code:

<source>&apos;Date equals&apos; matches everything that is within 24h of the current day.</source>

The English text should be changed to something like "matches everything within the given day" (not "current" - that's different!)

**Comment by pingurus** [comment]
Sorry, my fault!

**Comment by kiozen** [comment]
@pingurus can you fix code and German translation? 

For all: reviewing that part one more time doesn't hurt.

**Comment by kiozen** [comment]
And keep in mind that things are a bit more complicated now:

https://github.com/Maproom/qmapshack/wiki/DeveloperCommitCode
