### ISSUE TITLE
Importing images based on EXIF data

### ISSUE THREAD

**Issue by baem2** [Maproom/qmapshack#182]
Disclaimer: I am sorry if this has been answered somewhere already – I tried my best to find answers to my questions in the wiki/FAQ, but failed ...

I was using qlandkartegt so far. On its home page I am told qmapshack more or less is the successor (well, and debian's current stable does no longer have qlandkarte in its archives).

In qlandkartegt it was quite easy to load images, and automatically put them "on map", i.e. the GPS data was read out of their EXIF and small images where added there. I tried to do the same in qmapshack, but I did not find similar options.

Did I overlook it? If not: Is it planned to introduce that feature?

**Comment by kiozen** [comment]
No. No.

https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
