### ISSUE TITLE
Backward range selection causing small issues

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#183]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

- [x] Did you choose a good title?

**Describe the bug**

If I select the range in the edit track window starting from the end, the distance of the selected range is negative. That is not really false, but still not optimal, since the user does not see a direction in the range he selected. What is more annoying is that the distance is not converted.

**What have you done to circle down the problem?**

I have not checked why exactly it happens, but I assume that the unit conversion handles negative values as the minimal unit. When changing to imperial for example, the distance is given in feet instead of miles. I think that it would be more useful to fix the distance in the range selection to positive aswell. The recent changes to the range selection did not fix this.

**To Reproduce**

1. Open edit window of track
2. Select a range starting from the end
3. See error

**Expected behavior**

A positive distance with correct units.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/36167579/82113730-830ffa00-9758-11ea-9c77-4e4ec780a6e8.png)

**Attachments**

use any track

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: Windows 8.1 / Ubuntu 19.04
 - QMapShack Version 1.14.1 / current dev

**Additional context**

**Comment by kiozen** [comment]
oooops :) I'll fix it

**Comment by kiozen** [comment]
please test and review PR
