### ISSUE TITLE
RoutinoDatabaseBuilder - allow user defined tagging control files.

### ISSUE THREAD

**Issue by jmfloyd** [Maproom/qmapshack#187]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Feature**
**requests that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[ ] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

qms relies on tagging defined at system level (not user edit.  The Routino planetsplitter program allows the <prefix>-tagging.xml.

**Describe the solution you'd like**

By **not** defining the tagging arg in the commandline, the program will use the dir and prefix arguments to create the tagging file name (/routinopath/prefix-tagging.xml).  If that doesnt exist it uses the default routino folder for tagging.xml.  This is a better approach - qmapshack does not need to know the default routino folder location and provides a seamless way a user can define a specific  tagging control file.  It uses features of the original planetsplitter program which is used directly by qms for the database build.

**Describe alternatives you've considered**
None

**Give a reason why someone else should spend time on that request**
Originally thought this required some coding, but it only requires to delete 2 lines where the tagging arg is defined in the qmapshack/src/qmapshack/tool/CRoutinoDatabaseBuilder.cpp.

Keep in mind that you ask others to spend their spare time for your request. Convince them
by giving a reason why solving your request has a benefit for them, too. Good reasons are
if you are able to prove

* The request solves a fundamental problem for everyone
* The request is of general interest for many users

Bad reasons are:
* Because software xyz does it
* Because you just want it to have that way
* Because it will solve a very particular problem.

**Additional context**

I have tried it and it works as expected.  Note I used to create my own database builds outside of qms in order to fix some issues common to Australia driving.  I could otherwise have to edit a tagging.xml  as root to be able to run it from qms (not a good approach).

**Comment by kiozen** [comment]
No one picked up the ticket. I close it for now.
