### ISSUE TITLE
Docs:DeveloperCommitCode - cleanup forking/cloning section

### ISSUE THREAD

**Issue by jmfloyd** [Maproom/qmapshack#188]
In the section "Configure Git to sync your fork with the original QMapShack repository" there is some confusion.  The first 5 or 6 points repeat (or negate) the previous section "Create a local clone of your fork".  The previous section is good, latter section actually misses the forking part.

It just requires some cleaning up. It will be a lot less confusing especially for new comers who are less familiar with git.
Cheers

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
