### ISSUE TITLE
Error on gpx saved

### ISSUE THREAD

**Issue by fabiobike** [Maproom/qmapshack#19]
I use QmapShack 1.13.2 on Win 10Pro to create a gpx merging different tracks.
I added some  waypoints
I "save as "PizBoe_Trail.gpx".
I imported it to Oruxmaps 7.4.22 on my android samsung A3 2017 phone but failed.
The error is "Error opening the track"
I try to open the track with another software , Compegpsland 8.5, i save the tracks as "PizBoe_Trail_Land.gpx" and this one is accepted on Oruxmaps...
in the past I used the same procedure and never had any problems.. it'a  1.13.2 problem?

I attach both files

Thanks a lot!

[gpx.zip](https://github.com/Maproom/qmapshack/files/3635186/gpx.zip)

edit: I did other tests, I understand that the problem is the waypoints ...
creating a track without waypoints it' all ok

**Comment by sikmir** [comment]
Unexpected ':':
```xml
    <extensions>
     <ql:flags>0</ql:flags>
     <ql:activity>0</ql:activity>
     <::ql:terrainslope>10.838959971362641</::ql:terrainslope>
    </extensions>
```

**Comment by kiozen** [comment]
@fabiobike can you please investigate a bit further. Are waypoints generally a problem? Or just a special one e.g. `<name>Rifugio Boè 2873</name>`. Can you try with a single waypoint and strip down the data line by line to find out what line causes the problem.

**Comment by beedaddy** [comment]
I think @sikmir is right. @fabiobike, did you calculate the terrain slope in QMS? If you did, the exported gpx file has entries like `<::ql:terrainslope>10.838959971362641</::ql:terrainslope>`. And some software (tested it with GPXSee) has problems with that. I'm not very experienced with the gpx or xml format. But I wonder if the leading colons are permitted. Aren't colons only allowed to seperate the namespace prefix from the local part, @kiozen ?

**Comment by kiozen** [comment]
as @fabiobike states that the waypoints make a difference I expect a problem in the waypoint structure. 

Leading `::` simply denotes _global namespace_. That might be a problem, too. I will change this when fixing this bug. But I want to know the root cause for the issue before I start to invest time.

**Comment by sikmir** [comment]
> Leading :: simply denotes global namespace. That might be a problem, too.

But XML validation fails:
```sh
$ xmllint -schema <(curl -s http://www.topografix.com/GPX/1/1/gpx.xsd) PizBoe_Trail.gpx --noout
...
PizBoe_Trail.gpx:8695: element ::ql:terrainslope: Schemas validity error : Element '{http://www.topografix.com/GPX/1/1}::ql:terrainslope': This element is not expected.
PizBoe_Trail.gpx fails to validate
```

**Comment by fabiobike** [comment]
I I tried to repeat the procedure done:
- I made three tracks
- I joined them
- I put waypoints (even with accented letters, I thought that was the problem)

the error did not occur

I tried to use the function
"calculates the slope of the terrain based on the DEM data"
and the error occurred !!!

I think the problem is in this function.

**Comment by kiozen** [comment]
Ok, so it's not dependent on waypoints. But on the `::ql:` as @sikmir noted.

Can you please use a text editor and replace all occurrences of `::ql:` with just `ql:`. If that works we know for sure.

**Comment by fabiobike** [comment]
@kiozen 
> Can you please use a text editor and replace all occurrences of `::ql:` with just `ql:`. If that works we know for sure.

it works perfectly !

**Comment by kiozen** [comment]
:+1:  I will fix it.

**Comment by fabiobike** [comment]
Thanks a lot!

**Comment by kiozen** [comment]
@fabiobike are you able to compile and test?

https://github.com/Maproom/qmapshack/pull/40
