### ISSUE TITLE
Openstreetmap view no longer works

### ISSUE THREAD

**Issue by RobOo-Github** [Maproom/qmapshack#194]
QMapShack 1.14.1-1 (Debian).
Everything works. Live maps (Opencyclemap, Worldsat, etc), all work as always.
But since recently, OpenStreetMap does not. When I move the zoom level, or shift to a different location on the map, a window on the top left, It shows "Openstreetmap, x tiles pending", and the counter counts down to zero, more quickly than usual. But no maps show. Just a single coloured background canvas.  

Deleting all profile-settings (starting from scratch) gives the same result. 

Starting QMapShack from the command prompt shows no error messages:
xxx@debian:~$ qmapshack 
2020-05-27 10:20:36.124 [warning] "no file found for translations '/usr/share/qmapshack/translations/qmapshack_en' (using default)."
2020-05-27 10:20:36.301 [warning] Empty filename passed to function
2020-05-27 10:20:36.308 [warning] Empty filename passed to function

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

https://github.com/Maproom/qmapshack/pull/169
