### ISSUE TITLE
Some TS language files broken

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#195]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x ] Did you choose a good title?

**Describe the bug**

The qmapshack_*.ts language files for languages es, ca, cs, ru updated in the last commit are somehow broken.

**What have you done to circle down the problem?**

* Open the files in Qt linguist to see an error message ("Mehrfach vorhandene Meldungen").
* The errors are related to ccanvas.cpp.
* For the Russian file earlier tranlsations disappeared (not agreat problem, backup exists).
* The now wrong and already deleted prefix `markdown-header-` in Wiki links did re-appear.

**To Reproduce**

Open files in Qt linguist

**Expected behavior**

No duplicates of messages in the language file

**Screenshots**

none

**Attachments**

none

**Tracebacks**

none

**Additional context**

log of my last `git pull`:

~~~
Updating 8c5710e1..af850d95
Fast-forward
 changelog.txt                        |  1 +
 msvc_64/3rdparty.txt                 |  2 +-
 msvc_64/QMapShack_Installer.nsi      |  2 +-
 qmapshack.1                          |  2 +-
 qmaptool.1                           |  2 +-
 qmt_map2jnx.1                        |  2 +-
 qmt_rgb2pct.1                        |  2 +-
 src/qmapshack/locale/qmapshack_ca.ts | 12 ++++++------
 src/qmapshack/locale/qmapshack_cs.ts |  8 ++++----
 src/qmapshack/locale/qmapshack_de.ts | 16 ++--------------
 src/qmapshack/locale/qmapshack_es.ts | 12 ++++++------
 src/qmapshack/locale/qmapshack_ru.ts | 12 ++++++------
 12 files changed, 31 insertions(+), 42 deletions(-)
~~~

**Comment by kiozen** [comment]
This warning doesn't seem to be critical. I recommend to crosscheck if the correct translation is selected for the mentioned section. So far it does. If you save the file everything is fine again.
