### ISSUE TITLE
Continuation of the construction of the route after the undo of the last action

### ISSUE THREAD

**Issue by aerin** [Maproom/qmapshack#196]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Describe the bug**

I start to create a route and everything goes OK until I click “Undo last change”. After that I can’t add a new point, the right-click context menu is also not showed. I can switch the mode Ctrl+M,CTRl++, but a new point is not added to the route.

**What have you done to circle down the problem?**

1.14.1

**To Reproduce**

1. Right click and select "Add new route"
2. Click sometimes to add new route points
3. Click "Undo last action" or Delete point
4. See error: a click on the map does not add a new point and the context menu on the right button does not work either

**Expected behavior**

Сontinued route building

**Screenshots**

**Attachments**

**Tracebacks**

**Desktop (please complete the following information):**

Windows 8.1 Professional
QMapShark 1.14.1
QT 5.12.3
GDAL GDAL 2.4.2 
Proj4 620
Routino 3.3.2+svn(API version 8)

**Additional context**

**Comment by kiozen** [comment]
I do not see a bug. You are probably just confused. If you undo steps the software can't predict your future steps you want to do. There are two endpoints, multiple intermediate points, 4 functions to apply. Therefore you have to choose a function or keep the current one and select a point by moving the cursor close to it until it is highlighted. 

The details are explained here:
https://github.com/Maproom/qmapshack/wiki/DocGisItemsEditMultiple

**Comment by aerin** [comment]
O! I saw a lot of routing programs, but I see such a non-trivial interface for the first time;) Usually, if I have selected the mode of adding points, it is logical that the segment is drawn to it from the last point. And here you need to carry the mouse until the point turns red, click and only after that drag it to the right place. I can’t say that it’s not right, but it’s very unusual! Thanks for the explanation.

**Comment by kiozen** [comment]
Well no one forces you to use QMapShack. If other software fits your needs better I strongly encourage you to use that software instead of QMapShack.
