### ISSUE TITLE
Timestamp of track points are lost when track is edited

### ISSUE THREAD

**Issue by Steggen** [Maproom/qmapshack#199]
When a track is edited (track points points added or deleted, moved, track splitted...) the timestamp and height information are lost. This was not the case in QLandKarteGT. 
 
QMapShack 1.13.2
Proj4 5.20
Linux Mint 19,3

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
https://github.com/Maproom/qmapshack/wiki/DocFaqHandling#how-to-edit-tracks-without-losing-track-data
