### ISSUE TITLE
Elevation imprecise when exporting as GPX

### ISSUE THREAD

**Issue by robhubi** [Maproom/qmapshack#200]
**Choose a good title**
[ x] Did you choose a good title?

**Describe the bug**
Every technician's heart bleeds when measured values are lost during processing. The output of the height without decimal point at "Save as GPX w/o ext..." is such a case. Barometric sensors for altitude determination resolve in the cm range (see also https://www.openstreetmap.org/user/Robhubi/diary/393234 ) Rounding off to whole meters is a significant loss.

**What have you done to circle down the problem?**
Comparison of input and output. A google search gave no result

**To Reproduce**

1.	Load GIS data “QMStest01in.gpx” (see attachment)
2.	Save as GPX w/o ext… with name “QMStest01out.gpx”
3.	Compare "ele" in these files: for example 363.63 --> 364

**Expected behavior**
Keep at least 2 decimal places

**Screenshots**
none

**Attachments**
QMStest01in.gpx
QMStest01out.gpx

**Tracebacks**
none

**Desktop (please complete the following information):**
 - OS: Win 10 pro 64 bit
 - QMapShack Version 1.14.0

**Additional context**
none
[QMStest01in.gpx.txt](https://github.com/Maproom/qmapshack/files/4738255/QMStest01in.gpx.txt)
[QMStest01out.gpx.txt](https://github.com/Maproom/qmapshack/files/4738256/QMStest01out.gpx.txt)

**Comment by kiozen** [comment]
This is a request that pops up occasionally. So far no one was willing to spend time on it. It's quite some work with many changes in the code. So there has to be a real gain to do it. And if you put that into account everyone gave up as it is not worth the time spent.

Your experiments are totally valid and barometric sensors have a very good accuracy. I experienced that on my own while keeping drones on elevation with a barometric sensor years ago. However the output of a consumer grade device is far from centimeter precision. Even far from meter precision. For users it's totally unimportant if they are at 1245,34 m or 1245 m. They are interested in ascent and descent. And for those values anyway you have to use a different approach than simply summing up the deltas.

I leave this request open for the next half a year. Maybe someone else see enough potential in that topic to spent the time. And I promise I will take it into account if I ever find the time to finish the binary format V2 ticket and make the elevation values a float. This won't change anything for the rest but at least will not block a future change.

**Comment by robhubi** [comment]
Thanks for the awareness. If it had been just a change of a number ... but this effort is not worth it for something that 99% of QMS users would not even notice.

The accuracy of the height gain is another interesting topic, but it fits better into the forum.

**Comment by kiozen** [comment]
No one picked up the topic. I will close it for now.
