### ISSUE TITLE
Introduce possibility to duplicate Tracks, Waypoints etc.

### ISSUE THREAD

**Issue by BenediktO** [Maproom/qmapshack#203]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Feature**
**requests that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

I often want to duplicate Tracks, for example to later cut them and join to a larger Track. To accomplish that I have to send the Track to the original directory and then rename it.

**Describe the solution you'd like**

It would be great if in the drop-down menu when right-clicking an element, an option "Duplicate element" or similar would be available

**Describe alternatives you've considered**

The above described solution is possible, but not optimal

**Give a reason why someone else should spend time on that request**

The above use-case is in my opinion relevant for many users.

**Additional context**

**Comment by kiozen** [comment]
I do not really see the advantage. 

1. If you want to join tracks you just have to select the tracks and join them. There is no need to copy or clone (duplicate) them.

2. If you want to use parts of a track there are several better methods than cloning the track and butchering it. 

a. You can use your tracks while drawing a new one. The track drawing tool has an option to follow loaded tracks. Just press the `T` button. see https://github.com/Maproom/qmapshack/wiki/DocGisItemsEditMultiple

b. You can use the range edit/selection tool to copy a selected range from a track. see https://github.com/Maproom/qmapshack/wiki/DocGisItemsTrkRange (this is about the new upcoming tool, but functionality is the same for the old one)

From my  point of view cloning items has a very rare use case and the current approach by copy them into the same folder is sufficient. I hardly ever use it and I do a lot of track editing.

**Comment by kiozen** [comment]
No one picked up the ticket. I close it for now.
