### ISSUE TITLE
Export Project Information to Spreadsheets

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#206]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Feature**
**requests that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

- [x] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**
Sometimes I want to know what distances and elevation gains I have ridden the last months. Yes, I can look at the folder I keep my rides in, but a graph would be nice. And since everyone probably wants their own kind of graphs I thought it would be a nice feature to be able to export quasi arbitrary data to a spreadsheet from QMS so everyone can make their own graph in the tool of their choice afterwards.

**Describe the solution you'd like**

A button next to the "print project" button to open a view where the user can enter the terms from the workspace search to define what data is in each column. QMS then assembles the data for the whole project and outputs a .csv file to the location the user selected.

**Describe alternatives you've considered**

I've played around with exporting my rides to a gpx and then importing them to GoldenCheetah but  a) that's an overkill b) I couldn't make it work.

**Give a reason why someone else should spend time on that request**

Keep in mind that you ask others to spend their spare time for your request. Convince them
by giving a reason why solving your request has a benefit for them, too. Good reasons are
if you are able to prove

* The request solves a fundamental problem for everyone
* The request is of general interest for many users

Bad reasons are:
* Because software xyz does it
* Because you just want it to have that way
* Because it will solve a very particular problem.

I think many people like to see a summary of what they have done in a year in graphs. Using the existing search terms makes it easily configurable and has the upside that if a user wants a very specific diagram, it is not using our time to make that kind of graph appear as long as the data is already available in QMS.

I might be underestimating the scope of this project, but after all it is (mostly) my free time as long as I don't bother you with way too early pull requests :wink:

**Additional context**

**Comment by kiozen** [comment]
No one picked up the ticket. I close it for now.
