### ISSUE TITLE
Incomplete index handling in F1 help

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#211]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Feature**
**requests that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

Several HTML pages may have the same keyword (the same index entry). In earlier versions of QMSHelp.qhp they could have even the same id. The latest version of QMSQtHelp.py changed this behavior. Now, there is a more logical 1-to-1 relationship between a HTML page and its id as defined in the qhp file (this can be important when trying to synchronize the displayed HTML page with the content tree). As a result of this change the QMS F1 help variant is no more in a position to display a HTML page with a keyword/index entry used also for another HTML page. Qt assistant opens in this situation a selection window where the user can choose the topic to display.

**Describe the solution you'd like**

The class CHelpBrowser connects the linkActivated signal to a slot for index handling. This signal is not emitted, if several URL's belong to the given keyword (as an example use the keyword/index entry "Configuration, Routino"). Instead the similar signal link**s**Activated is emitted but not yet handled in QMS. 

Proposal: add an event handler for the signal linksActivated. This handler gets as one parameter a dictionary (Python language!) of document titles and their URL's. The easiest (and used up-to-now) case would be to use one (arbitrary) entry of this dictionary and display the URL. A more complete case would be the one used in assistant: open a window displaying all URL's, let the user select one of them and display the selected URL.

**Describe alternatives you've considered**

None

**Give a reason why someone else should spend time on that request**

A user would be surprised to click an index entry without a reasonable result.

**Additional context**

Compare the source code for assistant at

https://code.qt.io/cgit/qt/qttools.git/tree/src/assistant/assistant

Of interest are: "open" method in indexWindow.cpp and topicchooser.cpp.

Attention! This is Qt5.15 code! The method documentsForKeyword replaces the obsolete method linksForKeyword!

**Comment by wthaem** [comment]
@kiozen: 
@huirad: A few annoying comments about the use of different Qt5 versions in the help browser:

* When using (Py)Qt5.15.0 the F1 index part fails to work in QMS and also in the Python browser version I sent to kiozen with an email. It is working with (Py)Qt5.14.0 (in QMS with the exception of the not yet handled linksActivated signal).
* Reading Qt5.15.0 docus one could expect that the obsolete signals link(s)Activated still can be used. That fails in the current form of QMS F1 help code and of my Python script. Maybe, the code for index handling in both cases isn't sophisticated enough. I tried to use the new documentActivated signal, but did not yet have success.

Thus, there is at least one point of trouble when switching to Qt5.15.

I'll try to find a working version of my Python browser with PyQt5.15.0.

**Comment by wthaem** [comment]
### Context-sensitive help test summary

*There are remarkable changes between Qt5 versions that are related to the QtHelp index handling. The TOC and search parts of QtHelp seem to be not concerned. The following methods are are trouble spots:*

* QtHelp.QHelpIndexWidget.documentActivated  # introduced with Qt5.15 in preparation for upcoming Qt6
* QtHelp.QHelpEngine.documentsForKeyword     # introduced with Qt5.15
* QtHelp.QHelpIndexWidget.linkActivated      # obsolete with Qt5.15 - may disappear
* QtHelp.QHelpEngine.linksForKeyword         # obsolete with Qt5.15 - may disappear
* QtHelp.QHelpEngine.usesFilterEngine        # introduced with Qt5.13

Tests were done with a more or less complete QtHelp browser built with PyQt5 using the following versions:

~~~
Windows10: version 2004, build 19041.450

Python:
sys.version_info:           sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
sys.version:                3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
sys.api_version:            1013

PyQt5:
QtCore.PYQT_VERSION_STR:    5.15.0
QtCore.QT_VERSION_STR:      5.15.0
QtCore.PYQT_VERSION:        331520
QtCore.PYQT_CONFIGURATION:  {'sip_flags': '-n PyQt5.sip -t Qt_5_15_0 -t WS_WIN'}
~~~

**The code was tested only with PyQt5.15.0. An attempt was made to ensure that the code works with earlier Qt versions, too. But it couldn't be tested because re-installation of earlier PyQt5 versions failed.**

It is not known, if there have been any changes in the structure of the QHC help files caused by different Qt versions. The QHC files used for testing were created with Qt5.15.

Due to the fact that QMS is run on a wide range of operating systems using very different Qt versions (between 5.8 and 5.15 (to be expected for QMS Windows version)) it is almost impossible to test all these versions. Currently, QMS requires only Qt version >= 5.8. 

**Test results:**

* There is no need to work with link/documentForKeyword. links/documentsForKeyword give the necessary data.
* linksForKeyword returns a QMap structure which is mapped to a dict by PyQt5. This mapping is not a 1-to-1 relationship Mapping a QMap to a dict may lead to a loss of data (Use QMS help index entry "Map, TMS" to see this). Therefore, the Python code is more complicated than a similar C++ code because precautions must be taken to avoid a loss of data.
* The newer documentsForKeyword methods doesn't use QMap anymore. It results in a list which is mapped to a Python list without data loss.
* The document(s)... method need an activation by a call to helpEngine.setUsesFilterEngine(True). Without this call the document(s)...   method don't give the expected results. There is a small C++ program found in the Internet where this can be tested.
* The link/documentActivated signals are not used in the index handling. Instead the signal "activated" which is available in all Qt5 versions was used (Qt5 documentation: This signal is emitted when the item specified by index is activated by the user. How to activate items depends on the platform; e.g., by single- or double-clicking the item, or by pressing the Return or Enter key when  the item is current.).
* The correct locations in the code of the call to setUsesFilterEngine and the connect statements for signals seem to be relevant.

**Comment by kiozen** [comment]
How should we proceed with that ticket?

Afaik there are quite some changes concerning the help engine between the recent Qt5 versions. I didn't follow all discussions in detail. Was there a feasible solution?

**Comment by wthaem** [comment]
My Proposal: Close this one. There is still the open #266 and both tickets are linked somehow. 

The whole story depends a bit on the QMS strategy for using Qt. If it is to be expected that Qt5.15 or even newer Qt releases will be used in QMS in the future, then the existing QMS help code certainly needs some update. And it depends also on the strategy for using the offline help. 

There is quite a radical way to solve any help issues under discussion: instead of using QMS's own help browser (and I enjoyed kiozen's idea to have this browser!) connect the F1 call in QMS to Qt assistant. Implementation should be easy. Access to Qt assistant under Linux shouldn't be a problem because it is installed together with the Qt binaries. huirad added Qt assistant already to the latest Windows installation routine. No idea what happens with other OS.

Without the radical way:

If you look in #266 and search for "HelpBrowser_final.zip" (date 2020-12-07) you'll find my Python version of a help browser with code for the discussed cache handling. My hope is, that someone knowing C++ better than I do can translate this cache part (or a better one) into the QMS help code. My opinion: this should be done because the current solution used with the Windows installation isn't, mildly said, the best one.

The second issue is the use of methods declared as obsolete. Most likely, the current situation with QMS and Qt is such, that the obsolete methods can not yet be dropped. Somewhere relatively old Qt versions seem to be still in use that don't provide the new methods. In the Python code an attempt is made to use both methods while preferring the new ones. This issue concerns the index handling part of the discussion. 

The index part consists of 2 separate issues:
* use of obsolete methods,
* extra selection window/widget in case that several pages are linked to one index entry.

The implementation of the second issue seems to be easier with the newer methods.

My opinion: the selection widget is a "nice to have". Whether to implement the new methods depends on the QMS plans for the future. I think sooner or later they will be needed.
