### ISSUE TITLE
OSM_Topo.tms needs correction of URL

### ISSUE THREAD

**Issue by pmjherman** [Maproom/qmapshack#213]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[y ] Did you choose a good title?

**Describe the bug**

After correcting the User Agent in OSM_Topo.tms the use of this map still did not work. I found out that the URL of these tiles was outdated.
The following should be placed on line 7 of this file:

  <ServerUrl>https://a.tile.opentopomap.org/%1/%2/%3.png</ServerUrl>

Note that instead of a.tile.... also b or c can be used

**What have you done to circle down the problem?**

I have tried many versions of the file and this one works

**To Reproduce**

Change this in the file and it will work.
Sorry, I could have made a pull request, but cloning everything for this little correction was cumbersome

**Expected behavior**

I think with this correction everything is fine

**Screenshots**

N/A
**Attachments**

I have attached a working version of the file

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: [e.g. OS X, Debian, Suse, Windows]
 - QMapShack Version [e.g. 1.13.1]
 - Window Manager [e.g. KDE, GNOME]

**Additional context**

[OSM_Topo.tms.zip](https://github.com/Maproom/qmapshack/files/4776643/OSM_Topo.tms.zip)

**Comment by kiozen** [comment]
Strange `https://opentopomap.org/%1/%2/%3.png` is still working for me.

**Comment by pmjherman** [comment]
Yes, strange. Maybe some leftover cache or a proxy setting? In any case, with me I got nothing of OSMTopo untill I changed the server address, and now it works as a charm. I copied the address from the 'About' page of opentopomap.org, so I think this is the official one.

**Comment by kiozen** [comment]
Probably a left over in the cache. I guess there where still tiles with the old URL that failed due to the bad User-Agent. The cache kept these failed tiles as empty tiles. With the new URL another cache is built. That's why you see results. And you will see results with the old URL if you choose a non-cached area or the tiles expire from the cache.

**Comment by pmjherman** [comment]
Just tried it with a new directory for maps. You are right, the old URL does work once the Agent is changed. Sorry for my misinterpretation - things are always more complicated than you think.

**Comment by kiozen** [comment]
Just fine if it work :+1:
