### ISSUE TITLE
Fatal error while compiling V1.15

### ISSUE THREAD

**Issue by Berylux** [Maproom/qmapshack#214]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[ ] Did you choose a good title?

**Describe the bug**

Compiling QMapShack 1.15 on my Kubuntu 18.04.4 stops with error:

/home/beryl/Bin/gps/QMapShack/src/qmt_map2jnx/main.cpp: In function ‘int main(int, char**)’:
/home/beryl/Bin/gps/QMapShack/src/qmt_map2jnx/main.cpp:698:28: error: invalid conversion from ‘const char**’ to ‘char**’ [-fpermissive]
         oSRS.importFromWkt(&wkt);
                                             ^~~~

**What have you done to circle down the problem?**

Did you compare to previous versions? What versions? Did you check
if others have the same problem?
Compiling previous versions are usually run fine on my system (actually V1.14.1)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Attachments**

Can you provide an example file to trigger the problem?

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: Kubuntu 18.04.4
 - QMapShack Version 1.15 from github
 - Window Manager KDE

**Additional context**

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
