### ISSUE TITLE
Nautical miles for distances and feet for altitudes

### ISSUE THREAD

**Issue by think-nice-things** [Maproom/qmapshack#22]
Hi,

for flight planning is common to have nautical miles for distances and feet for altitudes / heights.
Unfortunately, qmapshack apparently does either allow to have nautical miles (nm) for horizontal distances (but then altitudes are also in nautical miles) or it allows to have statute miles (mi) for horizontal distances together with feet for altitudes.

I'd like to be able to have nautical miles for horizontal distances and feet for altitudes.

**Comment by think-nice-things** [comment]
Hi,

as it was a bit silent on this issue I implemented it myself ;-)

Attached is a diff. This adds the check button "Aviation (nm, feet)" to units which sets nautical miles and knots for horizontal distances / speed and feet for vertical distances.

[qmapshack.aviation.diff.txt](https://github.com/Maproom/qmapshack/files/3719390/qmapshack.aviation.diff.txt)

I'd be glad if it would find it's way into the official sources.

**Comment by kiozen** [comment]
Hi,

thanks for helping! That's very much appreciated. To keep better track of who contributed what code I would like to ask you to use a pull request. Have a look at:

https://github.com/Maproom/qmapshack/wiki/DeveloperCommitCode

**Comment by think-nice-things** [comment]
Hi // I followed the documentation https://github.com/Maproom/qmapshack/wiki/DeveloperCommitCode and created a branch QMS-22.

I didn't find out how to create a pull request though. Any hints?

**Comment by kiozen** [comment]
* Go to https://github.com/Maproom/qmapshack/pulls
* Press `New Pull Request`
* Press link `compare across forks`
* Base repository is `Maproom/qmapshack` and `dev`
* Head repository is your repository and your branch `QMS-22`
