### ISSUE TITLE
Feature request: Plugin API

### ISSUE THREAD

**Issue by gerion0** [Maproom/qmapshack#221]
*Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Feature**
**requests that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

Some time ago a planned a tour for longer bike trip, and wanted to know all camping sites along the route. This is codable with the Overpass API and/or Python in a straight forward way. However, I was obviously bound to exporting the data from qmapshack as gpx, parse that again and then work with it and reimporting it later on, while I would like to remain in qmapshack.

**Describe the solution you'd like**

I want to achieve the above steps directly within qmapshack. In my opinion the simplest thing for that is a plugin API.

**Describe alternatives you've considered**

The above described way is already an alternative: Write a lot of small scripts in Python etc. and do everything with GPX Im-/Export.

The other way would be to directly edit the source code of qmapshack and maintain a fork for this specific problem or bring it upstream. Nevertheless, writing C++ is hard for such a small thing.

**Give a reason why someone else should spend time on that request**

- Maybe you like the idea.
- A lot of programs get really nice extensions that have a Plugin API (Firefox/Blender/Gajim/...).
- It could lead to more developers that are willing to work within qmapshack.
- It could have some synergy effects, when people would begin to share their code.
- It is a generic solution that enables the solving a lot of very specific problems.

**Additional context**

Typically plugins are in a script language like Lua or Python. Especially for GIS programs also a direct connection to the Overpass API would be nice.

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

**Comment by gerion0** [comment]
> https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

Fair point, I have edited my post.

**Comment by pingurus** [comment]
I like the idea, but I think that it needs a good concept. 

The easiest way would probably be to automatically create python wrappers around the non-UI gis classes (i.e. with SWIG). Even though you still would not be able to work all the time inside qmapshack, you could easily access and edit your data without having to import/export it. (At least this is what I think after looking up stuff for 30mins, as I did not create wrappers before)

On a side note: If implemented, this might also cover #206

**Comment by kiozen** [comment]
As there is no real progress on the topic I close it for now.
