### ISSUE TITLE
Support for Garmin Fenix 6 series

### ISSUE THREAD

**Issue by stefangweichinger** [Maproom/qmapshack#222]
I open this issue as I found the closed issue #57 around the fenix5.

I assume that the underlying issue might be with `libmtp` where I also filed an issue around the ID:

https://github.com/libmtp/libmtp/issues/45

Currently the watch can be mounted with GNOME Nautilus, but there seems to be one directory level too much:
I see a device called `091e 4cdb` in Nautilus, in there a "Folder" called "Primary" and only in there the relevant folder "GARMIN" (which qmapshack looks for to find `GarminDevice.xml`, right?).

I understand that it's not exactly an issue of qmapshack, but wanted to report and document things.
Maybe someone can point me at some workaround?

thanks

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

**Comment by stefangweichinger** [comment]
lesson understood. Will use template asap.
