### ISSUE TITLE
Can't combine tracks with QMS 1.15.0-1Debian SID package 

### ISSUE THREAD

**Issue by QMSUserdevMap** [Maproom/qmapshack#225]
Hi,

I can't combine tracks with QMS. Button named "Joindre des Traces", (I use QMS with French Language). still grey when I try to combine two or more tracks.
I join the screenshot of my "About Menu"
![Version QMS](https://user-images.githubusercontent.com/67973967/86823334-054bd900-c08d-11ea-833a-88745334b544.png)

My Debian SID is up to date
Hope I gave all necessary informations
Best Regards

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
