### ISSUE TITLE
License file not found error when installing in windows 10

### ISSUE THREAD

**Issue by persep** [Maproom/qmapshack#227]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

[x ] Did you choose a good title?

**Describe the bug**

When installing QMapShack_Win64bit_1.15.0.exe in windows 10 I get this error in the installer when installing with all components selected. I've checked in the folder that the error refers to and indeed there is no "LICENSE" file there

![Clipboard02](https://user-images.githubusercontent.com/1191676/87850584-a4749a00-c8f1-11ea-8859-c47e07c3131e.jpg)

The only way to continue the installation is to click on "Ignore" and then it installs the program without any more errors

**What have you done to circle down the problem?**
I had version 1.14.1 installed without this error

**To Reproduce**

Open the installer and install and always gives the same error

**Expected behavior**

Installation of qmapshack without errors

**Attachments**

Not need it

**Tracebacks**
It doesn't crash

**Desktop (please complete the following information):**

 - OS: Windows 10 64bit 1909
 - QMapShack Version 1.15.0

**Additional context**

**Comment by wthaem** [comment]
Can't confirm this behavior. Installed QMS 1.15.0 on Windows 10 2004 (skipping MSVC runtime installation) without any problem.

**Comment by kiozen** [comment]
@huirad can you please have a look?

**Comment by huirad** [comment]
I tried - as reported by @wthaem, I see no issue.
Even if I have an existing installation and the LICENSE file opened in a text editor while running the installer.

So I propose to do https://github.com/Maproom/qmapshack/issues/234 and see if the bug disappears also for @persep with all the latest greatest stuff then.

**Comment by kiozen** [comment]
As there is no real progress on the topic I close it for now.
