### ISSUE TITLE
Documentation enhancement suggestion: no gmap support

### ISSUE THREAD

**Issue by j-paulus** [Maproom/qmapshack#228]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Feature**
**requests that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

[X] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

I have been using BaseCamp for my map needs and recently learned about QMapShack. I am trying to set-up the system for actually trying to use it and seeing if it could match my needs. I wanted to import / use the maps installed already for BaseCamp in .gmap (directory) format. Simple import didn't work and after an hour or so reading I'm tending towards the conclusion that these are not supported by QMapShack. If this really is the case, would it be possible to add an explicit mention to the documentation / FAQ that this format is not supported?

Alternatively, adding documentation of how to use the format.

**Describe the solution you'd like**

Mention explicitly in the documentation that the format is NOT supported. Or alternatively if it is supported, outline how to use it (for impatient dummies).

**Describe alternatives you've considered**

N/A.

**Give a reason why someone else should spend time on that request**

I assume there are also other potential users who have BaseCamp or similar software installed with gmap map format. 
- Having an explicit note about the (missing) support would make the documentation more complete and reduce the frustration of potential users.
- Having support for the format would avoid installing the same map in multiple formats and reduce the threshold of switching to QMS.

**Additional context**

N/A

**Comment by wthaem** [comment]
see: [https://github.com/Maproom/qmapshack/wiki/AdvSetup#download-and-install](https://github.com/Maproom/qmapshack/wiki/AdvSetup#download-and-install)

A remark about the not supported gmap format will be added soon.
