### ISSUE TITLE
qmt_map2jnx support for GDAL overview data

### ISSUE THREAD

**Issue by cytrinox** [Maproom/qmapshack#230]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Feature**
**requests that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[X ] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

I build jnx maps from different map sources. QMapTool utilizes qmt_map2jnx for this job.
QMapTool has options to generate overview data. But it seems that these are not used
to create different scale levels for jnx.

Even if the overviews are embedded (GeoTIFF for example), the source code of qmt_map2jnx ignores
any additional TIFF data.

**Describe the solution you'd like**

If there exists overview data (embedded or *.ovr files), qmt_map2jnx should build different
scale levels for the resutling jnx.

**Describe alternatives you've considered**

Instead of implementing this in qmt_map2jnx, it could be done in QMapTool. It must
extract each overview and provide this files as additional input files to qmt_map2jnx.

**Give a reason why someone else should spend time on that request**

The benefit in using jnx files is the ability to store different scale levels for faster map rendering. This is currently not possible.
The current workflow (generating overview files in QMapTool but don't use it) leads to wrong expectations.

**Additional context**

None

**Comment by kiozen** [comment]
As future JNX support is more or less dead with Alex's death and no more JNX patches for future firmware are provided I will not invest time into that. But if anyone else want to pick up the task go ahead. I'll leave the ticket open for half a year.

**Comment by cytrinox** [comment]
@kiozen Oh, wasn't aware of this, sad news. With firmware patches you mean the patches for the Garmin device firmware?

**Comment by kiozen** [comment]
As there is no real progress on the topic I close it for now.

**Comment by erikheinz** [comment]
Hi Oliver,
friends of JNX raster maps might be interested that, although Alex Whiter passed away in 2019, R.I.P., his software is quite alive.
Version 3.80 is able to read a pattern definition file defs.txt upon startup. An updated version suitable for current devices and firmware versions is available from the Internet. Have a look for JNXdefs_2021-03-15.
Best regards,
Erik

**Comment by kiozen** [comment]
Hi Erik,

good to read. However it would be more interesting to find out the missing section in the image file format that keeps us from creating our own img files with raster maps. Also see:

https://github.com/Maproom/qmapshack/wiki/RasterImg_AWhiter
https://github.com/kiozen/GarminImg

**Comment by kiozen** [comment]
In case you wonder what part is missing: RGN5

**Comment by kiozen** [comment]
Cool! Are you basing your work on https://github.com/kiozen/GarminImg?

**Comment by kiozen** [comment]
@ddmunhoz any success? 

I noticed that the GarminImg repo needs some love to work with latest Proj library. I will take care of this the next days.

**Comment by kiozen** [comment]
It's now working with latest PROJ library. And I fixed some bugs. The repo was in a state of an intermediate commit with code silence etc.  Now the decoder and encoder work as expected.
