### ISSUE TITLE
Improve English spelling

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#231]
Improve English spelling

**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Feature**
**requests that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

Some common English terms in QMS and QMT are misspelled.

**Describe the solution you'd like**

Change the spelling of some terms, e.g. full screen ==> fullscreen, real time ==> realtime, etc.

**Describe alternatives you've considered**

None.

**Give a reason why someone else should spend time on that request**

Messages to the user look better.

**Additional context**

None

**Comment by kiozen** [comment]
@pingurus I have updated the *ts files and came across some untranslated GC search strings. As you are more in GC could you please do the translations?

**Comment by pingurus** [comment]
@kiozen Should I open a pull request that links to this issue or create a new one?

**Comment by kiozen** [comment]
Just send me the ts file
