### ISSUE TITLE
Windows: Toolchain update to MSVC2019 and Qt5.15

### ISSUE THREAD

**Issue by huirad** [Maproom/qmapshack#234]
**Windows: Toolchain update to MSVC 2019 and Qt 5.15**

[X] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

To avoid messing around with already fixed bugs in 3rd party tools and libraries, the toolchain for Windows shall be adapted to using MSVC 2019 and Qt 5.15.0.

**Describe the solution you'd like**

Adapt cmake files if necessary, adapt windows installer scripts, if necessary, adapt Wiki if necessary.

**Describe alternatives you've considered**

Alternatives are: do it or do it not. I volunteer to do it - at least trying.

**Give a reason why someone else should spend time on that request**
I live in a country where the chancellor declares certain tasks as alternativlos. 

**Additional context**

@wthaem reported that he did it locally and that it probanly would fix https://github.com/Maproom/qmapshack/issues/229

**Comment by mitxel-m** [comment]
There is one point that is not strictly related to the QMS code, but it could affect users who use gdal plugins for formats such as ECW or MrSid.

Currently these plugins are not included in the compiled version of QMS, and the user adds them voluntarily. For now the easiest way to do this that we have found, is as described in the wiki, to use the plugins already compiled by Tamas Szekeres, available on the[ GISinternals website](https://www.gisinternals.com/release.php). 

Although I'm not absolutely sure, I think this works as long as the versions of MSVC and Gdal against which the plugin was compiled are the same as the versions against which QMS was compiled.  

Unfortunately I haven't found any plugins compiled against MSVC2019 yet, I hope that GISinternals will offer them in the future, but until then it could happen that users who need to use ECW should get stuck in a QMS version compiled against MSVC2017. 

This is just a comment that can help when considering the pros and cons of moving to MSVC2019. I really appreciate the volunteer work done to offer a windows installer, and I am aware that it is not always possible to cover all needs.  ;-)

I will keep an eye on GISinternals updates, and will communicate if there are any new developments.

**Comment by huirad** [comment]
Hello @mitxel-m, as far as I understand, MSVC2015, MSVC2017 and MSVC2019 are binary compatible.
See https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019
So I do not expect any issue.

**Comment by mitxel-m** [comment]
Hi @huirad. Thanks for the link and clarification. Really good news.
Now I see that I was a bit confused at this point. 
Thanks again for your attention and your work. ;-)

**Comment by huirad** [comment]
For the V1.15.1 windows binary installer, we will stay with MSVC2017 and Qt5.12.10.
Therefore this issue is obsolete and to be replaced with https://github.com/Maproom/qmapshack/issues/264.
