### ISSUE TITLE
Save track profile window's geometry when window gets closed

### ISSUE THREAD

**Issue by JFritzle** [Maproom/qmapshack#235]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Feature**
**requests that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

[x ] Did you choose a good title? -> Yes

**Is your feature request related to a problem? Please describe.**

Currently, geometry of track profile window only gets saved when QMapShack exits while track profile window is open. It is quite uncomfortable that track profile window does not get restored to previous size when closed and reopened immediately afterwards.

**Describe the solution you'd like**

When closing and reopening track profile window, I expect window to have same size as before and not to fall back to a size saved in a previous QMapShack session or even to default size of width x height = 300 x 200 pixels.

**Describe alternatives you've considered**

To save size of track profile window, I found no alternative solution other than to exit QMapShack totally while track profile window is open and to restart QMapShack.

**Give a reason why someone else should spend time on that request**

I could imagine, that request is a nice to have feature and of general interest for many users.

**Additional context**

I have been digging in code and found:
Track profile window's geometry does not get saved at close due to the fact, that procedure "CCanvas::saveSizeTrackProfile()" indeed gets called but returns without saving, because destructor of "IPlot" object "plotTrackProfile" causes condition "plotTrackProfile.isNull()" to be true. 

I am not sure, if following proposal could be a good and general solution without side effects, but at first glance it seems to be a working solution:
As destructor of "IPlot" object "plotTrackProfile" calls "canvas->slotTriggerCompleteUpdate" before destroying itself, I inserted code line "saveSizeTrackProfile();" at begin of procedure "CCanvas::slotTriggerCompleteUpdate". Thus "plotTrackProfile.isNull()" is still false when calling "saveSizeTrackProfile()" and geometry does get saved.

**Comment by JFritzle** [comment]
What I did to test:

- downloaded development branch
- applied [changes](https://github.com/Maproom/qmapshack/commit/5afa25efae3aafc0748ac97a5232614caafafe41) #242 to src/qmapshack/canvas/CCanvas.cpp
- build QMS on Linux Ubuntu 20.04

-> Unfortunately, issue #235 still exists.

Difference between solution #242 and issue #235:

**Describe roughly what you have done:**

#242: Save the profile window size when the profile gets switched from window mode to on-screen mode.
#235: Save the profile window size when the profile gets closed by window decoration's upper right close button "×" 

**What steps have to be done to perform a simple smoke test:**

- Load a track
- Highlight the track to open the profile view
- Switch profile view to window mode
- Change size of profile window
- #242: Toggle back to on-screen mode 
#235:  Close profile window by window close button "×"
- #242: Toggle back to window mode 
#235: Double-click the track in workspace to re-open the profile view  

-> #242: I do confirm: the profile window does have the same size as before.
-> #235: I still realize: the profile window does not have the same size as before.

**Comment by kiozen** [comment]
:facepalm: ok, using the 'x'. That's a bit cumbersome as a double click on the canvas is much more convenient, but yes. 

Please test again.

**Comment by JFritzle** [comment]
Test result with latest changes:

#242 and #235: The profile window has the same size as before.

-> Issue solved. Great!
