### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by old-stroby** [Maproom/qmapshack#236]
I am using XUBUNTU 20.4 and compiled QMapShack 15.0 develop.
Starting QMS from Cmd-Line (Terminal).
Closing QMS shows some Entrys in the Terminal:
==1456==ERROR: LeakSanitizer: detected memory leaks.
Do you need more Information?
rgds  Harald

old-stroby@ThinkPad-T61:~$ qmapshack
2020-08-07 19:30:35.714 [warning] Empty filename passed to function
2020-08-07 19:31:01.392 [warning] Empty filename passed to function
2020-08-07 19:31:01.507 [warning] Empty filename passed to function

=================================================================
==1456==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x7fc18e351bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fc17f43e2f4  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x212f4)

Indirect leak of 192 byte(s) in 1 object(s) allocated from:
    #0 0x7fc18e353947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x7fc185de638b  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x232c38b)
    #2 0x7fc18588a687  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x1dd0687)
    #3 0x7fc18588aac8  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x1dd0ac8)
    #4 0x7fc185cd80f1  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x221e0f1)
    #5 0x7fc185888319  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x1dce319)
    #6 0x7fc18588ba60  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x1dd1a60)
    #7 0x7fc1842b2af2  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x7f8af2)
    #8 0x7fc1842b3d53  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x7f9d53)
    #9 0x7fc18e1dd746  (/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5+0x22746)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7fc18e353947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x7fc18662d060  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x2b73060)
    #2 0x7fc18588a67c  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x1dd067c)
    #3 0x7fc18588aac8  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x1dd0ac8)
    #4 0x7fc185cd80f1  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x221e0f1)
    #5 0x7fc185888319  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x1dce319)
    #6 0x7fc18588ba60  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x1dd1a60)
    #7 0x7fc1842b2af2  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x7f8af2)
    #8 0x7fc1842b3d53  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x7f9d53)
    #9 0x7fc18e1dd746  (/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5+0x22746)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7fc18e353947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x7fc185de8071  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x232e071)
    #2 0x7fc185de639f  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x232c39f)
    #3 0x7fc18588a687  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x1dd0687)
    #4 0x7fc18588aac8  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x1dd0ac8)
    #5 0x7fc185cd80f1  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x221e0f1)
    #6 0x7fc185888319  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x1dce319)
    #7 0x7fc18588ba60  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x1dd1a60)
    #8 0x7fc1842b2af2  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x7f8af2)
    #9 0x7fc1842b3d53  (/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5+0x7f9d53)
    #10 0x7fc18e1dd746  (/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5+0x22746)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fc18e351dc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x7fc17f43e93c  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2193c)

SUMMARY: AddressSanitizer: 664 byte(s) leaked in 5 allocation(s).
old-stroby@ThinkPad-T61:~$ 

**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[ ] Did you choose a good title?

**Describe the bug**

**What have you done to circle down the problem?**

Did you compare to previous versions? What versions? Did you check
if others have the same problem?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Attachments**

Can you provide an example file to trigger the problem?

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: [e.g. OS X, Debian, Suse, Windows]
 - QMapShack Version [e.g. 1.13.1]
 - Window Manager [e.g. KDE, GNOME]

**Additional context**

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
