### ISSUE TITLE
Set default setting for source of a track. Now fixed set to color

### ISSUE THREAD

**Issue by pdenessen** [Maproom/qmapshack#237]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Feature**
**requests that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[ ] Did you choose a good title?
I hope, else let me know so I can improve.

**Is your feature request related to a problem? Please describe.**

Every time when I create a track then I need to go the details in the style track settings where I can change the source of the source to slope. Standard this is set to color (blue) Every time when I create a new track I need to change this again. This is a cool feature BTW !!

**Describe the solution you'd like**

There are various options I think:
A: Make a new setting under settings in the menu, where you can set the default values for the style.
B: Remember the last setting and use this with new tracks.

**Describe alternatives you've considered**

**Give a reason why someone else should spend time on that request**

Keep in mind that you ask others to spend their spare time for your request. Convince them
by giving a reason why solving your request has a benefit for them, too. Good reasons are
if you are able to prove

I am a happy user and want to support by giving my feedback to further improve the tool so others can benefit from as wel. However I am not a coder.
![202008 8-11-36-09](https://user-images.githubusercontent.com/11139454/89707083-6fe18480-d96b-11ea-9bcb-2e231d073972.png)

* The request solves a fundamental problem for everyone
* The request is of general interest for many users

Bad reasons are:
* Because software xyz does it
* Because you just want it to have that way
* Because it will solve a very particular problem.

**Additional context**

Attached the screenshot with the setting which should be set to default or been memorized for new tracks.

**Comment by kiozen** [comment]
As there is no real progress on the topic I close it for now.
