### ISSUE TITLE
Build error: "Target "qmapshack" links to target "Qt5::Positioning" but the target was not found" - qmapshack 1.15.0

### ISSUE THREAD

**Issue by GvMariani** [Maproom/qmapshack#247]
**Important Notice:**
**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**
What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?
[Yes ] Did you choose a good title?

**Describe the bug**
Trying to build qmapshack 1.15.0 on Rosa Linux x86_64, using gcc 5.5.0 and cmake 3.7.2.
Launching the build causes a failure with this error message in the konsole:
******************************************************************************************
CMake Error at src/qmapshack/CMakeLists.txt:912 (add_executable):
Target "qmapshack" links to target "Qt5::Positioning" but the target was
not found.  Perhaps a find_package() call is missing for an IMPORTED
target, or an ALIAS target is missing?
******************************************************************************************
As suggested by the above error message from cmake the CMakeLists.txt file in src/qmapsharck want to link to "Qt5::Positioning" but that variable was not initializated in the main CMakeLists.txt file.
Adding a "find_package(Qt5Positioning REQUIRED)" line in the main CMakeLists.txt file indeed fixes the build.

**What have you done to circle down the problem?**
Looked at the error message and tried to add the above fix.
Verified that the issue is present at leasr since release 1.13.1 (by looking at commit history of the main CMakeLists.txt file) and it is still present in the dev branch.

**To Reproduce**
1. Install sources.
2. Run cmake:
/usr/bin/cmake .. -DLIB_SUFFIX=64 -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 '-DCMAKE_MODULE_LINKER_FLAGS=-Wl,--as-needed  -Wl,-z,now -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags -Wl,--hash-style=gnu' -DDBUS_SERVICES_DIR=/usr/share/dbus-1/services -DDBUS_INTERFACES_DIR=/usr/share/dbus-1/interfaces .. -DBUILD_SHARED_LIBS:BOOL=OFF
3. See the above error message.

**Expected behavior**
Build completes successfully.

**Screenshots**
N/A
**Attachments**
N/A
**Tracebacks**
N/A

**Desktop (please complete the following information):**
 - Rosa Fresh R11 (Mandriva derivative, LTS)
 - QMapShack 1.15.0
 - Window Manager: KDE 5

**Additional context**
N/A

**Comment by kiozen** [comment]
Please test: https://github.com/Maproom/qmapshack/pull/248

**Comment by GvMariani** [comment]
> Please test: #248
Yeah, also this patch solves the issue, if really qt-positioning dep is useless and to be dropped: you are the one that can judge about this....
