### ISSUE TITLE
TMS map's MinZoomLevel value ineffective

### ISSUE THREAD

**Issue by flyingflo** [Maproom/qmapshack#250]
**Describe the bug**

I defined a TMS map with my self-made map from my server. 
It only has a z-value of 15.
The TMS file looks like this:
```
<TMS>
<Layer idx="0">
<Title>Kompass</Title>
<MinZoomLevel>15</MinZoomLevel>
<MaxZoomLevel>15</MaxZoomLevel>
<ServerUrl>http://servidor.lan/kompass/%1/%2/%3.jpg</ServerUrl>
</Layer>
</TMS>
```

Anyways, on the web servers access log, I see a request for z-value 6, which fails of course, and then no more requests, even if I zoom in and out on the empty map.
```
192.168.112.20 - - [01/Sep/2020:21:53:43 +0200] "GET /kompass/6/34/22.jpg HTTP/1.1" 404 491 "-" "Mozilla/5.0"
```

**What have you done to circle down the problem?**

Tried multiple [Min|Max]ZoomLevel settings, but requests on the server don't seem to match those limits.

**To Reproduce**

1. Put the .tms file in the map folder.
2. Have a web server with a (at least) one-zoom-level map.
3. Activate it.
4. See no tile of the map whatever zoom level you choose and no requests on the web server that are between MinZoomLevel and MaxZoomLevel

**Expected behavior**

Only zoom level 15 tiles are requested and shown. Or do I understand the TMS definition or anything else wrong?

**Desktop (please complete the following information):**

 - OS: Fedora 32
 - QMapShack Version 1.14.0-3.fc32
 - Window Manager: KDE

**Comment by kiozen** [comment]
That might be kind of a misunderstanding. Zoom levels in the TMS file are not equal to the zoom levels as the TMS server defines them. 

This is how the zoom level is calculated:

```
        qint32 z    = 20;
        QPointF s1  = buf.scale * buf.zoomFactor;
        qreal d     = NOFLOAT;

        for(qint32 i = layer.minZoomLevel; i < 21; i++)
        {
            qreal s2 = 0.055 * (1 << i);
            if(qAbs(s2 - s1.x()) < d)
            {
                z = i;
                d = qAbs(s2 - s1.x());
            }
        }

        if(z > layer.maxZoomLevel)
        {
            continue;
        }

        z = 21 - z;
```

Note that the TMS server's zoom level are ordered reverse to the ones QMS uses. For QMS a zoom level of 0 is most detailed and a zoom level of 21 less detailed. For zooming in the strategy is to stick with the minimum zoom level defined by the TMS file for all zoom levels closer than that. For zooming out the strategy is to skip the layer if the maximum zoom level is exceeded.

**Comment by flyingflo** [comment]
@kiozen Thanks for the explaination!

I set 
```
<MinZoomLevel>6</MinZoomLevel>
<MaxZoomLevel>6</MaxZoomLevel>
```
.. and now it behaves like I expected.
Sorry for the issue.
