### ISSUE TITLE
Mysql not available qmapshack crash

### ISSUE THREAD

**Issue by 7hemas7er** [Maproom/qmapshack#253]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

[X] Did you choose a good title?

**Describe the bug**

Remote mysql not avail
able qmapshack crash.

**What have you done to circle down the problem?**

not compared with previous version
not other isusses open for this problem

**To Reproduce**

1. add mysql database
2. database not available
3. program crash

**Expected behavior**

popup an error message 

**Screenshots**

**Attachments**

Can you provide an example file to trigger the problem?

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: Windows 10 2004
 - QMapShack Version 1.15

**Additional context**

**Comment by kiozen** [comment]
So far no one could reproduce the crash. I tested on Linux. Someone else on Windows. QMapShack provides the proper error message within the tool tip.

Could it be possible that you have a non matching qsqlmysql.dll?

**Comment by 7hemas7er** [comment]
I start program with visual studio and error is : 0x00007FFACB8F287E (ucrtbase.dll) in qmapshack.exe
the mysql server is installed in a remote site
qmapshack is an update, not a fresh install
in the installation dir I have found qsqlmysql.dll, version 5.12.3.0 
![qsqlmysql](https://user-images.githubusercontent.com/31734645/93237413-5b6d8480-f780-11ea-96eb-ab4f98b41f1a.png)

**Comment by 7hemas7er** [comment]
for solve my problem I remove mysql entrie from HKCU\SOFTWARE\QLandkarte\QMapShack\Database\Entries\

**Comment by 7hemas7er** [comment]
work with qsqlmysql.dll 5.12.2.0 found in Qt\5.12.2\mingw73_64\plugins\sqldrivers

after fresh install in folder QMapShack\sqldrivers  I not found qsqlmysql.dll
![immagine](https://user-images.githubusercontent.com/31734645/93369309-7ce97180-f84f-11ea-864b-15bcd02952eb.png)
![immagine](https://user-images.githubusercontent.com/31734645/93369325-8377e900-f84f-11ea-9ca3-04b67cab90b9.png)

**Comment by orsogrigio** [comment]
I confirm. If you install 1.15.0 on Windows for the very first time, the qsqlmysql.dll is not present under  QMapShack\sqldrivers. In the old 1.14 instead the driver is present and if you upgade to 1.15.0 it remains in the directory installation but it cause the crash explained at the begginnig of this issue. So please take care of include in the new installation package the correct driver for windows.

**Comment by kiozen** [comment]
First: Packaging is not in the scope of this project. The binary packages for Windows are provided by a volunteer as any other binary package.

That in mind, I was told that the more recent versions of pre-compiled Qt that are used to build the binary package do not include the MySQL plugin anymore. see https://bugreports.qt.io/browse/QTBUG-76081. So there is no way to ask a volunteer to add binaries into a package that have commercial status and thus violating licenses.

I heard you can find the plugin as binary somewhere in the Net. But this is not a solution we can support officially.

**Comment by wthaem** [comment]
Find some precompiled drivers for different Qt versions [here](https://github.com/thecodemonkey86/qt_mysql_driver/releases).

**Comment by kiozen** [comment]
As there is no real progress on the topic I close it for now.
