### ISSUE TITLE
MySQL: Add optional connection params

### ISSUE THREAD

**Issue by joschi1998nav** [Maproom/qmapshack#256]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Feature requests**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[ ] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

QMapShack till now only provides very limited options for connecting a MySQL database. If your server requires more sophisticated connection params QMapShack might e.g. fail to open the database or loose connection due to server-set timeouts.

**Describe the solution you'd like**

QSqlDatabase::setConnectOptions() would provide a way to set specific connection parameters (see https://doc.qt.io/qt-5.12/qsqldatabase.html#setConnectOptions for details). Suggestion would be:
- provide an additional text input "optional connection params" in database setup dialogue, default value blank
- store any string value from this text input together with database name, hostname etc.
- if this string value is other than "" use db.setConnectOptions(this_string_value) when opening the connection

**Describe alternatives you've considered**

Use a MySQL server that doesn't require those additional params. Might be a limiting factor for most people, though...

**Give a reason why someone else should spend time on that request**

I could do a quick & dirty hard coded setConnectOptions() in one single file of QMapShack sourcecode for my own purposes (and in fact I have done so). But that's a very specific solution for a very specific server setup. A more generic approach like described is beyond my abilities (or at least beyond self-confidence), I have to admit.

* The request solves a fundamental problem for everyone
* The request is of general interest for many users

Bad reasons are:
* Because software xyz does it
* Because you just want it to have that way
* Because it will solve a very particular problem.

**Additional context**

**Comment by kiozen** [comment]
As there is no real progress on the topic I close it for now.
