### ISSUE TITLE
Calculated DEM heights are incorrect

### ISSUE THREAD

**Issue by fullenser** [Maproom/qmapshack#259]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

[ ] Did you choose a good title? I think so.

**Describe the bug**

When I use QMapShack to replace the elevation of recorded tracks by DEM values, there is often a appreciable difference to the contour lines of OpenTopo map.

**What have you done to circle down the problem?**

To be sure, that not the DEM values itself are the problem, I wrote a Python script that uses the hgt-files from the same download as used by QMapShack. For each trackpoint of a track the script looks up for the surrounding four values in the corresponding hgt-file, interpolates according to the distances and adds the ele-tag.
When I open these updated tracks in QMapShack, the height values are nearly the same as the crossed contour lines show.
So it seems to be clear: the DEM values of the used hgt-files are correct.

**To Reproduce**

I add a simple constructed track crossing a hill in to versions: one with the elevation calculated by my script, the other with them replaced by DEM values with QMapShack. 
Just open them and try yourself! At the crossing with the 300 m contour line, there is a difference in altitude of 15 m between the two examples.

**Expected behavior**

I expected that the calculated heights nearly correspond to the crossed contour lines.

**Screenshots**

![example DEM error map with heights by QMapShack](https://user-images.githubusercontent.com/73926462/98077570-cb3ee800-1e70-11eb-9e92-24e254b76870.jpg)
![example DEM error map with heights by own script](https://user-images.githubusercontent.com/73926462/98077655-edd10100-1e70-11eb-9805-577505d79996.jpg)
![example DEM error details with heights by QMapShack](https://user-images.githubusercontent.com/73926462/98077678-fb868680-1e70-11eb-9a0e-6d2cdc850f85.jpg)
![example DEM error details with heights by own script](https://user-images.githubusercontent.com/73926462/98077704-050fee80-1e71-11eb-875f-6c4bdd50f993.jpg)

**Attachments**

[QMapShack DEM heights error.zip](https://github.com/Maproom/qmapshack/files/5485863/QMapShack.DEM.heights.error.zip)

**Tracebacks**

**Desktop (please complete the following information):**

 - OS: Windows 10 64-bit
 - QMapShack Version 1.14.0 and 1.15.0
 
**Additional context**

**Comment by kiozen** [comment]
If you think there is a problem have a look at:
```
qreal CDemVRT::getElevationAt(const QPointF& pos, bool checkScale)
```

**Comment by tormet** [comment]
Just to mention, if you use better andnewer DEM data then for me everything is fine. I have older DEM data for Germany, there I also get the 318m you showed here.

But if I get DTM Germany 20m v1 by Sonny from  https://data.opendataportal.at/dataset/dtm-germany then everything is fine. At the 300m line I got 302m.
![newHeights](https://user-images.githubusercontent.com/37560190/114747350-08c56c80-9d51-11eb-8f06-231b0ff58d0c.png)
