### ISSUE TITLE
Wrong timestamp when loading FIT

### ISSUE THREAD

**Issue by norbusan** [Maproom/qmapshack#262]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[X ] Did you choose a good title?

**Describe the bug**

The timezone information saved into GPX tracks is inconsistent, and in particular does not contain the correct timezone in the time stamps of the track points.

Looking at the GPX file I see
```
 <metadata>
  <name>2020.11.08 Karikomi-Ike</name>
  <time>2020-11-09T04:50:42.000Z</time>
 </metadata>
```
which is correct (I guess I downloaded it yesterday at that time).

But the track points are incorrect:
```
   <trkpt lon="136.71547961" lat="36.06665066">
    <ele>931</ele>
    <time>2020-11-08T13:31:44.000Z</time>
```
since the time part is the time in JST, but the time zone extensions is `Z` which is `GMT` and not `+0900`.

**What have you done to circle down the problem?**

It is the first time that I realize this.

**To Reproduce**

1. Select a track that is not in GMT timezone
2. Right click and Save as GPX
3. Import the GPX track in other applications, or read the text file manually

**Expected behavior**

Correct timezone information saved.

**Screenshots**

This screenshot shows that the track starts at 13:31 JST (+9)
![ksnip_20201110-120614](https://user-images.githubusercontent.com/1735589/98622586-36932900-234d-11eb-81d4-b754ebe8ed3e.png)

**Attachments**

This is the GPX track I am speaking about.
[2020.11.08 Karikomi-Ike.txt](https://github.com/Maproom/qmapshack/files/5514598/2020.11.08.Karikomi-Ike.txt)

**Tracebacks**

No crashes

**Desktop (please complete the following information):**

 - OS: Linux (Debian)
 - QMapShack Version 1.15.0
 - Window Manager KDE/Plasma

**Additional context**

The track was downloaded from a Garmin Fenix device.

**Comment by kiozen** [comment]
Hard to tell anything as you did not provide the original track file before it was loaded into QMapShack.

**Comment by norbusan** [comment]
Will get it again directly from the watch and attach it.

**Comment by norbusan** [comment]
Sorry for the long wait, here is the original FIT file (zipped)
[karikomi.zip](https://github.com/Maproom/qmapshack/files/5544006/karikomi.zip)

I also can confirm that when I do
```
gpsbabel -i garmin_fit -f  AB8D3144.fit  -o gpx -F  AB8D3144.gpx
```
the resulting GPX file has the correct times (saves as GMT times). Also, loading the gpx file into my Japanese GPS/Mapping program (Kashmir3D), the data is correctly included.

**Comment by kiozen** [comment]
I found a bug in the FIT implementation. Can you please test pull request #263.

**Comment by norbusan** [comment]
Great, thanks! I will test it later tonight or tomorrow (JST here)

**Comment by norbusan** [comment]
Confirmed that the PR fixes the issue. Thanks a lot.

**Comment by kiozen** [comment]
:+1: I just wonder why no one complained the last years. All users loading and storing FIT living in the UTC time zone?

Anyways, finally fixed.

**Comment by norbusan** [comment]
Not that I can answer your question, but I assume somehow that the intersection of Linux and Garmin and QMapShack and technically interested users is small.

But I think the real reason is that even **with** the bug, the data is shown **correctly** in qmapshack!!! If I just import the data, and hover with the mouse over tracks, I see the correct time, including time zone.

I only realized it because I use Kashmir3D a lot here in Japan, because it automatically downloads the excellent national maps which are freely available (wishlist item!), but Kashmir3D cannot import FIT data. So up to now I imported them into qmapshack, where I have also a lot of data from my work as pro mountain guide in Europe, and then export/save it as gpx. Then import the gpx into Kashmir3d. There I realized the timezone mixup.

Maybe the above explanation helps ...

Thanks a lot for your very nice program!!!!

**Comment by kiozen** [comment]
The bug always bites when you save data from a loaded FIT into a GPX. If you store it into a database it's fine because the database serializes the QDateTime object. And probably that's the reason why it's not affecting that many users.

Anyway, it's finally fixed :)
