### ISSUE TITLE
Configuring BRouter offline on MacOS crashes 

### ISSUE THREAD

**Issue by d029940** [Maproom/qmapshack#265]
**Describe the bug**

Configuring BRouter for local installation crashes.

**Desktop (please complete the following information):**

- MacOS Big Sur 11.01.
- QMapShack: 1.15.1 for MacOS 11
- BRouter 1.6.1
- Java: openjdk 11.0.9.1 2020-11-04 from AdoptOpenJDK (installed via brew)

**To Reproduce:**

- Click "Setup BRouter"
- Select local installation
- Download BRouter separately,  since QmapShack on MacOS cannot download BRouter (doing so by creating a new BRouter installation shows the download and install Version popup, but nothing happens).
- Select the directory where BRouter is saved . The option of update existing BRouter installation is offered. Since I have the most current version, I skip this.
- Click "Next"-Button presents the profiles. Taking any (does not matter which) and click "Next". This will lead to a crash of QMapShack.

I can do it over and over again. This error is reproducible.

--------------------------------------------------
 
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[ ] Did you choose a good title?

**Describe the bug**

**What have you done to circle down the problem?**

Did you compare to previous versions? What versions? Did you check
if others have the same problem?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Attachments**

Can you provide an example file to trigger the problem?

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: [e.g. OS X, Debian, Suse, Windows]
 - QMapShack Version [e.g. 1.13.1]
 - Window Manager [e.g. KDE, GNOME]

**Additional context**

**Comment by kiozen** [comment]
Please enter your request _in_ the provided template and _not above_ it, the next time. If not I might close it without reading it.
