### ISSUE TITLE
Support for Garmin Icons (like Basecamp is using it)

### ISSUE THREAD

**Issue by pinoy1** [Maproom/qmapshack#267]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Feature requests**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[X] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

Usually I am used to work with GPX-Files that i will use later on my Garmin-Device. Before i used Garmin Basecamp. I the avaliable Garmin-Icons (like for Port, Reef, Chruch, ...). It would be really great to have that also in QMapShack. That Icons are the ONLY reason for me that i still need to use Basecamp.

**Describe the solution you'd like**

I would like to have all the Garmin Standard Icons (like in Basecamp) avaliable in QMapShack so that if i export Data to my GPS device it will be able to display the right icons. Actually i don't know the logic in the background that an specific icon will be the same even in Basecamp, QMapShack or on the GPS Device.

**Describe alternatives you've considered**

It would be ok with me maybe just to download the set of icons to the waypointicons-folder.

**Give a reason why someone else should spend time on that request**

I think haveing the Garmin Icons avaliable can be userful for many users. I know many users who still need basecamp just because of the compatibility of the Garmin icons. Please don't say i should not use QMapshack but Basecamp, but i do not like to use Basecamp, but i need.

* The request solves a fundamental problem for everyone
The request is of general interest for many users

Bad reasons are:
* Because software xyz does it
* Because you just want it to have that way
* Because it will solve a very particular problem.

**Additional context**

![image](https://user-images.githubusercontent.com/48749997/100720934-00325200-33bf-11eb-918c-4409fbd77993.png)

**Comment by kiozen** [comment]
You have two options here:

1. You donate a set of icons where you hold the copyright and with a license that is Open Source compliant. The icon format must be SVG. In that case we can integrate those icons into the source code

2. You get your icons from what ever source you consider appropriate an add them as custom icons:

https://github.com/Maproom/qmapshack/wiki/DocGisItemsWpt#user-content-custom-icons

**Comment by pinoy1** [comment]
Thanks for the advice. So i will produce my own Garmin Iconset.
But how can i make transparences in the icons? In another software its possible with the color RGB 255 0 255 (magenta).

**Comment by kiozen** [comment]
QMapShack takes PNG as a format and PNG supports a transparent alpha channel

**Comment by kiozen** [comment]
I assume this ticket will not add anything to the project therefor I close it.
