### ISSUE TITLE
Crash after closing project where range is being selected

### ISSUE THREAD

**Issue by FabianInostroza** [Maproom/qmapshack#268]
[X] Did you choose a good title?

**Describe the bug**

If you close a project while range is being selected (right click "Select Range") on one of its tracks then QMapShack crashes with a segfault.

**What have you done to circle down the problem?**
It also happened at least on 1.15.0

**To Reproduce**

1. Load some gpx or fit file
2. Right click on one of the tracks and select "Select Range"
3. Right click on the associated project and close it.

**Expected behavior**
Application doesn't crash.

**Screenshots**

**Attachments**

Can you provide an example file to trigger the problem?

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: Debian
 - QMapShack Version 1.15.1
 - GNOME

**Additional context**

**Comment by kiozen** [comment]
Thanks for reporting. Please test:

https://github.com/Maproom/qmapshack/pull/269

**Comment by FabianInostroza** [comment]
> Thanks for reporting. Please test:
> 
> #269

Working fine here. 
Thanks.
