### ISSUE TITLE
Error: "No georeference information found." when activating DEMs

### ISSUE THREAD

**Issue by cvigo** [Maproom/qmapshack#278]
**Describe the bug**

I downloaded several `wcs` files to get online DEM from a number of resources in Spain and also an offline DEM with its `vrt` and `tiff` files (all attached but `tiff`)

All of them work in my MacBook Pro with **MacOS 11.0.1** (20B29), QMS 1.15.2, Qt 5.14.2, **GDAL 3.0.3**

None of them work in my iMac **MacOS 10.15.7** (19H15), QMS 1.15.2 Qt 5.14.2, **GDAL 3.2.0**. All showing the error "_No georeference information found._" when I click on "Activate".

**What have you done to circle down the problem?**

On the iMac, QMS 1.10 was working

**To Reproduce**

1. Copy the attached files in your DEM folder
2. Open QMS
3. Right-click any of the DEM and click on "Activate!

**Expected behavior**

DEM should be activated.

**Screenshots**

![image](https://user-images.githubusercontent.com/4451828/102073008-f1a65a80-3e02-11eb-8acb-81692f24a371.png)

**Attachments**

[DEM.zip](https://github.com/Maproom/qmapshack/files/5688323/DEM.zip)

**Tracebacks**

No crashes 

**Desktop (please complete the following information):**

 - OS: iMac. MacOS 10.15.7 (19H15)
 - QMapShack Version: QMS 1.15.2 Qt 5.14.2, GDAL 3.2.0.
 - Window Manager: MacOS

**Additional context**

None

**Comment by kiozen** [comment]
I uploaded new packages. The former ones seem to have a GDAL version that was not compiled with libcurl and thus lacked all the online map formats. Please test and report.

**Comment by cvigo** [comment]
working again. Thanks!!
