### ISSUE TITLE
Track metrics not updated when using UNDO / REDO in Edit mode

### ISSUE THREAD

**Issue by cdusqud** [Maproom/qmapshack#279]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**
[x ] Did you choose a good title?

**Describe the bug**
When you're creating a track in Edit Mode, the track metric window offers some important information of the track:

-Distance 
-Ascent
-Descent

This information gets properly updated each time you modify the track by adding new points, or modifying / deleting existing ones, which is a very useful feature. 

However, if you Undo / Redo your last action instead, the track metric window doesn't get updated with the correct information, showing incorrect Distance / Ascent / Descent data. 

**What have you done to circle down the problem?**
I only tested the problem in v. 1.15.2. I've tried with different routing methods (routino, vector, no autorouting), but it's always the same behaviour. 

**To Reproduce**
1. Add a track. 
2. Create two or or three new points. 
3. Take a look on the Track metrics window. 
4. Undo your last action. Your track should be now be shorter. 
5. Take a look on the Track metrics window. It won't be updated, showing exactly the same data at point 3

**Expected behavior**
The track metrics window should always offer correct information, and get properly updated when using undo / redo functions in Edit Mode. 

**Screenshots**
I've attached a couple of screenshots showing the problem. 

**Attachments**
![1](https://user-images.githubusercontent.com/76106623/102351040-16870300-3fa6-11eb-8ae7-8ba84db44ccd.png)
![2 (After Undo)](https://user-images.githubusercontent.com/76106623/102351081-27377900-3fa6-11eb-8935-363a4c1e00fe.png)

**Tracebacks**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - QMapShack Version [1.15.2]

**Additional context**

There are a couple of workarounds to solve the problem, but I think that track modifications should be reflected in the track metrics window, no matter if the modifications are manually done, or made through the undo feature.

**Comment by kiozen** [comment]
Wow, never noticed :laughing: Fixed it. Thanks for reporting.

**Comment by cdusqud** [comment]
Thanks very much!
