### ISSUE TITLE
TOC in Wiki not working

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#28]
**Describe the bug**
I am not sure if this was discussed on the mailing list, but the table of contents on top of at least the [CommitCode page](https://github.com/Maproom/qmapshack/wiki/DeveloperCommitCode) is not working.

**To Reproduce**
1. Go to the [CommitCode page](https://github.com/Maproom/qmapshack/wiki/DeveloperCommitCode)
2. Click on any of the links above the header

**Expected behavior**
I would expect it to jump down to the linked section

**Desktop (please complete the following information):**
 - OS: Firefox on Windows

**Comment by kiozen** [comment]
oops! Fixed it.
