### ISSUE TITLE
Tags icons / rating disappear from workspace after saving and closing a project

### ISSUE THREAD

**Issue by cdusqud** [Maproom/qmapshack#282]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**
[X ] Did you choose a good title?

**Describe the bug**
After tagging tracks in the workspace with rating and keywords, the icons will disappear if you save  > close > reopen the project from the database. 

**What have you done to circle down the problem?**
I've only checked v. 1.15.2. I've also asked in the spanish forum mendiak.net and the problem can be replicated by another user using Linux version. 

**To Reproduce**
1. Activate "Show tags in the workspace tree" option. 
2. Tag some tracks with rating and keywords. The tag icons / rating will be properly shown on the "Rating" column:
![1 - Tags OK](https://user-images.githubusercontent.com/76106623/102805688-e41d4180-43bb-11eb-993e-e9960e39e914.png)

3. Save the project to the DB. Close the project. Open the project from the database again. 
4. The tags / rating are not shown anymore:
![2 - No tags](https://user-images.githubusercontent.com/76106623/102805750-fac39880-43bb-11eb-8b6c-560d35226e64.png)

**Expected behavior**
When using "Show tags in the workspace tree" option, the track / rating info should appear on the appropriate column no matter if the project was closed and reopened again.

**Screenshots**
(Shown above) 

**Attachments**
N/A

**Tracebacks**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QMapShack Version 1.15.2
 - Window Manager [e.g. KDE, GNOME]

**Additional context**
Closing the project won't delete the tag / rating data, only the icons disappear after reopening the project. In order to see the icons again in the workspace, it's necessary to re-tag the tracks.
![3](https://user-images.githubusercontent.com/76106623/102805794-0a42e180-43bc-11eb-8a52-8936e8396cb6.png)

**Comment by kiozen** [comment]
@pingurus can you please have a look?

**Comment by cdusqud** [comment]
Thanks!
