### ISSUE TITLE
Compile error: interpolation.h not found

### ISSUE THREAD

**Issue by martinstingl** [Maproom/qmapshack#283]
I get a compile error with the current git version:

martin@desktop:~/apps/build_QMapShack$ make
[  1%] Automatic MOC for target qmapshack
[  1%] Built target qmapshack_autogen
[  1%] Building CXX object src/qmapshack/CMakeFiles/qmapshack.dir/qmapshack_autogen/mocs_compilation.cpp.o
In file included from /home/martin/apps/QMapShack/src/qmapshack/gis/prj/CDetailsPrj.h:22,
                 from /home/martin/apps/build_QMapShack/src/qmapshack/qmapshack_autogen/HSVUMMUBKV/moc_CDetailsPrj.cpp:9,
                 from /home/martin/apps/build_QMapShack/src/qmapshack/qmapshack_autogen/mocs_compilation.cpp:40:
/home/martin/apps/QMapShack/src/qmapshack/gis/trk/CGisItemTrk.h:35:10: fatal error: interpolation.h: No such file or directory
   35 | #include <interpolation.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/qmapshack/CMakeFiles/qmapshack.dir/build.make:1528: src/qmapshack/CMakeFiles/qmapshack.dir/qmapshack_autogen/mocs_compilation.cpp.o] Error 1

**Comment by kiozen** [comment]
Bad installation of alglib in your system. Not really a problem of QMapShack

**Comment by kiozen** [comment]
Please use the templates

https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

I will close issues that do not stick to that without further notice.

**Comment by martinstingl** [comment]
Thank for for pointing to alglib. I couldn't figure it out for myself.
Shouldn't it somehow be mentioned in the compile instructions?
After installing the package libalglib-dev compiling works for me.
