### ISSUE TITLE
Add Canadian topographic maps server

### ISSUE THREAD

**Issue by ssmlc** [Maproom/qmapshack#287]
**Is your feature request related to a problem? Please describe.**

The Canadian government provides a WMS server for topographic maps. I have written a WMS to TMS file based on the MOBAC feature:
```
https://sourceforge.net/p/mobac/feature-requests/197/
```
Should it go with the automatic downloads, or in the wiki under:
```
https://github.com/Maproom/qmapshack/wiki/DocMapsTipsOnline#use-wms-server-as-tms-server
```

**Describe the solution you'd like**

Here is the .tms file:
```
<TMS>
<Layer idx="0">
<Title>Canada - Toporama</Title>
<Script><![CDATA[(
function convert(z,x,y)
{ function tile2lon(x, z) {return x / Math.pow(2.0, z) * 360.0 - 180;}
  function tile2lat(y, z) {
    n = Math.PI - (2.0 * Math.PI * y) / Math.pow(2.0, z);
    return (Math.atan(Math.sinh(n)))*180.0/Math.PI;
  }
  north = tile2lat(y, z);
  south = tile2lat(y + 1, z);
  west = tile2lon(x, z);
  east = tile2lon(x + 1, z);
  baseUrl = "http://wms.ess-ws.nrcan.gc.ca/wms/toporama_en?service=wms&request=GetMap&version=1.1.1&format=image/jpeg&srs=epsg:4326&layers=limits,vegetation,builtup_areas,designated_areas,hydrography,hypsography,water_saturated_soils,landforms,constructions,road_network,railway,aeronautical_network,structures,power_network,boundaries,feature_names&width=256&height=256&bbox="
  return baseUrl + west +"," + south + "," + east + "," + north;
}
)]]></Script>
</Layer>
<Copyright>Contains information licensed under the Open Government Licence - Canada.</Copyright>
</TMS>
```

**Describe alternatives you've considered**

The file could be automatically loaded with this in src/qmapshack/map/, added to the wiki as done for the North Rhine-Westphalia and Bureau de Recherches Géologiques et Minières examples, or discarded.

**Give a reason why someone else should spend time on that request**

This will provide online access to high quality maps covering a large geographic area.

**Comment by kiozen** [comment]
Hi, please add it to the Wiki.

However a short smoke test failed on my side. Somehow Math.sinh() function is failing.

```
2020-12-30 12:57:00.982 [debug] Request to "typeerror: Property 'sinh' of object [object Math] is not a function"
```

**Comment by wthaem** [comment]
It worked for me on Windows10 without any problems for Canada. Maybe, slightly different javascript implementations used here.

But when testing I came across another question: EPSG:4326 is quite a universal CRS supported by many map servers. The proposed script formula seems not to have any Canadian specifics. Thus, I tried to use the proposed script with other (European) servers and failed. One result for a Spanish server didn't create a map of Spain but distributed the tiles all over the world.  Some permutation of the bbox coordinates resulted in a nice Spain map. With German servers a failed completely.

Any proposal how to improve the formula so that it can be applied to other servers supporting EPSG:4326?

**Comment by kiozen** [comment]
Yes, it's probably just my system. sinh() is documented to be function of Math object.

Haven't had the nerve to look into that formula. I am busy with that sh.. Garmin format stealing away another part of my lifetime.

**Comment by wthaem** [comment]
My guess: the formula with sinh(..) can be replaced with the formula used in CMapTMS.cpp/tile2lat(int y, int z).

**Comment by ssmlc** [comment]
Tes these formulas are the same; so are the tile2lon functions. Is it possible to call those functions?

I haven't added it to the wiki, should I replace the sinh with the identity used in CMapTMS.cpp?

Unfortunately I don't know about working with the other servers.

**Comment by wthaem** [comment]
@ssmlc: I took the freedom and included a slight modification of your example in the Wiki.

See page [DocFaqMaps](https://github.com/Maproom/qmapshack/wiki/DocFaqMaps#user-content-how-to-build-the-url-when-using-wms-via-tms) (last example in the linked section).

**Comment by kiozen** [comment]
@wthaem we could host it  and it to the maps collection of the wiki

https://github.com/Maproom/qmapshack/wiki/DocMapDemSources#other-regions

**Comment by wthaem** [comment]
I hesitate to do this - Mitxel promised to revise the whole stuff! 

Meanwhile, I have quite a long list of working (and not working!) WMTS, WMS, and TMS based maps. It wouldn't be possible to list them all in the Wiki. This is the reason why I tried to formulate some general rules in DocFaqMaps.

**Comment by pingurus** [comment]
> Meanwhile, I have quite a long list of working (and not working!) WMTS, WMS, and TMS based maps. It wouldn't be possible to list them all in the Wiki. This is the reason why I tried to formulate some general rules in DocFaqMaps.

How about creating a seperate repository where we collect online map files? I'd have a large TMS file for South Tyrol/Alto Adige to contribute.

**Comment by kiozen** [comment]
Actually this is what we do. The Wiki is a Git repository. There is a download folder where you can store those files. And there are tables to add a reference to the file. 

The only caveat: You need write access to the repository to upload files into the download folder which is restricted. However Wolfgang or me are happy to upload files for you.

**Comment by ssmlc** [comment]
@wthaem, in case you (or someone else) is curious, I got the list of available layers from here: 
http://wms.ess-ws.nrcan.gc.ca/wms/toporama_en?VERSION=1.1.1&request=GetCapabilities&service=wms

I think the list of maps in an easy-to-find place is useful, and it would be nice to add this TMS to the wiki. I'll leave it to you to decide.

Thank you for your responses so far. Feel free to close the issue, or perhaps keep discussing what to do with these files.
