### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by roya0045** [Maproom/qmapshack#288]
**Is your feature request related to a problem? Please describe.**

I stumbled upon this project and as a GIS user and contributor I was curious about it. But I find it difficult to understand what is the project about. Given that it is a GIS software in a domain with other established softwares and some that share dependencies (QGIS), it would be a good idea to present the project for what it is and possibly aims to be.

**Describe the solution you'd like**

I think it would be useful to add more information in the readme about the project itself before how to build.
Elements that could be added:

- Design philosophy
- Intended goals/targeted audience
- Distinguishing features/advantages
- Existing features (data type support, processing, modability?)
- Images

**Give a reason why someone else should spend time on that request**

Providing such information will help people learn about your project and should be more helpful than simply listing how to install the software if people are not sure what does said software.

**Comment by kiozen** [comment]
Why doesn't the wiki fit your needs? Why copy-pasting that stuff over several places?  Why placing that stuff into a file that is intended to give a brief compile instruction?

**Comment by roya0045** [comment]
@kiozen I didn't check the wiki tab and yes it does contain many of those elements you are right. Though the readme is the first thing people see about the project and there is no mention of the wiki, as it could also contain the installation instruction. The wiki tab is often a secondary source of information that is not often populated properly, this is why I didn't even consider it.
I'll close this ticket in this case.
