### ISSUE TITLE
CMake patches for PROJ4 and QuaZip expired too early

### ISSUE THREAD

**Issue by meinhardh** [Maproom/qmapshack#291]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

**Describe the bug**

Building qmapshack on Debian (-derived) systems fails at the cmake step producing errors about missing FindPROJ4.cmake and FindQuaZip5.cmake files.

**What have you done to circle down the problem?**

As builds worked fine last year, drilling down into CMakeLists.txt revealed that the missing files were created conditionally with an expiration year of 2021. For dates in 2021, this condition is not met, hence the .cmake files are not created.

**To Reproduce**

Just try a plain rebuild of the stock distro on a Debian (-derived) system

**Expected behavior**

cmake step runs to completion successfully

**Screenshots**

n/a

**Attachments**

Please see the attached proposed patch (that for the moment just pushes the problem to 2022...)

cat > CMakeLists.txt.patch <<EOD
--- qmapshack-V_1.15.2/CMakeLists.txt.orig	2020-12-07 17:13:38.000000000 +0100
+++ qmapshack-V_1.15.2/CMakeLists.txt	2021-01-04 11:10:21.121462442 +0100
@@ -24 +24 @@
-set(EXPIRE_YEAR "2021")
+set(EXPIRE_YEAR "2022")
EOD

**Tracebacks**

n/a

**Desktop (please complete the following information):**

In my case (but I don't think it matters):
Ubuntu 20.04 (focal)
QMS 1.15.2
Gnome (However I'm using ccmake in a terminal window, no window manager involved at this step)

**Additional context**

n/a

**Comment by kiozen** [comment]
I think the grace time was long enough. This is not really a problem of QMapShack. I can't tell if it is just a bad setup of the build scripts in  proj4 and quazip or the stubbornness of Debian packaging. I just know that for other distributions it's a nothing as they simply install the the cmake and autoconf files in parallel. 

Providing own cmake files for dependencies in a project is bad and should be avoided.

**Comment by meinhardh** [comment]
I've found the discussion thread from April 2019 and fully agree that
conceptually the maintainers of dependency libraries should provide the
required files for all supported build systems - and cmake clearly is
one of them.

Practically this doesn't help, though... for the last 20 months or so,
nothing has happened. Simply making a fix break because it's now 2021
(late in December I had compiled QMS just fine on another Focal system)
is very surprising.

I'll see whether I can raise a ticket concerning the Focal libproj-dev
package.

Cheers,

Helge

**Comment by kiozen** [comment]
I would appreciate that. My development time for this project is quite limited these days and mostly consumed by bug reports, reviews and discussions. In the end there is not enough time to really develop new stuff and no one else picks up the larger topics anyways. This is why I cut edges and and simply refuse to do stuff that is not 100% related to QMapShack code. Therefore picking up that topic and moving it to either Proj4/quazip or Debian is really helping.

**Comment by meinhardh** [comment]
Sure: https://bugs.launchpad.net/bugs/1910131

**Comment by kiozen** [comment]
thx. I cose this one for now.
