### ISSUE TITLE
Strange non-existing cache path used for WMTS and TMS files

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#293]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Describe the bug**

I'm trying to understand why an online map defined with a WMTS file isn't shown in QMS.

When running QMS with a debug log, then one of the early information is about the used cache:

`2021-01-05 9:43:13.542 [debug] "CACHE" path "C:/Users/k-wth/.QMapShack"`

This path is ok and can be found. But it is empty.

When loading and using a WMTS file there is a check, if a tile can be found in a cache. Here is the line in CMapWMTS.cpp:

`if(diskCache->contains(url))`

The test result in my case is "tile is in cache" for all tiles. Thus, the typical counter showing the number of tiles still to be downloaded isn't shown. But no map is shown, too!

With the help of the additional line

`qDebug() << "cache" << dir.path() << "abs" << dir.absoluteFilePath("QMS_cache");`

in CDiskCache.cpp I expect to get the location of the cache used in the above test. Result:

`2021-01-05 9:40:31.507 [debug] cache "C:/Users/wt/.QMapShack/mapy.geoportal.gov.plwssserviceWMTSguestwmtsTOPO" 
                                abs "C:/Users/wt/.QMapShack/mapy.geoportal.gov.plwssserviceWMTSguestwmtsTOPO/QMS_cache"`
                                
This path is different from the one mentioned above and doesn't exist (the debug statement comes after the `dir.mkpath(dir.path())` statement!).
This wrong path is also shown in an infobox when hovering with the mouse over the WMTS file name in the maps window.

There is no user `wt` on my computer, even if `wt` is quite often used as an abbreviation for my user name (it is, as can be seen later, the git branch name in which I made some changes to the source code). No idea where it does come from here.

Can it be that the `contains` method used works with non-existing directories and returns always "true"?

I changed the filename of the WMTS file and its abstract text to force a change of the cache - no change in the behavior.

I'm not sure if the described cache issue is the reason for not seeing a map. 

**What have you done to circle down the problem?**

I tried to get as debug info the resourceURL used for downloading a tile but failed due to the cache issue.

**To Reproduce**

Look at the cache path displayed for any WMTS or TMS file in the map window - there is everywhere the same and non-existing user. But most online maps work as expected!

**Expected behavior**

The cache path should be found on the computer. For debugging purposes there could even arise the need to delete manually the cache content.

**Screenshots**

None.

**Attachments**

Can you provide an example file to trigger the problem?

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: Windows 10
 - QMapShack Version 1.15.0
 
commit e9e80b6d22743184d293cb8f9648170577c2e937 (HEAD -> wt, origin/dev, origin/HEAD, dev)
Author: kiozen <oliver.eichler@gmx.de>
Date:   Mon Jan 4 12:08:57 2021 +0100

    [QMS-285] WMTS-based maps aren't restored correctly

**Additional context**

None

**Comment by kiozen** [comment]
What is the setup in the "Setup Map Paths" dialog and what is stored in the registry "cachePath"?

**Comment by wthaem** [comment]
That's it! I was still using a very old INI file from another PC! 

Thanks for the hint!

Handling of the INI file/config data in the source code is still a mystery for me.

**Comment by kiozen** [comment]
It's not that much of a mystery. If a value is in the config it is used. If it's key is not found the provided default is used. In your case the key could be found and thus the old value was restored. But you should be able to change it in the map path setup dialog.

**Comment by wthaem** [comment]
Thanks again for the hint. Understood this. The mystery for me is the handling of the config data in the source - my C++ weakness. Had I understood the code I wouldn't have raised a silly issue. Sorry!
