### ISSUE TITLE
Load POI file

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#301]
**Important Notice:**

This is for developers only. As a user use the `bug report` or `Everything that's not a bug` template.

**The parent ticket**

_add ticketnumber behind the #_

QMS-#294

**What do you plan to do**

Load the POI file "blindly", just as it was already the case in #296.

**The result will be**
- [x] QMS is able to load a large number of POIs without too much lag
- [x] It is selectable which types of POIs to load
- [x] The POIs have the icons that correspond to their type

**Comment by kiozen** [comment]
Also consider not to load all pois and to iterate over them but to make an intelligent query that sets limits to the coordinates and other filtering. For the first try limiting the coordinate to the viewport would be fine.
