### ISSUE TITLE
Show Track Profile in Create Track mode.

### ISSUE THREAD

**Issue by cqg2** [Maproom/qmapshack#306]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Feature requests**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**
[x] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

Not really a problem, but such a feature would be helpful when creating a new track in QMS. 

**Describe the solution you'd like**
When creating a track, the user gets the track metrics window, which offers very useful information (distance, ascent, descent) about the track being created:
![1](https://user-images.githubusercontent.com/76106623/104819819-6c163000-5830-11eb-8cdf-6aefa3d13359.png)

The track profile also offers really useful information, but in order to access it, the track must be previously finished and saved. What I would like is the possibility of getting the profile of the track being created on the fly, while still in Edit Track mode and without the need to finish and save the track first:
![4](https://user-images.githubusercontent.com/76106623/104819823-70424d80-5830-11eb-9e59-c94693408e1d.png)

Of course, the profile should update itself when new points are added / deleted / modified to the track, that would be very useful to the user, in order to quickly compare different alternatives (for example, different ways of going from point A to B) when planning a new track.

**Describe alternatives you've considered**
A good alternative would be allowing the user to apply track elevation / slope styles while on edit track mode, colorizing the track according with the elevation / slope data: 
![7](https://user-images.githubusercontent.com/76106623/104822320-e1d6c780-5841-11eb-9891-eb298c02def1.png)

The options we have now are to create different track variations, save them all and compare their profiles (wich is, of course perfectly doable, but more time consuming and not so immediate for the end user), or simply figuring out the profile track just by looking at the contour lines of the map.

**Give a reason why someone else should spend time on that request**
One of the main purposes of the software is planning routes and creating tracks. This feature, while not being essential at all, would be a nice addition to the already great set of flexible tools designed for this purpose, and, IMO would help to enhance  the user experience when planning a new trip.
Thanks for considering!

**Additional context**
N/A

**Comment by mitxel-m** [comment]
A feature for coloring the track on the fly when you draw can be useful, and of course is more realistic than the proposal of the magic number in #281 (which in my opinion can be dangerous).

Nevertheless, keep in mind that in most cases you will have to draw several options and evaluate them once you finish drawing, because you will never be able to draw two different variants from A to B without having to insert intermediate points. Therefore you will never be able to compare before you finish drawing.


Translated with www.DeepL.com/Translator (free version)

**Comment by kiozen** [comment]
As there is no progress for a long time I close it for now.
