### ISSUE TITLE
Optimization of POI query

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#307]
**Important Notice:**

This is for developers only. As a user use the `bug report` or `Everything that's not a bug` template.

**The parent ticket**

_add ticketnumber behind the #_

QMS-#294

**What do you plan to do**

@kiozen wrote:
> The search has to be optimized. There should be a sweet spot for the area covered by each query. If it is too small you ahve too many queries. If it is too large queries take too long. There might be also some potential in optimizing the SQL query. Or by creating additional temp tables at startup. I am no database specialist but I think there is a lot of potential in how to query a database.

**The result will be**

- [ ] The query should be considerably faster.

**Comment by pingurus** [comment]
I am thinking about whether it would be better to not query for the attributes in the SQL query. As far as I've understood the data column is not indexed in the SQLite file, so it is comparably slow to search for items in that column.

My idea would be to load all POIs from a 'tile' (the size may be changed for better speed) and then do a bucket sort into the existing map.
**Advantages:**
* Independent of how many categories are activated, there is only one query per tile executed

**Disadvantages**
* Initial loading may be a bit slower than before
* Memory consumption is drastically higher

I don't think that going half the way (querying every active category at once) would be better, since we would then have to also do a bucket sort, since all POIs are returned as one batch.

Just as @kiozen I am no database expert (This is the first time I really do work with SQL databases) so my reasoning may be flawed.

**Comment by kiozen** [comment]
Always when I am confused I start to ask the Internet. Most times I end up even more confused. But sometimes it helps :smile: 

Maybe it's a good idea to see how Osmand does a query. And the problem is not new therefor it's very likely that solutions have been discussed somewhere.

**Comment by mitxel-m** [comment]
@pingurus  To be honest, I'm not an expert, just a DB user. 
I have taken a look at the structure of a POI file, and there is a 'poi_index" table that contains the lat/lon max and min values.
It contains exactly the same number of rows as the 'poi_data" table and I assume both tables can be realtioned by their 'id' field.

May be you could  search first in the poi_index table   with a WHERE clausule and JOIN with the poi_data
```
select poi_index.*, poi_data.data from poi_index inner join poi_data on poi_index.id=poi_data.id WHERE minLat >= 40.00 AND maxLat <= 40.50 AND minLon >= 4.00 AND maxLon <= 4.5 
```
_That statment worked fine when I tested with the POI file for Spain. ( found 267 matches in 336ms ,from 1267649 total rows )_

then you should make a second search for 'data' within the results of the first search. ( or add it in the previous search)
but I don't know how to implement this in the code.

I think this is in line with what is explained in the sqlite documentation:

[https://sqlite.org/rtree.html](https://sqlite.org/rtree.html)

HTH

**Comment by pingurus** [comment]
Note to self / anyone who is interested:
The way how Mapsforge internally queries POIs can be found here:
[How the query is built](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-poi/src/main/java/org/mapsforge/poi/storage/PoiCategoryRangeQueryGenerator.java)
[What the constants mean](mapsforge-poi/src/main/java/org/mapsforge/poi/storage/DbConstants.java)

I'm not 100% sure, but I think it is how I initially built the query which was later replaced by versions that @wthaem found that where faster

**Comment by wthaem** [comment]
>I'm not 100% sure, but I think it is how I initially built the query which was later replaced by versions that wthaem found that where faster

The Mapsforge and the original QMS query seem to be quite similar or even equal. The objectives of the Mapsforge and the QMS queries are most likely different.

Mapsforge: construct easily various queries from query pieces, performance might not be the primary goal.

QMS: good performance is highly desirable.

In my opinion, performance depends not only on the query performance but at least on 3 factors:

1. The number of POIs in a POI file. Danger: Some users might prefer POI files for whole countries instead of several ones for smaller regions in a country.
1. The rationale behavior of the QMS users. When looking for cafés in Mallorca it is not a good idea to look at the map of the whole of Spain and select all types of restaurants.
1. The performance of the data query. Several variants of a SQL query have been discussed. What is missing is a reliable performance test of the different queries. I think, the queries in QMS can be changed relatively easily. Therefore, I wouldn't spent much more time on this topic. User experience and feedback will show if more should be done in the future.

**Comment by pingurus** [comment]
> * The number of POIs in a POI file. Danger: Some users might prefer POI files for whole countries instead of several ones for smaller regions in a country.

I think that the overall size of the poi file only matters, if there is no rtree support. What matters though is the number of the POIs returned by the area selected.

> * The rationale behavior of the QMS users. When looking for cafés in Mallorca it is not a good idea to look at the map of the whole of Spain and select all types of restaurants.

Currently choosing more categories than necessary is penalized by causing more sql queries for the same area. It might be sensible to query for all selected categories together. (Is it possible that you (@wthaem) suggested this before?) At least in my DB Browser it took only about 75% of the time to query for three categories together instead of querying for each separately.

You might be right though, that we shouldn't spend much more time on this.

**Comment by pingurus** [comment]
From [#330](https://github.com/Maproom/qmapshack/issues/330#issuecomment-787201429) : Limit queries to bounding box of POI files
