### ISSUE TITLE
Improve name selection for POI

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#321]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Feature requests**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[ x] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

In a POI file a POI may have several name fields, e.g. depending on language choice. One of them is `alt_name` (alternate name?).

Currently, it may happen, that QMS displays the `alt_name` field content, maybe, with an additional `alt_` prefix. It would certainly  be better to use the `name` field content (compare attached snapshot, left side: DB browser content, right side: QMS workspace/POI window).

**Describe the solution you'd like**

Set the value of the name field as name of the QMS waypoint obtained from a POI.

In the case, that the `name` field is missing or doesn't have a value (there are such cases!), use the value of one of the other `name:xx` fields, preferrably, `xx=en` or `xx=QMS language`. A QMS waypoint should have a name! Otherwise, the items list in the workspace looks strange!

For the description text in the waypoint, try to keep/insert linebreaks as seen in the DB Browser, otherwise information is difficult to read.

**Describe alternatives you've considered**

**Give a reason why someone else should spend time on that request**

Keep in mind that you ask others to spend their spare time for your request. Convince them
by giving a reason why solving your request has a benefit for them, too. Good reasons are
if you are able to prove

* The request solves a fundamental problem for everyone
* The request is of general interest for many users

Bad reasons are:
* Because software xyz does it
* Because you just want it to have that way
* Because it will solve a very particular problem.

**Additional context**

![POINames](https://user-images.githubusercontent.com/55309218/106283444-3b77c280-6242-11eb-8bf5-7c2e63b1d47f.png)

**Comment by pingurus** [comment]
Good catch for the `alt_name=` case, I wasn't aware of that possible tag.

> In the case, that the name field is missing or doesn't have a value (there are such cases!), use the value of one of the other name:xx fields, preferrably, xx=en or xx=QMS language. A QMS waypoint should have a name! Otherwise, the items list in the workspace looks strange!

Currently it should default to the name of the category, if there is no name recognized. Are the language abbreviations of the languages the same in QMS and OSM?

> For the description text in the waypoint, try to keep/insert linebreaks as seen in the DB Browser, otherwise information is difficult to read.

Yep, I tried that, but QMS neither reacts to the </br> tag nor the linefeeds that I insert (although both are invisible)

**Comment by wthaem** [comment]
_Currently it should default to the name of the category_: Dangerous! Reason: several waypoints may get the same name. But I think, typically one of the name fields should have a value. Thus, it is likely to find a name by looking through the `name_xx` and the `alt_name` fields. 

_Are the language abbreviations of the languages the same in QMS and OSM?_ Not sure. Most likely it is in both cases the 2-letter language standard code used for most of the languages. But there are 3-letter codes for some less used languages, too!

**Comment by pingurus** [comment]
> Dangerous! Reason: several waypoints may get the same name.

Dangerous in what way? QMS can handle it. I think it still should be the last fallback, if other naming fails (except there is some issue I didn't think of)

**Comment by wthaem** [comment]
As mentioned: a waypoint in a project should have a unique name. Thus, if fallback to category is necessary, add, for instance, a number to make it unique.
