### ISSUE TITLE
Add support for POI search

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#323]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Feature requests**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

A POI may have a lot of OSM tags.

In the current QMS implementation of POI handling POIs are grouped by category and subcategory. A category/subcategory is defined by a certain set of OSM tags.

There are fixed sets of categories and subcategories.

This certainly reasonable approach to POI classification in QMS has 2 disadvantages.

1. It is not obvious to which category/subcategory a POI does belong and thus it can be difficult to find it in QMS. Example: looking for (Christian) churches you can select `place - of_worship_christian`. With this choice you might not find some (orthodox) churches and you have to add `place - of_worship_unknown` to the selection to get a few more churches.
1. With the restriction to a fixed set of categories and subcategories only part of the POIs in a POI file can be seen in QMS (as an example: POI only with tags `name=..` and `shop=ticket` can't be found) .

**Describe the solution you'd like**

There is good search support for already existing GIS data types. A search for POIs would certainly be helpful to many QMS users.

The search could be for a substring in the `data` field of the `poi_data` table in the POI file. Examples: `name_ar=xx` or `cuisine=chicken`. The search result can be handled like the Geosearch result in the workspace. 

The search can find quite many POIs. Restrict the output to a fixed number of items or to those belonging to the area seen in the map window. Optional: add a possibility to show more found items.

**Describe alternatives you've considered**

* Add a category `All other POI` for all POIs in the POI file not belonging to one of the predefined categories. This proposal has a serious disadvantage: the number of POIs in this category can be extremely large. 
* Give the user the possibility to define his additional categories and subcategories.
* Add a tooltip to the category/subcategory field and display there the selection criterion used for this category/subcategory. (Example: it is not obvious what can be found in the categories `place` or `poi`)

**Give a reason why someone else should spend time on that request**

Implementation of a search mechanism would largely improve usage of POIs in QMS.

**Additional context**

None

**Comment by pingurus** [comment]
My first thought - I haven't tried it though - is that already should be possible with the current search. Copy over all POIs that might be of interest to you to a project and then use the full text filtering to filter for certain OSM tags. With a bit of regexing you might even search for tag combinations.

Of course this is not the most convenient way for the user, but I think it is no burden having to do it this way.

**Comment by wthaem** [comment]
Good proposal - but it fails in my case! And handling of your proposal requires a lot of steps: select all categories, select all POIs in some area, copy them into a project (it might be a lot of new waypoints!), find the few ones of interest, remove all others from workspace project.

With your proposal you can search only in the set of POIs having one of the categories/subcategories handled in QMS. And this is only a subset of all POIs in the POI file. My example with the ticket shop is just a real example of a POI in a file but not in QMS. So, my idea was to get access to all POIs in the file using an appropriate SQL query based on the search string.. The tricky thing is that the categories in the file are open-ended. You never can have all of them in a fixed list.

**Comment by pingurus** [comment]
We implement this together with #348
