### ISSUE TITLE
Show Garmin device in QMapShack workspace in MacOS

### ISSUE THREAD

**Issue by d029940** [Maproom/qmapshack#329]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Feature requests**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[X] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

If you want to have a list of all GPX-Files on the device, you must go manually (outside of QMapShack) to the mounted Garmin device , go to the correct folder (/Garmin/GPX) using MacOS finder. Also saving and loading of GPX files is easier, since one can stay in the QMapShack environment. Otherwise you need to use MacOS finder in addition.

**Describe the solution you'd like**

There already exists a solution for Windows and Linux. Just as a hint, attached devices will be mounted into the  /Volumes/ folder, e.g. my Garmin device is mounted as /Volumes/GARMIN
So maybe the solution for Linux needs slightly be updated in order to work for MacOS

**Describe alternatives you've considered**

Working in QMapShack AND MacOS-Finder.

**Give a reason why someone else should spend time on that request**

It's a convince function for all Mac users, so that they have the same comfort as Windows and Linux users.

**Additional context**

None

**Comment by kiozen** [comment]
On OS X device handling should work the same as on Windows or Linux. If it does not it's a bug and something is broken. Also make sure there is a valid `GarminDevice.xml` in the `Garmin` folder.

However as there is no active developer for OS X in the project you have to debug and fix it yourself. To start have a look into `CDeviceWatcherMac`.

**Comment by d029940** [comment]
Ok, now that I know, that the functionality exists, I digged around a little bit in the settings of the Mac.
With every version of MacOS, Apple increases its "security level and features".

To solve this problem the following steps are needed (attached screen shot):

1. Go into "System Preferences" -> "Security & Privacy".
2. Select tab "Privacy". Select on the left side "Files and Folders".
3. Look on the right side for QMapShack.app. (If it is not there, add it. It is probably stored under "/Applications/QMapShack/  folder (i.e. system wide) OR under the "Applications/QMapShack" folder in the user's home folder)
4. Tick the checkbox "Removable Volumes"

After that the Garmin device shows up in the workspace of QMapShack.

Can we put this information into the documentation?

On my Mac "Removable Volumes" was not selected.

As a side remark: Usually, when apps want to access "removable volumes", a (system) pop up appears to grant access.

![Screenshot 2021-02-06 at 15 53 18](https://user-images.githubusercontent.com/17231838/107121892-149a3b80-6895-11eb-9402-22f529b46446.png)

**Comment by kiozen** [comment]
Sure feel welcome to edit the Wiki. It's open for everyone.

**Comment by d029940** [comment]
Since, it is my first time to edit a Wiki, can you check that my additions are conform of any guide lines?

You can find my addition in the upper part of 
https://github.com/Maproom/qmapshack/wiki/DocGisDevices

**Comment by kiozen** [comment]
@wthaem can you please review

**Comment by wthaem** [comment]
Did it - it's well done.
