### ISSUE TITLE
Mouse range for POI tooltips too small

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#331]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Feature requests**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

The mouse range for tooltips is a bit too small. This implies that bundles of POIs are not recognized as bundles but as single POIs and it is difficult to get the tooltips for a single POI in the bundle.

**Describe the solution you'd like**

POI tooltips should behave like waypoint tooltips which have a bigger mouse range.

**Describe alternatives you've considered**

None

**Give a reason why someone else should spend time on that request**

Keep in mind that you ask others to spend their spare time for your request. Convince them
by giving a reason why solving your request has a benefit for them, too. Good reasons are
if you are able to prove

* The request solves a fundamental problem for everyone
* The request is of general interest for many users

Bad reasons are:
* Because software xyz does it
* Because you just want it to have that way
* Because it will solve a very particular problem.

**Additional context**

**Comment by kiozen** [comment]
Do we really need a ticket for that? And even one that is a bad example to others? Imho it would be sufficient to mention this on the ongoing PRs or development tickets.

**Comment by wthaem** [comment]
Right you are . I simply couldn't find the correct PR among the many active or closed PRs concerning POIs. And I didn't know, if a development ticket is the right place. Sorry.

**Comment by kiozen** [comment]
simply put that stuff to the active PR and let @pingurus decide to fix it asap or to create another dev ticket.
