### ISSUE TITLE
Fails to build with PROJ 8.0.0.

### ISSUE THREAD

**Issue by sebastic** [Maproom/qmapshack#333]
As initially reported in [Bitbucket Issue #438](https://bitbucket.org/maproom/qmapshack/issues/438), QMapShack needs to be ported to use `proj.h` because `proj_api.h` was deprecated in PROJ 6 and has now been removed in PROJ 8.

This prevents building QMapShack:
```
 CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
   Could NOT find PROJ4 (missing: PROJ4_INCLUDE_DIR)
 Call Stack (most recent call first):
   /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
   cmake/Modules/FindPROJ4.cmake:113 (find_package_handle_standard_args)
   CMakeLists.txt:170 (find_package)
```

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

**Comment by sebastic** [comment]
Filling out the template takes too much time, I have far too many upstreams to deal with, it's not worth my time.

If you're unwilling to fix this issue, we'll just remove the qmapshack package from Debian and Ubuntu, and I wish you luck supporting users of the package who will now have to build it themselves.

**Comment by demmm** [comment]
In case interested in a possible fix, here an example:
https://github.com/qgis/QGIS/commit/fc1ac8bef8dcc3194857ecd32519aca4867b4fa1

**Comment by sebastic** [comment]
That's just the first step, all the code that uses `proj_api.h` needs to be ported to use `proj.h`.

https://proj.org/development/migration.html

**Comment by landryb** [comment]
can this (real) issue please be reopened ? we (OpenBSD) are in the same situation, and we'll have to remove the qmapshack port/package when we update to proj 8 (soon).
