### ISSUE TITLE
Creation of an linear distance track not possible

### ISSUE THREAD

**Issue by BenediktO** [Maproom/qmapshack#336]
**Important Notice:**

**Do not delete any of the sections. Read what is requested. _Replace(!)_ the instructions by your _answer(!)_. Feature requests reports that are not properly filed might be closed without further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do you think someone else would understand what's fixed or done from your title? Does it really name the real topic of the issue?

**Is your feature request related to a problem? Please describe.**

In version 1.12.3 as in the official debian repositories and version 1.14 compiled myself I noticed that when using Create track a router is always used.

**Describe the solution you'd like**

I only want to create a track where the nodes are connected via airlines.
How can one achieve this?

**Describe alternatives you've considered**

I used the rules tool and tried to create such a track but the same problem occurs.

**Give a reason why someone else should spend time on that request**

It is sufficient to remove the Routing directory of Routino but this is a very bad solution.
It would be nice to be able to disable the router

**Additional context**

**Comment by kiozen** [comment]
It's already there. Simply use the toolbutton `O`. This will disable routing.

**Comment by kiozen** [comment]
see also 
https://github.com/Maproom/qmapshack/wiki/DocGisItemsEditMultiple#routing-options

**Comment by BenediktO** [comment]
thanks, sorry for the inconvenience
