### ISSUE TITLE
Upgrade to Proj 8 API

### ISSUE THREAD

**Issue by kiozen** [Maproom/qmapshack#337]
**Is your feature request related to a problem? Please describe.**

The old Proj API is discontinued with version 8 of the library. We need to upgrade. In the meanwhile porting is possible as all necessary functions are finally in the library. (from 7.1.0 on)

**Describe the solution you'd like**

This is the chance to hide the Proj mayhem in a class simplifying stuff. Features to implement are:

* initialization with different projections. Projections can change.
* testing for lat/long projections
* transform points and polylines (strictly use Qt types QPointF and QPolygonF)
* projection string validity check

**Describe alternatives you've considered**

n/a

**Give a reason why someone else should spend time on that request**

doing it on my own

**Additional context**

n/a

**Comment by pingurus** [comment]
I tried to update proj, but while make check returns no errors, QMS still fails compiling and `pkg-config --modversion proj` still returns `6.3.1`

@kiozen could you please update the wiki in case something changed except the version number?

**Comment by kiozen** [comment]
@pingurus did you make sure that the installation of Proj 8 did update the system wide cmake script to link against the new version.

**Comment by pingurus** [comment]
How can I check that?

**Comment by kiozen** [comment]
check the script in `/usr/lib/cmake...` or where ever your system is storing the stuff

**Comment by pingurus** [comment]
I'm still not able to compile, but through magic `pkg-config --modversion proj` now returns `8.0.0` and qt creator points me to the right file (proj.h where it is stated that this is version 8.0.0). What file exactly should I look for under `/usr/lib/cmake`? There are some folders with more files and even more references to proj4 in there. I'm on Ubuntu 20.04 if that helps.

Shouldn't the following section in `CMakeLists.txt` be updated?
```
if(${PROJ4_VERSION} VERSION_LESS 5.0.0)
    message( SEND_ERROR "You need at least PROJ4 5.0.0 or newer.")
endif()
```

**Comment by pingurus** [comment]
Somehow I managed to build now, I did
```
sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
sudo apt-get update
sudo apt upgrade
```
and some reinstallations of `libproj-dev`, `proj-bin` and `proj-data`. I doubt that my packages are in a clean state, but it works for now.
