### ISSUE TITLE
Map View shows gray bars on the sides

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#340]
**Important Notice:**

**Do not delete any of the sections. Read what is requested. _Replace(!)_ the instructions by your _answer(!)_. Bug reports that are not properly filed might be closed without further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do you think someone else would understand what's fixed or done from your title? Does it really name the real topic of the issue?

**Describe the bug**

(See screenshot)
There are gray bars (might be different dependent on your background) on the side of the map view, which are persistent when you move the map.

**What have you done to circle down the problem?**

There are at least two easy ways to fix the problem:
* restart QMS
* resize the QMS window

**To Reproduce**

1. have docks (e.g. POIs, Maps, Workspace) on both sides of the window
2. Move docks from one side to the other, so now they are only on one side
3. See the gray bars (might be different dependent on your background)

**Expected behavior**

The map view should detect on its own that it has more place to draw.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/36167579/111062196-c4bc1f00-84a7-11eb-9805-d44889819d37.png)

**Attachments**

Can you provide an example file to trigger the problem? No file needed.

**Tracebacks**
QMS does not crash, so there is no traceback and the debug output doesn't show anything suspicious either

**Desktop (please complete the following information):**

* OS: Ubuntu 20.04
* QMapShack Version: latest feature/pois (3753ec98 [QMS-314] Fix/Add POI categories)
* Window Manager GNOME

**Additional context**

I doubt it, but it could be related to #337 or how I updated to the new proj

**Comment by kiozen** [comment]
I can't reproduce.

**Comment by kiozen** [comment]
I still can't reproduce. Even with PR #335. I think it must be something with your system.

**Comment by pingurus** [comment]
I'll close this issue then, since it is neither a frequent nor an annoying bug :smile:
