### ISSUE TITLE
Better integration of new PROJ lib into cmake build system

### ISSUE THREAD

**Issue by kiozen** [Maproom/qmapshack#344]
**Is your feature request related to a problem? Please describe.**

The CMakeLists.txt is still using the old  PROJ4 scripts. They will be dropped at some point.

**Describe the solution you'd like**

Update the scripts to new PROJ cmake files and update the version check.

**Describe alternatives you've considered**

n/a

**Give a reason why someone else should spend time on that request**

I do it myself.

**Additional context**

n/a

**Comment by pingurus** [comment]
Sorry to say, but you missed the `FindPROJ4.patch` file in your renamings. Renaming the included file to `FindPROJ.cmake` and replacing all `PROJ4` by `PROJ` fixes the remaining cmake errors.

**Comment by kiozen** [comment]
This patch is dead since end of 2020. Your distribution should add a proper find script for cmake by now. If not it's a distribution's bug. 

Additionally the CMakeLists.txt checks for proper PROJ version, now. This will not work with a patch.

**Comment by kiozen** [comment]
Ok, I removed the patched to avoid confusion. And I fixed a problem with older proj strings. See PR #346.

@pingurus and @wthaem please cross check.
