### ISSUE TITLE
Crash when opening the projection wizzarrd

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#347]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Describe the bug**

QMS crashes when trying to use the projection wizzard

**What have you done to circle down the problem?**

Bug appeared after compiling QMS with proj version 8. It didn't occur with earlier QMS version using earlier proj versions.

**To Reproduce**

1. Goto menu `View - Setup Map view`
2. Find the button to the right of the edit field showing a grid and press this button (kiozen: yes, the button you marked) 
3. QMS crashes
4. **Or:** Goto menu `View - Setup grid`
5. The third button shows again a grid. Pressing this button crashes QMS, too.

**Expected behavior**

QMS shouldn't crash

**Screenshots**

None

**Attachments**

None

**Tracebacks**

```
 	Qt5Core.dll!00007ff8caf81313()	Unknown
 	qmapshack_RelDbg.exe!CProjWizard::CProjWizard(QLineEdit & line) Line 52	C++
>	qmapshack_RelDbg.exe!CCanvasSetup::slotProjWizard() Line 52	C++
 	qmapshack_RelDbg.exe!QtPrivate::QSlotObject<void (__cdecl CCanvasSetup::*)(void),QtPrivate::List<>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 418	C++
 	[External Code]	
 	qmapshack_RelDbg.exe!CCanvas::setup() Line 1142	C++
 	qmapshack_RelDbg.exe!CMainWindow::slotSetupMapView() Line 1331	C++
 	qmapshack_RelDbg.exe!QtPrivate::QSlotObject<void (__cdecl CMainWindow::*)(void),QtPrivate::List<>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 418	C++
 	[External Code]	
 	qmapshack_RelDbg.exe!main(int argc, char * * argv) Line 83	C++
 	[External Code]	
```

**Desktop (please complete the following information):**

 - Windows 10
 - proj 8.1.0, gdal 3.2.2
 - QMapShack Version:
 
 ```
 commit dfbacf7c292c10d847c0062f4620364ad30581d7 (HEAD -> QMS-313, origin/QMS-313)
Author: Henri Hornburg <pingurus@t-online.de>
Date:   Sun Mar 14 15:53:20 2021 +0100
```

**Additional context**

**Comment by kiozen** [comment]
Already addressed in PR #344, please test.
