### ISSUE TITLE
How to search address without internet?

### ISSUE THREAD

**Issue by asakura42** [Maproom/qmapshack#348]
**Important Notice:**

**Do not delete any of the sections. Read what is requested. _Replace(!)_ the instructions by your _answer(!)_. Feature requests reports that are not properly filed might be closed without further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do you think someone else would understand what's fixed or done from your title? Does it really name the real topic of the issue?

**Is your feature request related to a problem? Please describe.**

I would love to search address offline because I don't have Internet all the time. Osmand, for example, has it. And it is very convenient. Even the simplest coordinate, street or city search would already be a significant deal to not to search Wi-Fi spots in the middle of Vietnam, Sakhara Desert or Russian villages. While electricity I can found in many places, Wi-Fi still exists in cities only.

**Describe the solution you'd like**

I'd like some bar where I just could type something stupid like name of town or street or even coordinates. While maps contains this info it may be easy to find.

**Describe alternatives you've considered**

Maybe some point parser that loads database with all the point from map. I don't really know how it should work inside.

**Give a reason why someone else should spend time on that request**

The thing is internet.  Nominatim is cool, but offline search is killer-feature. It will make qmapshack really useful in cities where you just need to fast check where is, for example, that street with your motel.

**Additional context**

**Comment by asakura42** [comment]
Also didn't find how to find even coordinates.

**Comment by pingurus** [comment]
Could you please do the feature request as it is requested? It makes life easier for everyone. If you don't improve it, @kiozen will close this issue and you most likely won't get your feature anytime soon.

And regarding your request: If you can code you get it by doing it yourself, if you can't code please provide us with the most details you can give us, since we are doing this in our spare time. You could for example start looking on _how_ Osmand does it and then tell us. Also you could look up how the locus maps poi files work, as I think they also have addresses included. And of course you could tell us how you would like this search to be included in the UI, so we have an easier starting point there.

**Comment by asakura42** [comment]
Sorry @pingurus, I thought it was implemented and I just don't see it. I'll fix issue in a couple hours.

**Comment by kiozen** [comment]
Thanks for using the template now. But I agree with @pingurus. You are just requesting something without giving any details or doing any pre-work. By that the complete workload it shoved over to the one picking the item. I doubt anyone will if not really in need of such a feature him/herself.

Concerning offline search:

* You always need an offline database. Without a good source the feature does not make much sense. A good source might be OSM. 
* The raw OSM database is huge. Probably too large to copy it over and over again. And it contains more information than we need. Therefor you need some mechanism to reduce the raw data into data needed.
* Again raw databases are huge and not really optimized for size or speed of search. To perform a search in reasonable speed you have to index the data for a search. 
* Format. Creating your own vs using what's already there. If you create your own, you can optimize for your need but you have to provide tools and bandwidth to  create databases or to provide ready made databases. If you use what's already there it might not be optimal and sometimes it's in a very proprietary format (e.g. Garmin maps)

All this has to be clarified, before anyone will start to write a single line of code. But maybe you are lucky and someone will pick up the topic within the next 6 months.

**Comment by asakura42** [comment]
@kiozen
I don't know C++ so I wrote simple shell script to get location from address. At end I get lat and lon which enter as new position when adding waypoint. Not super convenient, but it works. https://github.com/asakura42/maptools/blob/main/addr2loc.sh

**Comment by kiozen** [comment]
As there is no progress since have a year I close the ticket for now.
