### ISSUE TITLE
Remove links to non-existing elevation data from dds.cr.usgs.gov

### ISSUE THREAD

**Issue by eugeneandrienko** [Maproom/qmapshack#356]
**Important Notice:**

**Do not delete any of the sections. Read what is requested. _Replace(!)_ the instructions by your _answer(!)_. Bug reports that are not properly filed might be closed without further notice.**

**Choose a good title**

Remove links to non-existing elevation data from dds.cr.usgs.gov

**Describe the bug**

There are links to https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/ in qmapshack's wiki, which are recommended to load tiles with elevation data. These links are all broken — the server returns 404 error instead of list of tiles.
I registered in usgs.gov site and not found any free elevation data in hgt format. In their Earth Explorer I found only elevation data from Space Shuttle missions in TIFF format and loading of that data is not automatic — you should manually select a polygon on the Earth and data source and after that you could download TIFF files.

Looks like the only one source of hgt files is http://www.viewfinderpanoramas.org site.

I think, links to dds.cr.usgs.gov should be removed from our wiki.

List of pages with invalid links to https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/ :

- https://github.com/Maproom/qmapshack/wiki/AdvSetup#download-and-install
- https://github.com/Maproom/qmapshack/wiki/DocMapDemSources
- https://github.com/Maproom/qmapshack/wiki/DocQuickStartEnglish
- https://github.com/Maproom/qmapshack/wiki/DocQuickStartGerman
- https://github.com/Maproom/qmapshack/wiki/DocQuickStartRussian
- https://github.com/Maproom/qmapshack/wiki/DocQuickStartFrench

**What have you done to circle down the problem?**

Did you compare to previous versions? What versions? Did you check
if others have the same problem?

**To Reproduce**

1. Go to wiki-page: https://github.com/Maproom/qmapshack/wiki/DocQuickStartEnglish
2. Click on 'Load tiles with elevation data.' link.
3. See error

**Expected behavior**

Broken links to https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/ should be removed from wiki-pages.

**Screenshots**

![2021-03-22-143955_1920x959_scrot](https://user-images.githubusercontent.com/18009436/111985194-5d444600-8b1d-11eb-990f-74cbc8f9c68b.png)

**Attachments**

Can you provide an example file to trigger the problem?

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: Gentoo
 - QMapShack Version: 1.15.2
 - Window Manager: i3

**Additional context**

I can remove these links myself, if I have enough rights to edit qmapshack's wiki (doesn't check this yet).

**Comment by wthaem** [comment]
There are even more dead links in the Wiki (status 404,503,..., e.g.: https://geoservices.ign.fr/documentation/ressources.html, https://pkgs.org/download/qmapshack, ...). Not sure, if we should keep or remove them.

**Comment by kiozen** [comment]
Everything that is dead and has no replacement should be removed. Everything that can be replaced by a new URL should be fixed.

**Comment by wthaem** [comment]
My opinion, too. I did this for quite a few links. But there are others, where the original author must make the change. Example: the links to French servers (appear also in TMS/WMTS/WMS discussion): some of them don't work anymore due to changes on the servers. A change of the link implies quite some changes in the accompanying text (how to get a login to the server) based on special knowledge (wrt to the USGS DEM data: I'm not aware if there is a possibility to access this data elsewhere or via some login). I know some broken links but I don't know the author and even if I know him I don't know how to contact him. 

My summary: The remaining broken links in the Wiki can only be updated by their authors.

**Comment by kiozen** [comment]
I guess we can close the ticket, can't we?

**Comment by eugeneandrienko** [comment]
I guess what we can close it, too.
Let the author(s) to edit those articles with broken links.
