### ISSUE TITLE
Crash when zooming/moving a map

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#357]
**Important Notice:**

**Do not delete any of the sections. Read what is requested. _Replace(!)_ the instructions by your _answer(!)_. Bug reports that are not properly filed might be closed without further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do you think someone else would understand what's fixed or done from your title? Does it really name the real topic of the issue?

**Describe the bug**

Sometimes QMS crashes when zoooming and/or moving the map while a previous zoom/move has not yet finished. It happens, that an active online map is not redrawn, only partially redrawn or only after some operation with the map.

**What have you done to circle down the problem?**

There is no rule that can describe the circumstances of the crash. It happens quite often with the normal QMS version and less frequently with the RelWithDbg version.

**To Reproduce**

1. Zoom and move (online?) map rapidly in a wide range. Maybe, the number of visible POIs may be involved.

**Expected behavior**

No crash should happen

**Screenshots**

**Attachments**

Can you provide an example file to trigger the problem?

**Tracebacks**

```
 	proj_8_0.dll!00007ff9f5370ca8()	Unknown
 	proj_8_0.dll!00007ff9f536d0c6()	Unknown
 	proj_8_0.dll!00007ff9f535f7ba()	Unknown
 	proj_8_0.dll!00007ff9f536fba5()	Unknown
 	proj_8_0.dll!00007ff9f536d0c6()	Unknown
 	proj_8_0.dll!00007ff9f535f7ba()	Unknown
>	qmapshack_GPX_Dbg.exe!CProj::_transform(double & lon, double & lat, PJ_DIRECTION dir) Line 170	C++
 	qmapshack_GPX_Dbg.exe!CProj::transform(QPointF & pt, PJ_DIRECTION dir) Line 139	C++
 	qmapshack_GPX_Dbg.exe!IDrawContext::convertRad2M(QPointF & p) Line 241	C++
 	qmapshack_GPX_Dbg.exe!IDrawContext::draw(QPainter & p, CCanvas::redraw_e needsRedraw, const QPointF & f) Line 381	C++
 	qmapshack_GPX_Dbg.exe!CCanvas::paintEvent(QPaintEvent * __formal) Line 614	C++
 	[External Code]	
 	qmapshack_GPX_Dbg.exe!CCanvas::event(QEvent * event) Line 1376	C++
 	[External Code]	
 	qmapshack_GPX_Dbg.exe!main(int argc, char * * argv) Line 83	C++
 	[External Code]	
```
There is also the following informatuion:

```
Stop at Exception: proj_x.cpp line 170:

170:  c = proj_trans(_pj, dir, c);
```

**Desktop (please complete the following information):**

 - OS: Windows 10
 - QMapShack with proj 8.0.0:
 
```
commit b41eb361bdf011b4e140e69852068f7ebd88d118 (HEAD -> QMS-342, origin/QMS-342)
Author: Henri Hornburg <pingurus@t-online.de>
Date:   Sun Mar 21 08:57:28 2021 +0100

    [QMS-342] Read GPX files as POIs

    * Added possibility to read GPX files as POIs
```

Other recent versions behave in the same way.

**Additional context**

**Comment by pingurus** [comment]
I can't reproduce this crash with current #341 (And I've been spinning my mousewheel very quickly :laughing: )

**Comment by frankystone** [comment]
I had this crash also, but in previous versions. Current version 1.16.1 (and some versions prior) does not crash an map moving anymore.

I think this bug can be closed?

**Comment by kiozen** [comment]
As there is no progress since have a year I close the ticket for now.
