### ISSUE TITLE
Fix compile flags for Windows 64bit

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#360]
**Important Notice:**

**Do not delete any of the sections. Read what is requested. _Replace(!)_ the instructions by your _answer(!)_. Bug reports that are not properly filed might be closed without further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do you think someone else would understand what's fixed or done from your title? Does it really name the real topic of the issue?

**Describe the bug**

Compiling the Windows dev version fails with an error

**What have you done to circle down the problem?**

Some earlier commits with PROJ version 8 could be compiled without errors.

Here is some relevant information:

* Used commit:

```
git log -1
commit a68c771a346ae3cbe65233044a9c2648a620936b (HEAD -> dev, origin/dev, origin/HEAD)
Author: kiozen <oliver.eichler@gmx.de>
Date:   Sat Mar 27 10:59:16 2021 +0100

    Update language files
```

* Build environment (run from command line):

```
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.28.29912.0
-- The CXX compiler identification is MSVC 19.28.29912.0
```

* Error message:

```
  CMainWindow.cpp
D:\QtProjects\QMS\QMapShack\src\qmapshack\CMainWindow.cpp(1782,1): error C2509: "nativeEvent": Memberfunktion wurde in
"CMainWindow" nicht deklariert [D:\QtProjects\QMS\QMapShack\Build\src\qmapshack\qmapshack.vcxproj]
D:\QtProjects\QMS\QMapShack\src\qmapshack\helpers/CWptIconDialog.h(28): message : Siehe Deklaration von "CMainWindow" [
D:\QtProjects\QMS\QMapShack\Build\src\qmapshack\qmapshack.vcxproj]    
```

* One remaining warning:

```
 CMapJNX.cpp
D:\QtProjects\QMS\QMapShack\src\qmapshack\map/CMapJNX.h(58,9): warning C4086: Pragma-Parameter "1", "2", "4", "8" oder
"16" erwartet [D:\QtProjects\QMS\QMapShack\Build\src\qmapshack\qmapshack.vcxproj]
D:\QtProjects\QMS\QMapShack\src\qmapshack\map\CMapJNX.cpp(22,1): warning C4103: Die Ausrichtung wurde nach dem Einschli
eßen des Headers geändert, möglicherweise fehlt "#pragma pack(pop)". [D:\QtProjects\QMS\QMapShack\Build\src\qmapshack\q
mapshack.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(2496,40): error C2338: Windows headers require t
he default packing option. Changing this can lead to memory corruption. This diagnostic can be disabled by building wit
h WINDOWS_IGNORE_PACKING_MISMATCH defined. [D:\QtProjects\QMS\QMapShack\Build\src\qmapshack\qmapshack.vcxproj]    
```

Can my compiler environment settings be the cause of the error?

**To Reproduce**

Repeat compiler run

**Expected behavior**

No errors during compilation
**Screenshots**

**Attachments**

Can you provide an example file to trigger the problem?

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: Windows 10
 - QMapShack Version: see above 
 - Proj 8.0.0
 - GDAL 3.2.2
 - Qt 5.15.2
 

**Additional context**

None

**Comment by kiozen** [comment]
Try to change line 1762 in file CMainWindow.cpp from 

```
#ifdef WIN32
```
to:

```
#ifdef Q_OS_WIN64
```

And you have to do this probably in several locations, too.

**Comment by wthaem** [comment]
Error message from CMainWindow.cpp unchanged. Must I set somewhere Q_OS_WIN64?

**Comment by wthaem** [comment]
Success with compilation after adding your changes to header files, too.

Changed files:

CMainWindow.cpp/.h
CMapImg.cpp/.h
CMapJNX.h
