### ISSUE TITLE
GIS items missing in projects loaded from file or database

### ISSUE THREAD

**Issue by kiozen** [Maproom/qmapshack#363]
**Describe the bug**

Lately no GIS items are listed when loading a project from file or database. However restarting QMapShack with the empty project in the workspace restores the project with all items.

**What have you done to circle down the problem?**

I checked older commits to circle down the problem. No change. Therefore I suspect the problem to be some kind of interaction with newer Qt versions. 

Next I checked with gdb `void CGisWorkspace::loadGisProject(const QString& filename)`. After some time I realized that the GIS Items are loaded and attached to the project's QTreeWidgetItem properly. They are just hidden because of  `item->setWorkspaceFilter(currentSearch);`.

Somehow the initial filter is suppressing all items. Commenting the line solves the problem, but will break filtering.

**To Reproduce**

1. Load GPX into the workspace -> project is listed without GIS items as children
2. Restart QMapshack -> project is listed with children

**Expected behavior**

All projects loaded into the workspace must list all of their GIS items

**Screenshots**

n/a

**Attachments**

n/a

**Tracebacks**

n/a

**Desktop (please complete the following information):**

 - OS: SuSE Leap 15.2
 - QMapShack Version 1.15.2
 - Window Manager: KDE
 - Qt Version 5.15.7

**Additional context**

n/a

**Comment by kiozen** [comment]
@pingurus Can you test and confirm. Maybe you have an idea what's wrong.

**Comment by wthaem** [comment]
Can't confirm this for Windows 10, Qt 5.15.2 and

```
commit d1d98ffe365530f5a16bb86b114f8731dbed13d7 (HEAD -> dev, origin/dev, origin/HEAD)
Author: kiozen <oliver.eichler@gmx.de>
Date:   Thu Apr 8 19:13:51 2021 +0200

    [QMS-360] Fix compile flags for Windows 64bit
```

After opening a GPX file I can see the track inside the file/project. Also starting from the command-line with the GPX file as parameter works as expected.

**Comment by kkarsten62** [comment]
- Can't confirm this for openSUSE 15.2 with Qt 5.12.7 and Fedora 33 with Qt 5.15.2.
- No selfcompiled Qt
- Both tests are based on new installation of OS and QMS
- Latest commit used (same as  wthaem  did for Windows)

**Comment by tormet** [comment]
With Ubuntu 20.04.2 and the developer (Debug and RelWithDebInfo) version I also cannot confirm this. Everything works as expected.

**Comment by kiozen** [comment]
@pingurus it's because of missing default initialization in struct search_t

```
    struct search_t
    {
        searchProperty_e property;
        search_type_e searchType;
        searchValue_t searchValue;
    };
```

I would set it to:

```
    struct search_t
    {
        searchProperty_e property = eSearchPropertyNoMatch;
        search_type_e searchType = eSearchTypeNone;
        searchValue_t searchValue;
    };
```
and create a PR. Could you please confirm that the fix is ok.
