### ISSUE TITLE
Don't activate all layers of online WMS/WMTS maps

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#369]
**Important Notice:**

**Do not delete any of the sections. Read what is requested. _Replace(!)_ the instructions by your _answer(!)_. Feature requests reports that are not properly filed might be closed without further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do you think someone else would understand what's fixed or done from your title? Does it really name the real topic of the issue?

**Is your feature request related to a problem? Please describe.**

Online WMS/WMTS may have a considerable number of layers. When activating one of these maps, all layers are automatically activated, too. This can lead to a tremendous number of tiles to be downloaded. It can't be expected that a user might be interested in the overlay of several hundreds of layers. During the download process the user can de-activate layers manually. This is almost impossible with several hundreds of layers.

**Describe the solution you'd like**

When loading an online map for the first time either 

* don't activate layers at all **or**
* activate only a few of them **or**
* give the user a possibility to interrupt the loading of tiles while saving the downloaded tiles (tiles removed from the map when de-activating a WMTS file)

**Describe alternatives you've considered**

None

**Give a reason why someone else should spend time on that request**

Increase of user-friendliness of GUI- and data handling

**Additional context**

1. Download the WMTS capabilities file from https://wmts.geo.admin.ch/EPSG/3857/1.0.0/WMTSCapabilities.xml
1. Start QMS and adjust the map window so that the whole of Switzerland can be seen.
1. Activate the WMTS file
1. Follow the number of tiles to be downloaded
1. Look at the number of activated layers

In my case QMS crashed before all tiles could be downloaded. In the tile cache there are at the moment of the crash ~8800 tiles downloaded within 12 minutes.

**Comment by kiozen** [comment]
As there is no progress since have a year I close the ticket for now.
