### ISSUE TITLE
Mapsforge Maps Wrapper script does not tile

### ISSUE THREAD

**Issue by wowotiel** [Maproom/qmapshack#370]
See https://github.com/Maproom/qmapshack/wiki/DocBasicsMapDem#mapsforge-maps
I have managed to use maps from openandro.org within QMapshack (Version
1.15.2; Qt 5.12.8; GDAL 3.2.2; Proj4 Rel. 8.0.0; Routino 3.3.3).
This only works with the .cmd file:

java -jar MapsforgeSrv.jar -m \path\to\map -t \path\to\stylepause

The Openandromap that I use does does work with the comman
./mapsforce.cmd that I have created. OS is Ubuntu 20.04.

When I use the wrapperscript *"Mapsforge_for_QMapShack.tcl" *the
wrapper GUI is started but when I actived the openandrmap the map does
not tile (I see a running wheel but there is no map created).

Is there also a debug mode for Linux wrapper script, so I can find out
what is wrong?

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

**Comment by JFritzle** [comment]
Have a look at wrapper script's repository https://github.com/JFritzle/Mapsforge-for-QMapShack
