### ISSUE TITLE
Refine templates to hide comments

### ISSUE THREAD

**Issue by mitxel-m** [Maproom/qmapshack#373]
### Is your feature request related to a problem? Please describe.
[comment]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] )

The issues templates contain comments and instructions on how to fill them in. These comments can be edited or deleted by the user to prevent them being displayed in the request, however this is not always the case and sometimes the result is a difficult to read mix.

### Describe the solution you'd like
[comment]: # (A clear and concise description of what you want to happen.)

- Wrap the instructions with comment tags, (HTML, Markdown) so that they appear in the template, but are not displayed in the output.
- Use markdown heading marks `###` for each section instead of bold, to make the template clearer for the user.

### Describe alternatives you've considered
[comment]: # (A clear and concise description of any alternative solutions or features you've considered.)

None

### Give a reason why someone else should spend time on that request
[comment]: # (Keep in mind that you ask others to spend their spare time for your request. Good reasons are if you are able to prove that the request solves a fundamental problem for everyone, or the request is of general interest for many users. Bad reasons are you just want it to have that way, or argue that software xyz does it.)

I expect it will make things easier for everyone, and I will do a PR with refined templates

### Additional context
[comment]: # (Add any other context or screenshots about the feature request here.)

This request has been filled with such a template

**Comment by kiozen** [comment]
This is brilliant. I always wondered how to solve that but couldn't see the obvious! Many thanks!
