### ISSUE TITLE
on-screen profile window has no close button

### ISSUE THREAD

**Issue by WIsbrecht** [Maproom/qmapshack#375]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
When I click on "show on-screen profile" it used to open a new window with the elevation profile of a track.
Now a new window opens but in my Kubuntu 21.04 (KDE) it doesn't show up as a separate window in the KDE task manager anymore. Also there is no close button, only a maximize button.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
I cloned the newest Qmapshack from github (ce0a7e5a).
Followed the new PROJ8 instructions (https://github.com/Maproom/qmapshack/wiki/BuildUbuntuPROJ8)
Compiled and installed everything.
Still no close button.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Double-Click on a track in the Workspace
2. A new window with the elevation profile opens
3. The new window has no close button and doesn't show up as a separate window in the KDE Task-manager

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)
The "show on-screen profile" used to have a close button

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)
![Screenshot_20210504_130559](https://user-images.githubusercontent.com/939173/116998122-0a45dd00-acde-11eb-902c-10f3c9846268.jpeg)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: Kubuntu 21.04
 - QMapShack Version:   git ce0a7e5a
 - Window Manager:  KDE 5.21.4; Qt 5.15.2

### Additional context
[comment]: # (Add any other context about the problem here)
The close button disappeared after I upgraded Kubuntu from 20.10 to 21.04 and was forced to recompile Qmapshack.

**Comment by kiozen** [comment]
I can not reproduce it. But doesn't mean anything if it comes to window decorations. You might try to change the code in IPlot.cpp line 91 
```
    if(mode == eModeWindow)
    {
        overrideWindowFlags(Qt::Tool);
        setAttribute(Qt::WA_DeleteOnClose, true);
```
Not sure why there is `overrideWindowFlags`. `setWindowFlags(Qt::Tool);` should be the better choice. And you can try different flags.  See https://doc.qt.io/qt-5/qt.html#WindowType-enum for other options.

**Comment by WIsbrecht** [comment]
Hey,

I changed overrideWindowFlags to setWindowFlags and it did the trick. Thank you!
The documentation for QWidget::overrideWindowFlags says:
"Warning: Do not call this function unless you really know what you're doing."

- Waldemar

**Comment by kiozen** [comment]
Obviously someone didn't knew what he was doing :blush: I will commit a fix. Thanks for testing.
