### ISSUE TITLE
MacOS m1 arm chip support request.

### ISSUE THREAD

**Issue by d0u9** [Maproom/qmapshack#377]
### Is your feature request related to a problem? Please describe.
No.

### Describe the solution you'd like
New apple's m1 chip support.

### Describe alternatives you've considered
No.

### Give a reason why someone else should spend time on that request
The brand new m1 chip will be the most popular in subsequent Macbook production line.

### Additional context
No.

**Comment by cvigo** [comment]
does not look good
 #458

**Comment by kiozen** [comment]
As there is no progress since have a year I close the ticket for now.
