### ISSUE TITLE
Toggle fullscreen does not work

### ISSUE THREAD

**Issue by kiozen** [Maproom/qmapshack#380]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

Toggling back and forth between maximized window and fullscreen results in a non-maximzed window when not in fullscreen mode.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

It's a problem how the code treats windowState(). Refere to Qt docs for details on how to do it properly.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Start QMapShack maximized
2. Toggle fullscreen (F11) -> fullscreen
3. Toggle fullscreen (F11) -> window is of any size but not maximized

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

Properly toggle between fullscreen and maximized screen

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

n/a

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

n/a

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

n/a

### Desktop
[comment]: # (please complete the following information)

 - OS: Suse 15.2
 - QMapShack Version:  1.15.2
 - Window Manager: KDE
- Qt 5.12.7

### Additional context
[comment]: # (Add any other context about the problem here)

n/a

**Comment by wthaem** [comment]
> window is of any size but not maximized:

Doesn't hold true under my Windows 10 - neither before nor after #QMS-380. Here, everything is fine.

**Comment by kiozen** [comment]
This is more a problem of Linux, latest Qt version and KDE
