### ISSUE TITLE
Enhancing activity system

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#39]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have more activities to choose from to label my tracks with.
There has been some talk back on [Bitbucket](https://bitbucket.org/maproom/qmapshack/pull-requests/265/add-new-activities/diff).

@kiozen could you please describe what your thoughts were when refactoring the code "quite some time ago", so we know what we can build on?

Can others interested in this please draft their wishes regarding the new activity system, so we can find a solution that is the most useful?

I think it might be good if the user could add activities by himself. They would then inherit the symbol of their parent activity. For this to be possible, they would not be allowed to add a new category, only subcategories. Or, in order to better be able to differentiate by icons, the sub categories could be fixed also and the user only adds the sub-sub categories. This would look something like this:
- Bicycle
    - City
        - UserDefined1
    - Trekking
    - Road
    - MTB
        - UserDefined2
        - UserDefined3

However, this would have the drawback, as @mitxel_m already said back on bitbucket (although in a slightly different context), that one can't differentiate the user defined activities.

Last but not least, we'd need someone to draw the icons, as I'm not good at that.

**Comment by kiozen** [comment]
I think user defined activities are too much overhead for a very rare use case. And it will break the interchangeability of data between users on another level than just different versions of QMapShack.

What where my thought on that:

* This has to be backward compatible with reading older tracks. 
  - Very old tracks have the activities coded as flags. The current code converts these flags into  enumeration values.
* This won't be backward compatible when reading a newer track with an older version of QMapShack
  - The binary *.qmb format is not backward compatible. A design flaw we have to live with.
  - Older versions of QMapShack won't be able to interpret the new values.

Using a number delta of 100 between each activity is a vague idea of having categories and sub-activities. That would make the current activities ambivalent. E.g.  _Foot_ will be the activity used by old tracks and also open up a category with all kinds of walking activities. This is a quite shitty concept you get when you decide things on-the-fly without the patience and time to develop a real concept. But it happens.

The activity menu is generated automatically, see `CActivityTrk::getMenu`. This has to be enhanced. I tried once and realized it's not that easy than I expected it to be. The vector list `CActivityTrk::actDescriptor` has to be analysed. If there is an activity with a multiple of 100 and no sub-activities, the menu entry is just an action. If there are sub-activities the entry is a sub-menu with the name of the base activity (category). And this base activity has to be the first entry in the submenu, too. 

These are the rough ideas. But as long as no one starts to define a list of activities and sub-activities **including** a real existing icon set I wouldn't like to start with that topic. We already have quite some weird  code on that topic. I don't want to produce more of that by going on to code into the blue.

**Comment by mitxel-m** [comment]
First of all ( but not most important) I can help with icons.  ;-)

I also agree that any list of activities and subactivities that you imagine will not please most users.

That's why I think a list of activities should be approached with this idea:
  
**What do you use this for?**

In my case:
- to create summaries.
- to better visualize the sections and difficulties of a route, both in the map and in the graph. 

Just as is shown here:

https://bitbucket.org/repo/L5qerE/images/1433945544-Anboto-MTB2.jpg

So I need a list where subactivities say something about the terrain or the difficulties.

In the past I creted [some icons for MTB](https://bitbucket.org/mitxel_/qmapshack/commits/8c37613ac7b8d01e759c5e2d19a19c49d1bc7c11) following that idea. I can create other ones for walking and running in the same way.

**Comment by kiozen** [comment]
Let's collect stuff:

https://github.com/Maproom/qmapshack/wiki/DocActivityPlanning

Simply add your ideas and suggestions for activities.

**Comment by pingurus** [comment]
@kiozen What do you think of renaming `train` to `public transport`, so we can put `bus` into the same category?

How can we fit the idea of @mitxel-m into the concept of listing all the different activities? Auto generate the surfaces and the corresponding symbols for each activity? By that I mean one could just suffix the surface into the name and overlay the activity symbol with the surface symbol. However there still would have to be a decision for which activities this makes sense.

**Comment by kiozen** [comment]
> @kiozen What do you think of renaming `train` to `public transport`, so we can put `bus` into the same category?

good point :+1: 

> How can we fit the idea of @mitxel-m into the concept of listing all the different activities? Auto generate the surfaces and the corresponding symbols for each activity? By that I mean one could just suffix the surface into the name and overlay the activity symbol with the surface symbol. However there still would have to be a decision for which activities this makes sense.

Imho this has to be hard coded. It won't be that bad because as far as I am concerned it's only for `foot` and `cycle`.

**Comment by pingurus** [comment]
> Imho this has to be hard coded. It won't be that bad because as far as I am concerned it's only for foot and cycle.

Would you then add it to the foot and cycle sub-activities (aka as a sub-sub-activity) or as an own sub-activity?

**Comment by kiozen** [comment]
Well there will be activities like `mountain bike grade 1` or `hiking grade 1` Maybe @mitxel-m has a good idea fore the correct wording.

**Comment by mitxel-m** [comment]
Added some proposals for hiking and running at  the wiki page.
See remarks and references below the list

( ...now cooking MTB)

;-)

**Comment by pingurus** [comment]
> ( ...now cooking MTB)
Maybe you could base it on the [STS](http://www.singletrail-skala.de/overview), which is also used in OSM.
However most users (me included) would probably only use 0-2, maybe 3.

**Comment by pingurus** [comment]
> The activity menu is generated automatically, see CActivityTrk::getMenu. This has to be enhanced. I tried once and realized it's not that easy than I expected it to be.

Is this the only critical point from coding perspective?

**Comment by pingurus** [comment]
> If there is an activity with a multiple of 100 and no sub-activities, the menu entry is just an action. If there are sub-activities the entry is a sub-menu with the name of the base activity (category). And this base activity has to be the first entry in the submenu, too.

I would say that sub-activities have to be a multiple of 10 and the sub-sub activities fill the remaining void, since that is the consequent application of the idea.

However, we then nearly hit the limit with the activities we've already found (ship is at 8 sub-activities, maximum would be 9)

Isn't there a qt tree class, from which a menu can be automatically created and which we can subclass to put all the other activity related infos into? Yes, that would require a hard rework of the complete activity system including all references to it, but we would get rid of this limit due to the id's.
But before rewriting the code we should find out what is exactly expected from the activity system besides the  activities which we started listing in the wiki.

Some points that are implemented:
* provide all available activities with icons, descriptions etc.
* provide activity ranges in the track
* provide summaries for activities

Some points that come to my mind:
* providing the default velocity filter for the activity (in whatever form that will be) to be able to apply filters activitywise throughout the track

These seam to be two different goals:
1. track specific (summaries, etc)
2. global (providing all activities and if it is approved and implemented some time the velocity filters)
As a consequence this should maybe be split up into a class providing the activities and some form of identifier for them and the current class whose instance would then be specific to a single track.

I'm sorry if this is maybe a bit unclear, it was kind of a stream of conciousness writing :smile:
Both remarks from @kiozen for the coding side and from @mitxel-m for the wanted features side are appreciated!

**Comment by kiozen** [comment]
`actDescriptor` should contain all data concerning activities. And it should be the base to derive the stacked menu. It's no problem to add other members to `CActivityTrk::desc_t` as far as these are common to all activities.

If there is other data not common to all activities it should be stored in a different place using the activity enum as a key.

**Comment by pingurus** [comment]
> It's no problem to add other members to `CActivityTrk::desc_t` as far as these are common to all activities.

So the values for the velocity filter could go in there, when they're implemented?

**Comment by pingurus** [comment]
> ( ...now cooking MTB)

Did you make any progress?

**Comment by kiozen** [comment]
As this issue is older than 6 months I close it for now.
