### ISSUE TITLE
QMS GUI locks while loading POIs

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#390]
### Describe the bug

QMS GUI locks while loading POIs

### What have you done to circle down the problem?

Run RelWithDbg version to get call stack

### To Reproduce

1. Activate 1 POI file and several categories
1. Move and zoom map to wanted region
1. While big and small rotating cursors are still rotating try to activate a second POI file
1. Both cursors come to a standstill. GUI actions are no more possible.
1. Use break in MSVC 
1. Execution is/stops in CPoiPoi.cpp, line 525 (while(query.next())
1. Most likely 1 of the mutex operations (the lock in line 538?) in this loop doesn't return
1. Further stepwise debugging in MSVC not possible - need not existing kernelbase.pdb

### Expected behavior

No GUI lock after not allowed GUI action

### Screenshots

None

### Attachments

None

### Tracebacks

Not possible

### Desktop

 
* OS: Windows10
* QMapShack Version: commit 422c4c5

### Additional context

The repeatedly commented issue with the hard to detect small brownish rotating cursor on almost brown map background (desert areas) facilitates wrong/too early GUI actions!

**Comment by kiozen** [comment]
see #389
