### ISSUE TITLE
Save route sub-points as ordinary route points in case of track routing

### ISSUE THREAD

**Issue by pinysuse** [Maproom/qmapshack#396]
### Is your feature request related to a problem? Please describe.
[comment]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] )
Due to the behavior of my navigation devices I use airline-navigation based on _routes_.
This requires significant upfront planning and defining a sufficient number of route-/way-points.
The effective track evolves by following the natural terrain while the navigation device points to the next way-point.

Often, planning is based on pieces or combinations of existing tracks.
While QMapShack provides powerful tools to manipulate tracks, the current features do not allow for the simple conversion of a track into a route.

**_Track routing_** seems rather close to the intended solution! However, it does not allow to save the route including all the sub-point nicely created by track based routing.

### Describe the solution you'd like
[comment]: # (A clear and concise description of what you want to happen.)

Let's make use of the existing feature [Description of routing methods in QMapShack - Method 4: Routing with tracks (track 
routing)](https://github.com/Maproom/qmapshack/wiki/DocGisItemsRouting#description-of-routing-methods-in-qmapshack).

#### Request: 

Save route sub-points as ordinary route points in case of track routing

- The below fragment of an addition to the manual describes the possible user workflow to convert tracks to routes with this feature.
- Implementation option: Instead of saving route sub-points in track routing mode an additional button `Save as new (T)` could be added.

#### Note: 

The section [Save data](https://github.com/Maproom/qmapshack/wiki/DocGisItemsEditMultiple#save-data) could be understood in such way that sub-points created by this method would already be saved in the database. This is not the case. 
Nevertheless, they would not be exported. So a possibility to convert sub-point to ordinary route points is requested.

### Describe alternatives you've considered
[comment]: # (A clear and concise description of any alternative solutions or features you've considered.)

Current work around:

1. Export the track
2. Convert to a route in an external tool or editor
3. Re-import the route

### Give a reason why someone else should spend time on that request
[comment]: # (Keep in mind that you ask others to spend their spare time for your request. Good reasons are if you are able to prove that the request solves a fundamental problem for everyone, or the request is of general interest for many users. Bad reasons are you just want it to have that way, or argue that software xyz does it.)

- It appears this issue is addressed sporadically by users.
- Converting routes to tracks is possible in QMS but not vice versa

### Additional context
[comment]: # (Add any other context or screenshots about the feature request here.)

The following fragment of a wiki page could be added between [Use list of routing points](https://github.com/Maproom/qmapshack/wiki/DocGisItemsRte#use-list-of-routing-points) and [Use map window](https://github.com/Maproom/qmapshack/wiki/DocGisItemsRte#use-map-window):

---

### Use Tracks

(see also the section [Use map window](https://github.com/Maproom/qmapshack/wiki/DocGisItemsRte#use-map-window))

1. Open a map view
2. Activate a track from the database so that it is visible in the map view
3. Move the mouse pointer to a first trackpoint of a track in the map view where the route should start
4. Right-click the mouse and select `Add route` from the context menu which pops-up. A [toolbox](https://github.com/Maproom/qmapshack/wiki/DocGisItemsEditMultiple#user-content-line-edit-toolbar) appears on the top of the map view.
5. Press `T` to select track routing method and follow the [detail description for track routing](https://github.com/Maproom/qmapshack/wiki/DocGisItemsRouting#user-content-description-of-routing-methods-in-qmapshack) to use one or more tracks to create a new route.
6. Press `Save as new`.
   Sub-points will be converted to ordinary route points when track routing mode (`T`) is active. 
   
#### Note

This will produce a route with potentially a lot of route points not suitable for routing with a routing engine (too many points).
Also a navigation device will need to use airline routing to handle a route with so many points. Beware of device specific points-per-route limits!
   
#### Hint
After creating a route based on tracks consider to convert it to a track _again_, reduce the number of points by means of [track filters](https://github.com/Maproom/qmapshack/wiki/DocGisItemsTrkFilters#track-filters), and convert it back to a route by above method.

---

**Comment by kiozen** [comment]
Wouldn't it be simpler to allow saving of subpoints when saving a route? Right now QMS only saves the points set by the user. The subpoints calculated by a routing engine are purged when saving the route. There might be a small dialog when saving routes giving the user the options and a checkbox if the options should be applied to all routes when saving several.

**Comment by UEckhardt** [comment]
I have started development on this topic: [https://github.com/UEckhardt/qmapshack/tree/QMS-396](https://github.com/UEckhardt/qmapshack/tree/QMS-396). The first commit there allows to convert a track to a route via a new icon in the track context menu.

Since my old garmin device allows only up to 230 route points I plan to implement this feature also for the actions for a track range.

**Comment by UEckhardt** [comment]
> Wouldn't it be simpler to allow saving of subpoints when saving a route? Right now QMS only saves the points set by the user. 

I think it is not necessary to save subpoints. Specially the routes for older devices should not be overloaded with intermediate points. 

I don't like too much intermediate dialogs, so an other approach would be, to have two conversion buttons, one for saving the subpoints and an other one for saving without subpoints. Since I think this feature is heavily dependent on the used GPS devices it may be sufficient to have only a global option in the setup dialog.

**Comment by pinysuse** [comment]
> > Wouldn't it be simpler to allow saving of subpoints when saving a route? Right now QMS only saves the points set by the user.
> 
> I think it is not necessary to save subpoints. Specially the routes for older devices should not be overloaded with intermediate points.

Actually, I do not know in which respect a _sub_point differs from an _ordinary_ route point and how various devices would handle it. It may be safer to save them as ordinary ones.

Re. device limitation: As pointed out in the wiki fragment "Hint", depending on the previous workflow it may be necessary to filter out/remove superfluous point after a first raw route/track creation. I think this is no problem once we have a possibility to create a route from a track and can switch between both anytime.

So I would be happy with any of the proposed approaches.

**Comment by UEckhardt** [comment]
I have now pulled a new version which allows to convert a track range to a route. There is a new icon (route) in the track range menu.

**Comment by kiozen** [comment]
Sub-points vs points: A most simple route is from A to B. Therefore the route points are A and B and a straight line in between. 

Now we have auto-routing that can convert that straight line into many sub-points. These sub-points usually are not subject to be saved with the route as (in an ideal world) they can be calculated anywhere else, too. As a consequence the route is stored with two points A and B. 

Of course we can decide to save those sub-points as ordinary points, too. Leading to the already mentioned problem that most devices have a limit (Why? Because they consider all route points as intermediate stations they have calculate a route for) I know that is not you goal. You want airline routing. 

Imho the proper way would be to have a route with calculated subpoints and and convert it into a route with pure route points based on a simplifying algorithm that takes a maximum number of route points.

**Comment by UEckhardt** [comment]
I don't think it is worth the work to develop an simplifying algorithm. This algorithm will depend heavily on the used device, its routing capabilities and limitations. So it may be a real challenge to create a well working algorithm. If anyone has a good idea for such an algorithm it would be better to implement this for tracks with the ability to convert sub-points to points.

**Comment by kiozen** [comment]
The algorithm is called Douglas-Peucker and is already implemented in QMS. But we can discuss it, when I have more time in the next days.

**Comment by pinysuse** [comment]
I apologize for the late reply.
After eventually upgrading to OpenSuse 15.3 and getting a recent version of QMS installed I had the chance to use the new feature.

**_It works like a charm!_**

Thanks to @UEckhardt and @kiozen  for providing to this great feature!
