### ISSUE TITLE
1.16.0 ecw don't work Win10 

### ISSUE THREAD

**Issue by flock-vi** [Maproom/qmapshack#399]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
vrt-builder in rev 1.16.0 : ERROR 4: `1.ecw' not recognized as a supported file format.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
gdalplugins, license, and libecwj2.dll are ok ( in the program-directory )
different ecw-files same result
1.15.2 ecw was ok

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Werkzeug
2. VRT Builder
3. Quelldateien auswählen: xy.ecw
4. Zieldatei auswählen: xy.vrt
5. Start
6. ERROR 4:  `1.ecw' not recognized as a supported file format.

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: Windows 10
 - QMapShack Version:   1.16.0

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by kiozen** [comment]
As this version ships with an updated version of GDAL you probably have to update you ECW libs and all stuff that it needs to use ECW in GDAL, too. 

As ECW support is beyond the scope of this project and the Windows binaries are just donated by a volunteer you have to help yourself. In the Wiki there is an updated step by step instruction on how to compile for Windows.

**Comment by mitxel-m** [comment]
That's right, From QMS 1.16.0 the ecw plugin must be updated, to match GDAL 3.3.0. and MSVC2017 versions.

A new plugin installer can be downloaded [from GIS Internals](https://gisinternals.com/query.html?content=filelist&file=release-1916-x64-gdal-3-3-0-mapserver-7-6-3.zip) (Thanks to Tamas Szekeres), then follow the instructions in the wiki to update the plugin.

It seems that there is no plugin for MrSid yet at GISInternals.

( ...I will update the wiki now, with the new link)

**Comment by flock-vi** [comment]
Thanks a lot for the fast answer and the modified WIKI ! Now it works perfect again !
