### ISSUE TITLE
Installation on USB Stick

### ISSUE THREAD

**Issue by borisb74** [Maproom/qmapshack#404]
### Is your feature request related to a problem? Please describe.
I tried to install QMapShack on a UBS pen drive to have a portable version for sharing map configuration, POIs, database etc. across my desktop and laptop. However, I didn't succeed.

### Describe the solution you'd like
I'd like to have a rough instruction on how to have a QMapShack installation on a USB pen drive.

### Give a reason why someone else should spend time on that request
Having QMapShack on a pen drive would help us to start planning on a desktop and continue planning when on vaction, trip, ...

**Comment by kiozen** [comment]
This is out of the scope of this project. Do you really expect someone else to do the work for you with that lousy request of yours? You haven't even provided a target OS nor what you have tried so far. This is just like "I want unicorns!". Sorry unicorns are all sold out. There won't be any delivery of new unicorns soon. Best you breed your own. :unicorn:

**Comment by WST1811** [comment]
@borisb74 
I'm using QMS on 3 Devices at the same time. Install QMS in OneDrive or Google Drive or another Cloud and use it in a mounted network drive. That works for me in the last years. For vacation i use a small netbook, it works. ;)

**Comment by borisb74** [comment]
> @borisb74
> I'm using QMS on 3 Devices at the same time. Install QMS in OneDrive or Google Drive or another Cloud and use it in a mounted network drive. That works for me in the last years. For vacation i use a small netbook, it works. ;)

Thank you very much for your suggestion. I'm basically able to share maps and DEM configuration across multiple computers. However, two topics are unclear for me:
* The workspace is always created under C:\Users\<userid>\.config\QLandkarte\workspace.db, Is there a way to specify where the database is located or use a separate database? Looking at the code it seems to be fixed to QDir::home(). Based on the description of QDir::homePath() I tried to set several environment variables in a batch file, but none of them seem to work.
* I configured and automatic switch of the zoom level (Google Maps for overview, other for details). This is not configured in the maps folder but elsewhere. How can I share this option across computers?

**Comment by WST1811** [comment]
>     * The workspace is always created under C:\Users<userid>.config\QLandkarte\workspace.db, Is there a way to specify where the database is located or use a separate database? Looking at the code it seems to be fixed to QDir::home(). Based on the description of QDir::homePath() I tried to set several environment variables in a batch file, but none of them seem to work.

I asked this in a german forum, the answer was: No, this Database is never made for using by more then one QMS Installation. Most of time i clean up the workspace, shutdown QMS and start it at the other device.

You can try to copy workspace.db into a networkdrive after finish QMS und copy the db before start QMS into the wright directory.
 
>     * I configured and automatic switch of the zoom level (Google Maps for overview, other for details). This is not configured in the maps folder but elsewhere. How can I share this option across computers?

Don't know, sorry.

**Comment by kiozen** [comment]
As there is no progress since have a year I close the ticket for now.
