### ISSUE TITLE
MBTiles hybrid maps text is so small

### ISSUE THREAD

**Issue by DerekTizz** [Maproom/qmapshack#405]
When zooming MBTiles maps with hybrid layers visible hybrid text is very small, not readable. Can you add intermediate zoom levels (forex by Shift or Alt) to add smooth zooming to increase text size. Thank you!

**Comment by DerekTizz** [comment]
![CropperCapture 11](https://user-images.githubusercontent.com/29268936/120118526-b246ad00-c19b-11eb-8617-f10d1f8366d0.jpg)

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
