### ISSUE TITLE
Add please moving map with GPS usb doungle support

### ISSUE THREAD

**Issue by DerekTizz** [Maproom/qmapshack#407]
Add please moving map with GPS usb doungle support, cos qlandkarte doesn't support mbtiles maps. I have a lot mbtiles which easy opened by qmapshack. I want to use qmapshack for raster maps navigate by usb GPS. Thank you!

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
