### ISSUE TITLE
Buttons on top of a map are not visible in dark mode on the Mac

### ISSUE THREAD

**Issue by d029940** [Maproom/qmapshack#41]
**Describe the bug**
Selecting a route and hit icon "Move route points" shows buttons "Save to original", "Save as new", "Abort" at the top of the map. These buttons are barely visible, although they are present. 

**To Reproduce**
0. Switch to dark mode on the Mac
1. Go to 'Workplace and select a route.'
2. Click on 'Click on the route on the map.'
3. See error in the top left of the map view

**Expected behavior**
The buttons should be visible.

They are visible in light mode.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X 10.14
 - QMapShack Version 1.13.2

**Additional context**

**Comment by kiozen** [comment]
Up to now we don't have a good fix for that. I would think this is a Qt bug for the OS X dark them. These buttons are plain buttons and the correct colour scheme should be applied. As far as I can see the buttons are transparent taking the colour of the widget underneath as background colour. This works for a classic dialog widget with a dark background widget. but not for the map canvas.

Applying the dark theme in Linux does not show this flaw. In Linux the buttons background colour is set correctly. Therefore I think this is an OS X specific bug.

As there is no active OS X developer and the maintainer of the binary packages lacks the expertise we can't provide a fix. A patch is highly appreciated.

**Comment by d029940** [comment]
Hello,

I understand, that this is OSX specific.

I am a hobbyist programmer and just learning Qt. The only “hack” currently I can think of, is to set the background of those buttons which are on top of a map, with CSS stylesheet.

e.g. the following line sets the background of the button to green. 
pushButton->setStyleSheet("background-color: #4CAF50");

Like I mentioned, it is somehow a hack and I am far away to be a programmer.

Manfred

Manfred Kern
Email: manfred.kern@gmail.com

**Comment by kiozen** [comment]
Yes this is a hack indeed. It would affect all OS and all colour schemes pinning the colour to a fixed value :smiley: That's not what we want. 

Probably the best fix would be to load a stylesheet for buttons when starting QMS. This code has to go into the OS X specific initialization. `CAppSetupMac` However it has a flaw, too. The moment OS X decides that the background colour should change all buttons will still have the fixed value.

Maybe you can google a good solution and test it.

**Comment by d029940** [comment]
You are right.
In order to do it right, one must whenever the map view is repainted
- check the current mode (dark or light) (optional)
- Set the background, the border and the font of those buttons on the map to a fixed color, so that the text can clearly be seen.

- And these settings have to be wrapped into an #ifdef Q_OS_MACOS ...

Another solution is to enforce light mode for the complete app (btw. the Windows version also does not respect dark mode). In order to this, you need to add 

<key>NSRequiresAquaSystemAppearance</key>
<string>true</string>

to info.plist

Refer to https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_macos_app#2993819

**Comment by d029940** [comment]
You are right.

One have to set the background, border and font color in a way (fixed) - irrelevant of dark / light mode for those buttons on the map view. I am not sure if CAppSetupMac is the best place. Maybe this have to be set when those buttons are created and should be wrapped into an `#ifdef Q_MAC_OS  ... #endif`conditional statement. In that way, you can ignore palette, dark/white mode changes .... And this would be ok, because the underlying map itself does not respect those changes either.

Alternatively, we can enforce light mode by putting

`<key>NSRequiresAquaSystemAppearance</key>
<string>true</string>`

into the `info.plist` file, i.e. completely opting out from dark mode, as described here:
[https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_macos_app#2993819](url)

By the way, the windows version does not respect dark mode.

**Comment by d029940** [comment]
I just checked adding the following to Info.plist in the Contents folder of the QMapShack.

`<key>NSRequiresAquaSystemAppearance</key> 
<string>true</string>`

It works - no rebuilding of the software needed. QMapShack will be shown in light mode and the buttons over the map can be identified. So maybe this can be changed on GitHub as well, so that the next download works also in dark mode.

**Comment by kiozen** [comment]
As this issue is older than 6 months I close it for now.
