### ISSUE TITLE
CScrOptRangeTool: Fix layout for larger fonts.

### ISSUE THREAD

**Issue by UEckhardt** [Maproom/qmapshack#414]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
The track data of the last point of a track is not fully displayed int the range tool window, see point 410 in the attached screen shot.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
Checked with the current version 1.16.0 and latest dev branch.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Select a track.
2. Click on the range tool button.
3. Select the last point of the track.
4. See error, the information of the last point is shown only partially. 

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)
The information of the last point shall be fully visible.

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)
![Screenshot_20210606_135358](https://user-images.githubusercontent.com/11475549/120923811-c6753780-c6d0-11eb-921f-187010f22353.png)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: OpenSuSE Leap 15.2
 - QT: 5.12.7
 - QMapShack Version:   1.16.0 and latest dev branch
 - Window Manager: KDE 5.18.6

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by kiozen** [comment]
Tried to reproduce with all kinds of fonts. The ugly ones and the less ugly ones. Couldn't reproduce. What are your font settings?

**Comment by UEckhardt** [comment]
I use NotoSans14. I have tested these fonts settings under Ubuntu 21.04 (KDE 5.21.4/QT 5.15.2). There QMS works as expected. Yesterday I upgraded to OpenSuSE leap 15.3 but the problem still remains. 

It seems to be some other issue only on OpenSuSE Leap 15.2 and Leap 15.3.

**Comment by UEckhardt** [comment]
I can reproduce the problem now also on Ubuntu. From the main menu select View->Set Map Font and select a font with size 14, for example Noto Sans Regular 14.
