### ISSUE TITLE
Problem loading from Database

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#42]
**Describe the bug**
When having old geocaches in the database and one loads a project containing those, QMS acts a bit weird, without causing any serious problems if you don't provoke QMS.
This changes, when you open a geocache, that loads a picture from web:
* if you have this geocache loaded multiple times to workspace (see below how to achieve that), QMS crashes
* if you have the geocache only loaded once, you get [4]. In this state, you can't close the project from the database window, since it is stuck in the "squared" state and you can't toggle through to unchecked

**To Reproduce**
1. Open an old database 
2. Load project containing geocaches into workspace
3. Play around, maybe there are more bugs than what I found

**Expected behavior**
I would expect QMS to convert the geocaches to the current format, mark the project as changed and when saving overwrite the old geocache items.

**Screenshots**
[1] When I tick the box next to the project the old geocaches don't get ticked:
![grafik](https://user-images.githubusercontent.com/36167579/66401348-51c19580-e9e3-11e9-8a05-229a411901cb.png)
[2] The workspace looks reasonable:
![grafik](https://user-images.githubusercontent.com/36167579/66401443-76b60880-e9e3-11e9-8896-51553a13a818.png)
[3] However, when I manually tick the old geocaches in the database window they get unticked and this happens:
![grafik](https://user-images.githubusercontent.com/36167579/66401531-93524080-e9e3-11e9-8579-f3a70ab951fe.png)
[4] Database after loading image for geocache (without provoking the multiple load of a geocache into the workspace) and saving:
![grafik](https://user-images.githubusercontent.com/36167579/66402220-cc3ee500-e9e4-11e9-909e-0b4fcdae9449.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - QMapShack Version 1.13.2

**Additional context**
I have yet no idea how old the database has to be (i.e. was this introduced when I worked on the CGisItemWpt to make it better usable for geocaches (I think yes, since it still has the old symbol in the database) or is this a problem of the changed key calculation for geocaches or is it maybe a side effect of something I didn't work at or a combination of the former)

**Comment by kiozen** [comment]
As this issue is older than 6 months I close it for now.
