### ISSUE TITLE
Change of map view name is not taken into account in POI tab

### ISSUE THREAD

**Issue by kkarsten62** [Maproom/qmapshack#421]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
Changing the name of a map view will not consider in POI tab. But in DEM and/or Map tab it's handled correctly.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
- Change name of map view
- Check in POI tab ==> name is **not** changed
- Check in Map or DEM tab ==> name is changed

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)
see above

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)
Name should be change in tab, same as DEM or Map tab

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)
![grafik](https://user-images.githubusercontent.com/55464608/122079657-e8bc3300-cdfd-11eb-8144-78beac69b96a.png)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)
N/A

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.)
N/A

### Desktop
[comment]: # (please complete the following information)

 - OS: Ubuntu 18.04
 - QMapShack Version:  latest development commit
 - Window Manager:  GNOME

### Additional context
[comment]: # (Add any other context about the problem here)
N/A

**Comment by wthaem** [comment]
Even closing the POI tab and re-opening it doesn't lead to the new name! (Windows)

**Comment by kiozen** [comment]
I will prepare a fix. Might take some time to upload it.

**Comment by kkarsten62** [comment]
No stress :-)

It's a minor Bug only. After a restart the changed name is present. So we have a valid bypass solution.
