### ISSUE TITLE
Combine tracks results in a new track with several segments - conflicting documentation

### ISSUE THREAD

**Issue by WIsbrecht** [Maproom/qmapshack#422]
### Is your feature request related to a problem? Please describe.
[comment]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] )

When combining several tracks to one new track, the new track consists of several segments.
I consulted the documentation and found opposing statements regarding the "Combine tracks" feature.
DocGisItemsTrk:
- "Handling of track segments": "[...] joining after that all segments properly with the help of the context menu entry Combine tracks creates a new track with one segment only [...]"
- "Combine tracks": "When combining tracks, the track segments of all tracks involved are copied in the selected order into the new track. Thus, combining several tracks leads to tracks with several segments."

I found the latter is the current behavior of QMS. The new track consists of several segments.

### Describe the solution you'd like
[comment]: # (A clear and concise description of what you want to happen.)

Either fix the documentation or, better, give a choice when combining tracks whether the new track should have only one or several segments in it.

### Describe alternatives you've considered
[comment]: # (A clear and concise description of any alternative solutions or features you've considered.)

Implement a segment editor of some sort. I couldn't find a way to see if there are more than one segments in a track in QMS. Only after exporting to gpx and searching for "trkseg" shows that there are indeed more than one segments in the track.

### Give a reason why someone else should spend time on that request
[comment]: # (Keep in mind that you ask others to spend their spare time for your request. Good reasons are if you are able to prove that the request solves a fundamental problem for everyone, or the request is of general interest for many users. Bad reasons are you just want it to have that way, or argue that software xyz does it.)

I only found this issue after I joined several tracks in QMS into one and saved it as a gpx file. Then I imported the gpx file in Osmand and there I saw more than one start/stop icon for the track. This suggested that there were more than one segments in the file. I opened the gpx file in an editor and found more than one "trkseg".

### Additional context
[comment]: # (Add any other context or screenshots about the feature request here.)

**Comment by wthaem** [comment]
Current QMS behavior confirmed. Conflicting documentation can be found in `DocGisItemsTrk`. If there hasn't been a change in QMS then the description in the subsection `Handling of track segments` is incorrect and has to be improved. @kiozen: Please, confirm that the documentation has to be changed. After that I'll do the change.

**Comment by kiozen** [comment]
I would say the current behavior of Qmapshack is the intended one. Therefore fixing the Wiki is the way to go.

**Comment by wthaem** [comment]
Documentation fixed. Thanks for pointing to the conflict!

**Comment by WIsbrecht** [comment]
Thank you! Is there a way in QMS to join several tracks and only have one segment in it, or if not, how would I delete the segments in the resulting track?

**Comment by wthaem** [comment]
Not the solution one would expect but a possible one:

In the latest QMS dev version a track can be converted into a route (track context menu `Convert to route`) and the route can be converted back to a track (route context menu `Convert to track`). The new track has only 1 segment.

Be careful to handle track subpoints correctly!

**Comment by kiozen** [comment]
We could make this an option in the dialog. Would you please open a feature request referencing this discussion?

⁣BlueMail for Android herunterladen ​

**Comment by WIsbrecht** [comment]
Yep, will do. Thanks.
