### ISSUE TITLE
Adding new map paths is broken

### ISSUE THREAD

**Issue by salsergey** [Maproom/qmapshack#427]
### Describe the bug
I want to add new map path. However, the dialog for selecting a directory is broken, because there is no reaction when I click the "Open" button.

### What have you done to circle down the problem?
This dialog is working on Windows. However, it is broken for a couple of years on Linux. I guess it could be the result of some changes made in Qt or KDE libraries.

### To Reproduce

1. Press RMB at the maps panel and select to adjust map paths.
2. Press the "plus" button and try to add a directory.
3. Select any directory and press "Open" button.
4. Nothing happens...

### Expected behavior
The dialog should close and a directory should be added to the list of map paths.

### Screenshots
[comment]: # 

### Attachments
[comment]: # 

### Tracebacks
[comment]: # 

### Desktop
Manjaro Linux with KDE. QMapShack 1.16.0 as well as current dev branch.

### Additional context
[comment]: #

**Comment by kiozen** [comment]
Strange enough it's working on my SuSE 15.2/KDE system. But anyways using the default for the flags is the better choice.
