### ISSUE TITLE
Changing .QMapShack folder's location

### ISSUE THREAD

**Issue by erhelito** [Maproom/qmapshack#433]
### Describe the bug
It's more a question than a bug... How can we configure the .QMapShack folder's location ? It's because I have 2 harddisks : an SSD, and an HDD. QMapShack is installed on the SSD, but it's not advised to store temporary files on an SSD...

### Desktop
[comment]: # (please complete the following information)

 - OS: Win 10
 - QMapShack Version:   1.16.0

**Comment by kiozen** [comment]
Change the environment variables like HOME before starting QMapShack

And please stick to the template. Next time the issue will be closed without further notice.
