### ISSUE TITLE
Realtime source: HTTP

### ISSUE THREAD

**Issue by Gleb-ho** [Maproom/qmapshack#434]
### Long story short 
New realtime data source - polling KML data from HTTP server, would be great.

### Long story
We are using Qmapshack in real rescue operations and related training. Qmapshack is very helpful in collaborative work on placemarks database due to it's Database functionality. Also Qmapshack has good tools for measurements and some map drawing operations (waypoint radius, waypoint clone and move). 
But there are some limitations we struggle. First one is offline maps, which are absolutely required in real rescue operations. We have solved this with [mapproxy](https://mapproxy.org). But second problem is that we have a lot of gis data which comes from different sources, and we are gathering it in our self-written application. It takes a lot of time to export and import it to Qmapshack. So it would be helpful to use realtime data source in Qmapshack which polls http server for placemarks.

Another approach is to write to MySQL server which Qmapshack use. But there is binary data stored, we cant reliably update it. So if Qmapshack's MySQL storage implementation will be refactored to support external updates, and that update process will be documented - problem solved.

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
