### ISSUE TITLE
Store/restore name of map view

### ISSUE THREAD

**Issue by kiozen** [Maproom/qmapshack#436]
### Is your feature request related to a problem? Please describe.
[comment]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] )

Restoring a map view from file won't restore the view's name. 

### Describe the solution you'd like
[comment]: # (A clear and concise description of what you want to happen.)

The view's name should be stored with all other data in the `*.view` file. When restored the name should be applied.

### Describe alternatives you've considered
[comment]: # (A clear and concise description of any alternative solutions or features you've considered.)

n/a

### Give a reason why someone else should spend time on that request
[comment]: # (Keep in mind that you ask others to spend their spare time for your request. Good reasons are if you are able to prove that the request solves a fundamental problem for everyone, or the request is of general interest for many users. Bad reasons are you just want it to have that way, or argue that software xyz does it.)

The view's name is part of the view's data that should be restored. As a user you want to get your view back without any other configuration.

### Additional context
[comment]: # (Add any other context or screenshots about the feature request here.)
n/a

**Comment by michael-heerdegen** [comment]
Now this change got available in Debian and I could finally test it.  Works nicely as I had imagined. Thank you very much!
