### ISSUE TITLE
Add number of tracks in a project in headline in detail project track list

### ISSUE THREAD

**Issue by kkarsten62** [Maproom/qmapshack#439]
### Is your feature request related to a problem? Please describe.
[comment]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] )
I would like to see the number of tracks in a project shown in headerline in track list in project edit dialog.

### Describe the solution you'd like
[comment]: # (A clear and concise description of what you want to happen.)
Add/change two lines of code in method CDetailsPrj::drawByGroup(...) in CDetailsPrj.cpp
QString htmlStr = QString("\<h2\>%1 ").arg(trks.count()) + tr("Tracks\</h2\>");
cursor.insertHtml(htmlStr);

### Describe alternatives you've considered
[comment]: # (A clear and concise description of any alternative solutions or features you've considered.)
N/A

### Give a reason why someone else should spend time on that request
[comment]: # (Keep in mind that you ask others to spend their spare time for your request. Good reasons are if you are able to prove that the request solves a fundamental problem for everyone, or the request is of general interest for many users. Bad reasons are you just want it to have that way, or argue that software xyz does it.)
I will provide a Pull Request.

### Additional context
[comment]: # (Add any other context or screenshots about the feature request here.)
![Auswahl_038](https://user-images.githubusercontent.com/55464608/134000941-e84ea4ed-b2e7-4c85-af00-86c6392263bd.png)

**Comment by kiozen** [comment]
Why just for tracks? This should be either done for all sections ore none. If you just do it for one it's just a matter of time someone is requesting it for another.

**Comment by kkarsten62** [comment]
> Why just for tracks? This should be either done for all sections ore none. If you just do it for one it's just a matter of time someone is requesting it for another.

Hmm, personally I am working with Tracks and Waypoints only. I did not checked the code to find out what kind of other stored objects (Routes?, Areas?) will be displayed in projects details. Any quick help? Then I can I adapt tonight to the other objects.

**Comment by kiozen** [comment]
Yes it's always tracks waypoints routes and areas. Just look at the file you already edited.

**Comment by kkarsten62** [comment]
> Yes it's always tracks waypoints routes and areas. Just look at the file you already edited.

Updated for Waypoints, Routes and Areas also.
