### ISSUE TITLE
Error loading 4umaps

### ISSUE THREAD

**Issue by sgrifell** [Maproom/qmapshack#443]
### Describe the bug
4umaps online maps do not load in the map view

### What have you done to circle down the problem?
I tried older versions, compiled a development version, and I have the same problem.

### To Reproduce
In the debug console the message is: 

2021-09-25 8:13:00.954 [debug] Request to "https://tileserver.4umaps.com/15/16058/12318.png" failed: "Falló el handshake SSL"

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

### Screenshots
![image](https://user-images.githubusercontent.com/36042117/134761045-d31a16c4-b582-4dc2-8461-34096aa68a29.png)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: Linux Mint 19.3 Tricia 
 - QMapShack Version:  1.16.0
 - Window Manager:  xfce

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by kiozen** [comment]
This not a problem of QMapShack. Your OpenSsl/Qt installation seems to be broken. You need a Qt installation that includes the OpenSsl plugin-in and of course the proper OpenSsl version hast to be installed, too.

**Comment by sgrifell** [comment]
Thanks! 

I'm going to review it but it seems strange because with opentopomap (HTTPS) everything works fine

**Comment by sgrifell** [comment]
I found in stackoverflow one workaround for this possible bug in QT 5.12.8 - OpenSSL 1.1.1f that works fine for me. In the file map/IMap Online.cpp i was added in the line 66 this code:

QSslConfiguration conf = request.sslConfiguration();
conf.setPeerVerifyMode(QSslSocket::VerifyNone);
request.setSslConfiguration(conf);
