### ISSUE TITLE
MacOS binaries for v1.16 are missing

### ISSUE THREAD

**Issue by cvigo** [Maproom/qmapshack#458]
### Is your feature request related to a problem? Please describe.
[comment]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] )
MacOS binaries for v1.16 are missing

### Describe the solution you'd like
[comment]: # (A clear and concise description of what you want to happen.)
Add MacOS binaries as for previous versions

### Describe alternatives you've considered
[comment]: # (A clear and concise description of any alternative solutions or features you've considered.)
Compile the binaries myself :-(

### Give a reason why someone else should spend time on that request
[comment]: # (Keep in mind that you ask others to spend their spare time for your request. Good reasons are if you are able to prove that the request solves a fundamental problem for everyone, or the request is of general interest for many users. Bad reasons are you just want it to have that way, or argue that software xyz does it.)

### Additional context
[comment]: # (Add any other context or screenshots about the feature request here.)

**Comment by kiozen** [comment]
Binaries are not part of the project. They are provided by volunteers maintaining them. Currently there is no one maintaining the OS X binaries. That's why there aren't any recent. 

Therefor the alternative - compiling yourself - is the only option.

**Comment by cvigo** [comment]
😕 thanks
