### ISSUE TITLE
Why call it a copy if it’s not a copy?

### ISSUE THREAD

**Issue by Moilleadoir** [Maproom/qmapshack#459]
I’ve used a lot of programs, but QMapShack has to be one of the most confusing.  One of the biggest problems I have is the deeply unintuitive use of the word ‘copy’.  Almost always a copy is just a link/reference and not a copy, so why call it a copy?  That’s just misleading.

There are three things that could make QMS more understandable.

1. Change `Copy to` to `Create a link to`
2. Change `Create a clone` to `Create a copy`
3. Add some way to directly create a copy

At the moment the only way to actually create a copy in a new folder is to use `Copy to` twice and then delete the reference.  Since this is something I do a lot, it’s very frustrating.  I have a lot of officially ‘named’ trails that I need to make copies of so they can be cut up and recombined.  This is fairly trivial to do in a program like BaseCamp, but very tedious in QMapShack.

I suspect that most users are used to the way it works, so there may not be much incentive to change this behaviour.  All I can say is that I find that when I come back to using the program every few months I have to waste **a lot** of time relearning the odd way it works.

If there is a way to directly create real copies (“clones”) that I’ve missed, I’m ready to learn, but using giving words different meanings can only be puzzling to users.

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

**Comment by Moilleadoir** [comment]
Wow!  Obviously not interested in feedback.
