### ISSUE TITLE
[TOC] in Wiki pages

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#46]
In the Bitbucket Wiki there was a possibility to create a TOC with the help of the `[TOC]` macro inserted on top of a wiki page. This doesn't work anymore in the Github wiki. 

**Questions:** 

- Does somebody know an easy way to create a TOC in a Github Wiki?
- Should we delete this not working macro from the Wiki pages?

**Comment by kiozen** [comment]
Up to now I haven't found a good solution. The situation as far as I understood:

* Github does not provide a macro for `[TOC]`
* It does provide a macro for other formatting languages.
* We can replace `[TOC]` by a real table of contents
  - by doing this once emanually
  - by doing the once with one of the scripts found in the Net

Changing the formatting language is quite a task. Markdown is one of the most simple ones. That's why I chosed it. It's quite readable without rendering. And very widely supported. I would like to stick with it.

Replacing the `[TOC]` is quite a task, too. But it's easier to be done. It's a one time effort. And then we have to keep the table of contents in sync which is the major drawback.

**Comment by wthaem** [comment]
My proposal for the TOC issue after knowing enough about the rules for building anchors in Github:

* Use a Python script on a local copy of the Wiki to
    * insert a TOC on top of each Wiki page in case there is no TOC (should be done once),
    * update an existing but outdated TOC, if necessary (should be done after editing a Wiki page implying a change of the TOC).
* The essential parts of such a script are ready and I'm testing them.
* The script can be made public and used by everybody editing a Wiki page on a local copy of the Wiki (Python must be available without any additional packages).
* I don't have a clue, if such a script can run on the server side and if so, which requuirements the script should fulfill.

@kiozen: Should I proceed in this direction?

**Comment by wthaem** [comment]
I just understood that Github Wiki pages are creating and using non-ASCII languages anchors in links that don't work.
Thus, TOC's can only be added to English Wiki pages and not to DocQuickStartGerman.md (if uppercase umlauts are in header line), DocQuickStartSpanish.md (if special Spanish characters are in header line), or DocQuickStartRussian.md.

**Comment by kiozen** [comment]
I think we could use hooks in git you run stuff on a commit. 

https://git-scm.com/book/de/v1/Git-individuell-einrichten-Git-Hooks

But I am not sure if that works with GitHub. Right now I am lacking the time to have a closer look.

**Comment by wthaem** [comment]
I run a local (client-side) pre-commit hook while using git in the Git Bash shell under Windows. Works fine. I didn't try to do the same with a usual CMD shell. 

Disadvantages of client side hooks: 
* hooks are not part of the repo and must be distributed and activated using some special additional rules
* No client-side hook detects automatically and immediately Wiki pages edited on the server.

On the server-side a post-receive hook might do the job if it is possible to get access to the repo's file system (read and write access). 

Disadvantage: after pushing changes to the repo the user can assume that the repo and his local copy are in sync unless another user pushes new modifications. The server-side hook can be seen as such a (pseudo-)user who makes instantaneous changes to the repo. Thus, repo and local copy may fail to be in sync immediately after a push.

*Open question:* when editing a Wiki page on the server would it be possible to trigger a script when leaving the editor?

**Comment by wthaem** [comment]
@kiozen: The location of the Wiki should be `https://github.com/Maproom/qmapshack.wiki.git` (result from calling `git config --get remote.origin.url` on the local Wiki copy). When opening this URL I get an 404 error. Could you please check if you can open this URL and see the Wiki files in the form code files can be seen without the `.wiki` part? Could the 404 be related to access rights?

**Comment by kiozen** [comment]
same for me. This URL is mapped to the git machinery. The real URL is https://github.com/Maproom/qmapshack/wiki

**Comment by wthaem** [comment]
Sure - it is. But at the same time there is the information that the Wiki in GH is handled internally like a repo and the link given above should point to the files (I suppose the MD ones and not the ones rendered in the browser), including to some additional Git internal directories, used e.g. for server-side hooks. My hope was that with access to `https://github.com/Maproom/qmapshack.wiki.git` there could be a way to define such a hook. Up to now, I haven't seen any other way to define a server-side hook.

**Comment by kiozen** [comment]
As far as I understood - with the scarce research I did - you need a sub-directory `.git/hooks` in your repository. You can create such a directory within your cloned repo and commit/push the changes.

Searching for `github adding toc via git hook` I found this 
https://github.com/thlorenz/doctoc

It looks like this might do exactly what we want.

Maybe it's best practice if you create a project in your domain and copy the wiki into the wiki space of that project. Now you can experiment and test without the danger to destroy anything in the real wiki. If it works out well you can copy that stuff into the real wiki.

**Comment by wthaem** [comment]
The `.git/hooks` directory is for client-side hooks only. For server-side hooks on GitHub I found the following comment:

*For obvious reasons, GitHub won’t allow you to execute arbitrary code on their servers as part of Git hooks. The only hooking they allow is through their webhooks or the integrated third-party services.*

*If you need to run some custom code, you will have to host that somewhere and set up a webhook to run it on your own server.*

From here, my conclusion is that the only way to handle TOC's is on the client-side. I'll have a look at doctoc. Maybe I will find some hints how to overcome weaknesses of my script (handling of non-ASCII MD pages)

**Comment by kiozen** [comment]
> _For obvious reasons, GitHub won’t allow you to execute arbitrary code on their servers as part of Git hooks. The only hooking they allow is through their webhooks or the integrated third-party services._
> 
 Makes sense :smile: 

I guess the easiest way is to run the scripts locally from time to time. Client side hooks are overkill as it would work only for the two of us.
