### ISSUE TITLE
Question: will the support for old Garmin devices be backported from QlandkarteGT?

### ISSUE THREAD

**Issue by jose1711** [Maproom/qmapshack#463]
I think QlandkarteGT was the only OSS program supporting uploading/downloading of maps and waypoints/tracks to/from old Garmin devices (e. g. eTrex Legend w/ monochromatic display) via serial cable. As there still may be people out there using such devices (me :smile: ) I wonder if there is a slight chance that some really basic support would be backported to qmapshack or I should better pin QlandkarteGT and all its dependencies (like `gdal` or `proj6`).

**Comment by kiozen** [comment]
No won't happen.

https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
