### ISSUE TITLE
Installation issue on Ubuntu 20.04.2

### ISSUE THREAD

**Issue by adzweig** [Maproom/qmapshack#466]
Hi
I am trying to compile the App in Ubuntu 20.04.2.
When I enter the command "ccmake ../QMapShack" I receive the error message "Error opening terminal: xterm-256color"

How can I find out what why this is happening?

Thanks for any pointer
Adrian

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

**Comment by kiozen** [comment]
Search Google for the error.
