### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by 13hannes11** [Maproom/qmapshack#467]
### Is your feature request related to a problem? Please describe.
It would be great to have a flatpak version of qmapshack to make it easier to install on more systems. For example Fedora Silverblue.

### Describe the solution you'd like
A flatpak package on flathub.org

### Describe alternatives you've considered
Packaging as Appimage.

### Give a reason why someone else should spend time on that request
A flatpack makes the software available to more people.

**Comment by ventoux84** [comment]
I am also interested for a flatpak version.

**Comment by kkarsten62** [comment]
You can have a look on this:

https://hub.docker.com/r/harenber/qmapshack-appimage
https://github.com/kkarsten62/QMapShack.AppImage
https://github.com/kkarsten62/QMapShack.AppImage/wiki
https://github.com/Maproom/qmapshack/releases

AppImages for latest version 1.16.1 will be uplooaded next week.

**Comment by kiozen** [comment]
AppImages uploaded
