### ISSUE TITLE
Is a windows release is planned for the latest version V_1.16.1 ?

### ISSUE THREAD

**Issue by jcz7021** [Maproom/qmapshack#469]
### Is your feature request related to a problem? Please describe.
[comment]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] )
Not really, more like a question. Is a windows release is planned for the latest version V_1.16.1 ?

### Describe the solution you'd like
[comment]: # (A clear and concise description of what you want to happen.)
A windows relase for the latest version V_1.16.1

### Describe alternatives you've considered
[comment]: # (A clear and concise description of any alternative solutions or features you've considered.)
Using the V_1.16.0

### Give a reason why someone else should spend time on that request
[comment]: # (Keep in mind that you ask others to spend their spare time for your request. Good reasons are if you are able to prove that the request solves a fundamental problem for everyone, or the request is of general interest for many users. Bad reasons are you just want it to have that way, or argue that software xyz does it.)

A had created a bug concerning offset that seems to be fixed in the latest release (https://github.com/Maproom/qmapshack/issues/430) so I'm really interested :-)

### Additional context
[comment]: # (Add any other context or screenshots about the feature request here.)

**Comment by kiozen** [comment]
Binary is available
