### ISSUE TITLE
Support waypoints with grid coordinates

### ISSUE THREAD

**Issue by Don42** [Maproom/qmapshack#47]
**Is your feature request related to a problem? Please describe.**
When planning hikes I prefer to use UTM or MGRS coordinates. But QMapShack does not provide a way to create a waypoint from grid coordinates or read the grid coordinates of a waypoint.

**Describe the solution you'd like**
I would like to either have an option to switch the used format for all entry and display fields, or a
 second display field for the grid coordinates and a button to move the waypoint to a provided grid coordinate.

**Describe alternatives you've considered**
Currently I copy the degree coordinates to online converters.

**Additional context**
Hiking maps (in Germany) often use UTM grids. I prefer the MGRS format, since I find it easier to read and shorten for manual notes. Their are relatively easy to convert from one to the other.

**Comment by kiozen** [comment]
As this issue is older than 6 months I close it for now.
