### ISSUE TITLE
GPS usb antenna ?

### ISSUE THREAD

**Issue by eb4cuv** [Maproom/qmapshack#474]
I have a mouse type antenna that connects via usb to the computer of the (VK-172)
QMS has support for this type of antenna? And if not, are you planning to support it?

thanks,
Julio

**Comment by wthaem** [comment]
Did you read [https://github.com/Maproom/qmapshack/wiki/DocRealtime](https://github.com/Maproom/qmapshack/wiki/DocRealtime)?

**Comment by eb4cuv** [comment]
Yes, I read the documentation. It doesn't say anything about my question or I didn't see it. I already have it working with an android device, but I would like to connect it directly to a mouse-type antenna.

**Comment by wthaem** [comment]
There is no device-specific description but section "GPS location data" on the above-mentioned page describes the steps you have to follow. If your GPS data is not NMEA you have to find/build a converter.
