### ISSUE TITLE
GPSD and Realtime

### ISSUE THREAD

**Issue by eb4cuv** [Maproom/qmapshack#475]
Hi,

I have managed with the gpsd daemon to send data to other software like foxtrot via tcp/ip. In QMS I can set the host as localhost and the port as 2947.
In foxtrot I am receiving the position, height and other data well but not in QMS. QMS makes the connection ok but shows no data.

thanks.

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
