### ISSUE TITLE
Color the map by elevation

### ISSUE THREAD

**Issue by slammyV** [Maproom/qmapshack#476]
### The parent ticket
[comment]: # (Add ticketnumber behind QMS-# )

QMS-476

### What do you plan to do
[comment]: # (Describe roughly what you want to do.)
I like to add the functionality of coloring the map by elevation for getting a better impression of the terrain shape when planning routes.

### The result will be
[comment]: # (A list of goals that have to be achieved to consider the ticket as done.)
- a color overlay over the map that reflects the elevation
- added an option to the DEM for enabling and disabling the elevation based shading
- a color scale can be enabled/disabled to be shown in the map to assign colors to elevation
- min/max elevation spinners in the DEM prop menu to rescale the color bar
- a slider to change the opacity of the color overlay of the map

**Comment by huirad** [comment]
I like this feature. Thank you!
