### ISSUE TITLE
24 / 5 000 Résultats de traduction Conflict with antivirus 

### ISSUE THREAD

**Issue by ZestyEagle** [Maproom/qmapshack#482]
###nAnti-virus, abruptly closes QMapShack. The antivirus believes that QMapschak is making a fraudulent copy of data.

 ### I've only been using QMapSchak for a week and am learning about QMapshack's capabilities. When the incident occurs, the "TrendMicro" antivirus offers to uninstall QMapshcak. This happened 4 times in two days, January 28 and 29, 8 days after installing Qmashack on my PC. Since Trend Micro lists files it believes to be from a data breach, I searched and found one of these files. It is a tile of an OrthoPhoto IGN France map (TMS OnLine Map), loaded in the cache. Before this error appeared, I modified the configuration of the map view: EPSG 3857, square scale optimized for TMS/WMTS tiles. A track to identify the error.

### Used the ORTHO Photo

(https://user-images.githubusercontent.com/98384740/151673233-663193e4-a167-4387-bbcf-ce5dff47b13c.jpg)

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
