### ISSUE TITLE
MacOS: Tag/Nacht-Schalter ist ohne Wirkung - nicht optimale Farbwahl

### ISSUE THREAD

**Issue by SabineSW** [Maproom/qmapshack#485]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
Das Häkchen unter Ansicht bei Nacht/Tag ist ohne Wirkung unter MacOS. Es werden die Systemeinstellungen verwendet.

Die Farbwahl ist auch suboptimal: die weiße Schrift auf hellgrauem Hintergrund ist schlecht lesbar. Im Screenshot vom Bearbeiten eines Projekts ganz rechts.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
Nur mit QMapShack 1.15.2 unter MacOS getestet. Derzeit habe ich noch keine andere Version zur Verfügung. Ich habe sonst nur Linux und da gibt es den Modus nicht.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

Egal, ob das Häkchen gesetzt ist oder nicht.: Tagsüber schwarz auf weiß, nachts weiß auf schwarz.

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

Ich hätte gerne schwarz auf weiß zu jeder Zeit.

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

<img width="941" alt="Bildschirmfoto 2022-02-15 um 18 56 02" src="https://user-images.githubusercontent.com/92666324/154124042-b09a30ee-e4fa-4740-a4e0-339975600311.png">

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)
Abwarten, bis es Nacht ist.

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: [e.g. OS X, Debian, Suse, Windows]
 - QMapShack Version:   [e.g. 1.13.1]
 - Window Manager:  [e.g. KDE, GNOME]

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by kiozen** [comment]
I guess you have the wrong expectations about this feature

https://github.com/Maproom/qmapshack/wiki/DocControlMapDem#workspace

**Comment by SabineSW** [comment]
You are right! 

Nevertheless, when MacOS switches to Dark Mode, some parts are hard to read (white on grey).
