### ISSUE TITLE
Track selection 0-index bug

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#489]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

In Track selection mode, when you already have selected the track point with index 0 and press "extend towards start of the track" the selection is gone.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

When selecting the end of the track and moving towrds the end nothing happens (as expected).
The error occurs both when keeping the button "extend towards start of the track" pressed and when stepping through.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Select any track
2. Go into trackpoint selection mode (that on with the screen overlay where the selected part of the track turns green, not the editing one)
3. Select a range at the beginning
4. press "extend towards start of the track"  until you see the  error

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

Just as at the end: when you are at the limit stay there and keep the selection.

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

x

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

x

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

x

### Desktop
[comment]: # (please complete the following information)

 - OS: Ubuntu 20.04
 - QMapShack Version:  commit  bd24a0f9d41ea131f584c6b60bd57f9d53779cd7 (1.16.1 dev)
 - Window Manager:  GNOME

### Additional context
[comment]: # (Add any other context about the problem here)

x

**Comment by kiozen** [comment]
Please test PR
