### ISSUE TITLE
Crash when selecting a folder in the «map / select a folder» menu

### ISSUE THREAD

**Issue by Philetjosie** [Maproom/qmapshack#491]
I try to select a folder for the maps, using the menu: file / select a map folder. The windows open correctly, I click the "+" sign to add a new folder, I then have a nautilus window to select the folder I want, but as soon as I select a folder, QMapShack crashes. 
I did not find how to lauch it from the terminal (tried «qmapshack», «QMapShack» or «./QmapShack») therefore I do not have errors messages, just a plain crash...
I'm running it in Ubuntu 21.10, every thing up to date, and Qmapshack latest stable release. Thanks a lot.

**Comment by Philetjosie** [comment]
In fact, I succeded to launch it from the terminal, and here are the messages I get:

philippe@philippe-desktop:~/Applications$ ./QMapShack_1.16.1-x86_64_Ubuntu-18.04_2a7ebeaac078873f63fb33ea9709c784.AppImage 
+ set -e
+ echo -e '\n\n--- QMapShack.AppImage starting\n\n'


--- QMapShack.AppImage starting


+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/tmp/.mount_QMapShdoi2SZ/usr/bin
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/tmp/.mount_QMapShdoi2SZ/usr/bin
+ link=/home/philippe/Applications/rout
+ trap cleanup EXIT
+ '[' -L /home/philippe/Applications/rout ']'
+ ln -s /tmp/.mount_QMapShdoi2SZ /home/philippe/Applications/rout
+ /tmp/.mount_QMapShdoi2SZ/usr/bin/qmapshack
2022-02-20 12:37:54.034 [warning] "no file found for translations '/tmp/.mount_QMapShdoi2SZ/usr/translations/qt_fr' (using default)."

(qmapshack:9923): Gtk-WARNING **: 12:38:20.805: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Format d’image non reconnu (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Format d’image non reconnu (gdk-pixbuf-error-quark, 3)
/tmp/.mount_QMapShdoi2SZ/AppRun.wrapped : ligne 28 :  9923 Abandon                 (core dumped) ${APPDIR}/usr/bin/qmapshack "$@"
+ cleanup
+ '[' -L /home/philippe/Applications/rout ']'
+ rm /home/philippe/Applications/rout
+ echo -e '\n\n--- QMapShack.AppImage  finished\n\n'


--- QMapShack.AppImage  finished

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
