### ISSUE TITLE
Disappearing track near 180° East

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#493]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

Attached is a GPX file with a track located near but west of 180° East. This track is correctly painted with one zoom level and one map position. This track disappears when moving or zooming the map slightly.

The attached snapshot consist of 3 parts: the upper left and the lower parts are equal and show the track. The upper right snapshot was taken after slight move of the map. Here, the track can't be seen.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Load attached GPX file
2. Double click the track to position it on the map
3. Check if it can bee seen
4. Move map or zoom it a bit to see the track appearing resp. disappearing

Can be reproduced!

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

The track should be always on the map

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

Attached

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

GPX file + snapshots

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

None

### Desktop
[comment]: # (please complete the following information)

 - OS: Windows 10
 - QMapShack Version:  1.16.1, latest dev
 - Window Manager:  [e.g. KDE, GNOME]

### Additional context
[comment]: # (Add any other context about the problem here)

My impression is that 180° East is somehow involved in the problem. Extreme case: Move track to the east so that right border is at 180° East.

[NZ.zip](https://github.com/Maproom/qmapshack/files/8110257/NZ.zip)

**Comment by kiozen** [comment]
This is a known problem at 180°. A correct rendering would make the already quite complex code even more complex. 

A workaround is to use a projection that takes 180° as center. I do not have an EPSG code at hand but those projections exist.

**Comment by wthaem** [comment]
Thanks for the quick answer. I wasn't aware that this is known.
