### ISSUE TITLE
Setup Travis CI to automatically build AppImage (portable binary package for Linux)

### ISSUE THREAD

**Issue by Symbian9** [Maproom/qmapshack#50]
Lets setup Travis CI for auto-build *AppImage* (portable package for Linux) for each commit:

0. [ ] Create `.travis.yml` - https://github.com/Maproom/qmapshack/blob/master/.travis.yml
1. https://github.com/appimage/AppImageKit
1.1. https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/linuxdeploy
2. https://github.com/probonopd/uploadtool
3. [ ] Enable Travis CI pushing to GitHub releases for this repo.

For example, take a look on *LeoCAD* `.travis.yml` implementation:

- https://github.com/leozide/leocad/blob/master/.travis.yml

And here is what resulted builds would look like:

- https://github.com/leozide/leocad/releases/tag/continuous

For any support:

- https://docs.appimage.org/user-guide/faq.html#question-where-do-i-get-support

**Comment by kiozen** [comment]
You are welcome to fork the repository and setup everything to provide AppImages. If it proves to be stable and reliable I might consider integrating it into the main repository.

**Comment by kiozen** [comment]
Btw, as this is another ticket that totally ignores the template, please do so in the future. I will have to close these tickets as they are a bad example and encourage others to do the same. This will end up in the same chaotic ticket style as we had on BitBucket. That's why I will enforce it.
