### ISSUE TITLE
Setting up BRouter offline failed

### ISSUE THREAD

**Issue by FTno** [Maproom/qmapshack#502]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

Setting up BRouter for offline use didn't work.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

Tested installing QMapShack from repository instead of using the AppImage.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Go to 'BRouter (online)'
2. Clicked on the 'Setup' button
3. Selected 'local installation'
4. Selected Create new BRouter installation (Java detected)
5. In the download dialog selected and downloaded v 1.6.3, download worked fine. But the 'Next' button is disabled.

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

The Next button to work

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: Linux Mint 20.3
 - QMapShack Version: QMapShack_1.16.1-x86_64_Ubuntu-18.04.AppImage
 - Window Manager:  Cinnamon

### Additional context
[comment]: # (Add any other context about the problem here)

Installing QMapShack (v. 1.14) from repository instead of using the AppImage resulted in exactly the same issue.

BTW - using BRouter online worked fine.

**Comment by kiozen** [comment]
I can't reproduce. If the next button is disabled something failed. But with that little information I can't tell anything.

You might want to debug yourself. The method in question should be 
``` 
CRouterBRouterSetupWizard::slotLocalDownloadButtonFinished(QNetworkReply* reply)
``` 

The next button should become active the moment 
``` 
pageLocalInstallation->emitCompleteChanged();
```
is called.

**Comment by FTno** [comment]
In the download and install log (with green text) everything seems fine with the last word 'ready'.

Since you can't reproduce and I'm not able to debug I close the issue.
