### ISSUE TITLE
BRouter 1.6.3 offline installation fails

### ISSUE THREAD

**Issue by clasatau** [Maproom/qmapshack#503]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
In the brouter offline setup window, where you have to specify the paths to brouter installation and java exe I hit the button "Add folder and install BRouter". In the following window I chose brouter-1.6.3.zip, downloaded and installed it and returned to the previous window. But there I could not hit the "next" button because it was deactivated (greyed out). Below the input field for the brouter installation path there was the information that the folder was empty. So it proposed to make a new installation.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
I managed to solve the problem. At first I had to change the path in the input field because the installation had created the subfolder brouter-1.6.3 where the java file is located. Additionally I had to rename the java file from brouter-1.6.3-all.jar to brouter.jar. Only then QMS recognized the brouter file and allowed me to press the "next" button so that I came to the profile selection and routing data download windows.

### Desktop
[comment]: # (please complete the following information)

 - OS:  Windows 10
 - QMapShack Version:   1.16.1

**Comment by mitxel-m** [comment]
I can confirm this 
I have also checked that it only happens with the new brouter 1.6.3, but not with previous versions of the brouter such as 1.6.1.

The reason is that the newer zip comes with a different folder structure and a different name for the java executable, (adding the version number).

1.6.1
![](https://i.ibb.co/ftjXt8v/Selecci-n-118.jpg)

1.6.3
![](https://i.ibb.co/sq56HXL/Selecci-n-119.jpg)

For now one should choose  brouter 1.6.1  when asked from the installer ,
 or  
install 1.6.3 and then  manually rename the folder and names , as @clasatau have done.

HTH

**Comment by wthaem** [comment]
Additionally, on Windows systems there can be an issue with Java version numbers required by BRouter - they depend on the download source (oracle.com or java.com). I failed with the latest java package downloaded from java.com but succeeded with the one from Oracle.

And there is still the annoying older issue #388 making the use of BRouter a hazard.

**Comment by ntruchsess** [comment]
I also noticed this a while ago, BRouter does now use a build-pipeline to create releases which results in different Naming-scheme. In the past BRouter-releases were manually crafted and published. I'll adjust the installer accordingly.

**Comment by kiozen** [comment]
Thx Norbert for taking care!

**Comment by kiozen** [comment]
This is linked with QMS-#502

**Comment by ntruchsess** [comment]
@kiozen : fix is ready, please see my PR https://github.com/Maproom/qmapshack/pull/512
