### ISSUE TITLE
Hybrid layers text is very small, not readable

### ISSUE THREAD

**Issue by DerekTizz** [Maproom/qmapshack#513]
When zooming MBTiles maps with hybrid layers visible hybrid text is very small, not readable. Can you add intermediate zoom levels (forex by Shift or Alt) to add smooth zooming to increase text size. Thank you
![120118526-b246ad00-c19b-11eb-8617-f10d1f8366d0](https://user-images.githubusercontent.com/29268936/164540249-256e254f-41ab-4f44-8fc4-6b7b52f812fc.jpg)
!
!

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
