### ISSUE TITLE
"Save as" to a smartphone

### ISSUE THREAD

**Issue by ventoux84** [Maproom/qmapshack#514]
Describe the bug

After creating a track, it is not possible to save it on a smartphone because the dialog window does not suggest it. 

To Reproduce

In a kde plasma environment.
Connect a smartphone to the PC and make sure it is properly mounted. If yes, it appears in Dolphin under the heading "Peripherals".

Open Qmapshack and create a track. Then try to save it to the smartphone.
A window opens to choose the destination. This windows (qt file-chooser ? ) chows the heading "Peripherals", but the smartphone does not appear in it.

However,  the text editor Kate shows the phone when you want to save a file.
    

Expected behavior

 The smartphone should appear in it, like it appears in Dolphin and Kate.

Attachments

Screenshots of the Dolphin's window  and  the window "Save as" of Kate with the phone  that appaears and Qmapshack "Save as" with the phone that does not appear. 

Desktop
HP Elitedesk Intel I5 Archlinux KDE Plasma up to date Qmapshack 1.16.1
Also tested on a VM running OpenSuse Thumbleweed Plasma up to date
![_Save as_ with Qmapshack](https://user-images.githubusercontent.com/56974650/166873394-aa53b38c-fd1c-4ed4-a1f6-69f0ff09e2d6.png)
![Dolphin](https://user-images.githubusercontent.com/56974650/166873425-1d4e3342-b275-4fa5-8906-e8c9f6b8726f.png)
![_Save as_ with Kate](https://user-images.githubusercontent.com/56974650/166873448-efd4ea1e-9300-4091-b01b-c260c761cbe4.png)
.

**Comment by kiozen** [comment]
This is not a problem of QMapShack. It is a problem how your system is setup. The native Qt file dialog displays the complete filesystem and all block devices found on the system.

Electronic devices like smartphones are often accessed different. The protocol is called MTP. There are two ways to deal with MTP devices. KDE and other window managers provide their own implementation to handle the protocol. As QMapShack is a portable software it can't integrate these OS/window manager specific mechanisms. Else it would be a GTK or KDE application only.

The second way is to integrate the MTP devices as a block device on OS level. For Linux there is `mtp-tools` and  `mtpfs`. Just google for those packages and you will find tutorials. Once the phone is mounted to your filesystem you can access it with QMapShack.


Btw why is it that hard to simply use the issue templates as provided. It's more work to remove all the template code and to reinvent it than simply using it. You removed all the formatting provided by the template. Now your request is more or less an unstructured  ascii mashup.

**Comment by ventoux84** [comment]
Thank you for these explanations and I apologize for the bad layout.

I found this page that explains how to mount the smartphone other than by Dolphin.
It works, but it is an additional operation that you don't have to do in other EDs. This is not a good point for KDE.
https://askubuntu.com/questions/1346885/how-to-access-mount-android-drive-in-kubuntu-20-04-with-other-file-manager-than

**Comment by kiozen** [comment]
Imho this is also not an issue of KDE. It's how your Linux is configured. Some distributions install MTP support right on the spot some don't. There are reasons for both approaches.

If you Google a bit more you should find tutorials on how to do the mount automatically.  So it's all about how you configure your Linux. 

I assume the topic is solved and close it. Reopen if there is anything left to do.
