### ISSUE TITLE
Unable to close welcome tab at the beginning

### ISSUE THREAD

**Issue by adryen31** [Maproom/qmapshack#515]
Hello,

I installed QMapShack on ubuntu 20.04 and after the first opening a Welcome Tab is displayed, but after a lot of actions to get to farm the welcome window and to get to see the waypaint card behind, I can’t ... in addition I closed and opened the software several times in order to no longer be in welcome mode ... how can I-I close this intanpestive window ..
![welcome](https://user-images.githubusercontent.com/1407536/167289811-488efbcd-fa25-48dd-bbca-bf1ce09e9f62.png)
![welcome](https://user-images.githubusercontent.com/1407536/167289860-7fe73ed5-c39a-456b-abd0-2b281c8f4f5a.png)

Thank a lot and best regards

Adrien.

**Comment by pingurus** [comment]
It is literally written right next to the arrow you drew. You have to activate a map.

Also, why is it so hard to read and use the template? https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
