### ISSUE TITLE
GPX-tracks are not displayed if lon or lat are invariant over the entire track

### ISSUE THREAD

**Issue by kaskasapakte** [Maproom/qmapshack#517]
### Describe the bug

If open a gpx-track that runs exactly in north-south or east-west direction, it will not be displayed. If changing only one track point minimally, the track is visible on the map.

### What have you done to circle down the problem?

The same behavior in QMapShack 1.14.0 and 1.16.1.

Checked gpx-files in question with GpsPrune, Viking and JOSM. There they were displayed.

### To Reproduce

1. Open attached files with QmapShack.
2. The `*_not_displayed.gpx` files will be not shown at the map.

### Expected behavior

GPX-tracks should be displayed even if longitude or latitude do not change between track points.

### Attachments

[gpx_files.zip](https://github.com/Maproom/qmapshack/files/8697975/gpx_files.zip), contains:

- `meridian_displayed.gpx`
- `meridian_not_displayed.gpx`
- `polarcircle_displayed.gpx`
- `polarcircle_not_displayed.gpx`

### Desktop

 - OS: Manjaro Linux 21.2.6
 - Kernel: 5.17.6-1
 - QMapShack Version: 1.16.1
 - Window Manager: xfce, xfwm

and

 - OS: Xubuntu 20.04.4 LTS
 - Kernel: 5.13.0-40
 - QMapShack Version: 1.14.0
 - Window Manager: xfce, xfwm

**Comment by kiozen** [comment]
Bug confirmed. Root cause: Bounding box has not area -> Track is never within bounding box
