### ISSUE TITLE
Editable Timestamps for waypoints

### ISSUE THREAD

**Issue by mfbehrens99** [Maproom/qmapshack#518]
### Is your feature request related to a problem? Please describe.
[comment]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] )
I am keeping track of the places where I stayed in a GPX file that I edit with QMapShack. GPX Files have (as far as I know) a timestamp assosiated to each point. I think it would be very practical to have an edit button for the timestamp.

### Describe the solution you'd like
[comment]: # (A clear and concise description of what you want to happen.)
When viewing a point the timestamp is blue (like the name, description, ...). When you click on it a editor opens. Best case would be a full datetime editor, much easiser to implement would be a plain text dialog.

### Describe alternatives you've considered
[comment]: # (A clear and concise description of any alternative solutions or features you've considered.)

As I pointed out a plain texbox would also be okay

### Give a reason why someone else should spend time on that request
[comment]: # (Keep in mind that you ask others to spend their spare time for your request. Good reasons are if you are able to prove that the request solves a fundamental problem for everyone, or the request is of general interest for many users. Bad reasons are you just want it to have that way, or argue that software xyz does it.)

In my opinion the would greatly improve projectes where you have to keep track of geopoints in a specific time order.

### Additional context
[comment]: # (Add any other context or screenshots about the feature request here.)

**Comment by kiozen** [comment]
What? You want to edit a timestamp that is recorded by a device with the most precises clock on earth included? 

If there is a timestamp in the GPX file recorded by a GPS device this is the one and only valid timestamp for that point. Changing it makes n o sense at all.

**Comment by mfbehrens99** [comment]
Of course this does not make sense for continous tracks. But if you are placing individual markers on the map then it makes sense. Right now I keep track of the point in time by writing it into the comment while the gpx time field stores the creation timestamp

**Comment by kiozen** [comment]
Ah, ok you are talking about waypoints. That makes sense.

**Comment by kiozen** [comment]
Please test PR

**Comment by mfbehrens99** [comment]
Unfortunately I am not able to build the app because I am not in c++. I had a quick look at the source code and it looked like what I was thinking about. Thank you that you took the time to implement the feature.

**Comment by kiozen** [comment]
Thanks for expecting other to work for you. I am not in testing, so this ticket is blocked.
