### ISSUE TITLE
Updated elevation profile when editing a track

### ISSUE THREAD

**Issue by frankystone** [Maproom/qmapshack#524]
It would be nice to have the elevation profile instantly updated when editing tracks. Currently the elevation profile is only updated if i save the edited track.

Also i am using the OpenTopoMap for planning a route/track it's sometimes difficult to find out how steep parts of the track may be. An instantly updated elevation profile would also be useful if other maps than topo maps are used.

Thanks to all developers of this great software!

OS: archlinux
QMapShack version: 1.16.1

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
