### ISSUE TITLE
Crash due to `std::bad_alloc` while opening an (big) IMG map

### ISSUE THREAD

**Issue by okvik** [Maproom/qmapshack#527]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

I'm trying to open (activate) the following [.img map](https://my.hidrive.com/api/file?attachment=true&pid=b1563197746.80198&access_token=0e4tHOrBbzTt2eQiiQCm) but getting the crash:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

The map is rather big: 4.4GB, and includes the DEM data. The same map without the DEM data, which weighs 3.0GB opens just fine. Another map, with DEM data but also 3.0GB big opens just fine as well.

This bit of testing leads me to believe the size of the file is the issue. In particular the maps that are >4GB in size.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
 
I've tried opening a few different maps with / without DEM data, with sizes greater and less than 4GB.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Download the [map](https://my.hidrive.com/api/file?attachment=true&pid=b1563197746.80198&access_token=0e4tHOrBbzTt2eQiiQCm)
2. Reload Maps
3. Try to activate the map
4. The application crashes with the above error

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

The map opens.

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

I'm sorry, but I've quit trying to build QMapshack after spending an hour fighting my way through the build dependency hell.

### Desktop
[comment]: # (please complete the following information)

 - OS: Ubuntu 22.04
 - QMapShack Version:  1.16.1 (from apt) 
 - Window Manager:  KDE

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by kiozen** [comment]
The implementation in QMapShack is definitely limited to 32 bit and to the same applies to Garmin devices. Therefore the crash is expected.

**Comment by okvik** [comment]
Garmin not supporting these bigger maps seems weird, since the map author clearly was making them for Garmin specifically (check the [homepage](https://gravelmaps.de/en/) if you care) and apparently used their software to do it as well.

Perhaps the 32-bit limitation is something that applies to older devices? I've no idea, and I don't have a Windows PC at hand to try and open the map in Basecamp, nor do I own a Garmin device.

In any case, is there some way to convert the map to some format that QMapShack would be happy with?

**Comment by kiozen** [comment]
Well maybe Garmin changed something. Haven't had a look into that format for years, now. 

The only way to make QMapShack happy is to reduce the size. There are tools to reassemble Garmin img files available e.g. http://www.gmaptool.eu/en/content/gmaptool

Or you try to fix the code of QMapShack.

**Comment by okvik** [comment]
Alright, I'll try my luck with GMapTool. Thanks for the tip.

**Comment by kiozen** [comment]
I close the ticket for now. If you want to give it a try to fix the code you can reopen the ticket.
