### ISSUE TITLE
failed: "Error transferring https://tile.openstreetmap.org/13/4187/2755.png - server replied: Blocked"

### ISSUE THREAD

**Issue by jcz7021** [Maproom/qmapshack#534]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
Openstreetmap tiles are not displayed !

When having a look at the log file (org.qlandkarte.QMapShack.log) this is what we get:
failed: "Error transferring https://tile.openstreetmap.org/13/4187/2755.png - server replied: Blocked"

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
I've tried to change the user agent value inside the tms file with the latest value of Google Chrome

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Create a *.tms file by download the "OpenStreetMap.txt" file below and rename it to "OpenStreetMap.tms"
[OpenStreetMap.txt](https://github.com/Maproom/qmapshack/files/9078947/OpenStreetMap.txt)
3. Activate the map inside QMapShack
4. Tiles are not displayed

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)
Tiles should be displayed

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)
![image](https://user-images.githubusercontent.com/42817564/178143016-6da46339-c8aa-4fb8-9c02-45a262f7d0be.png)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: Windows 11
 - QMapShack Version:   1.16.1

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by wthaem** [comment]
Issue confirmed. The above mentioned tile can be downloaded without any problems in Firefox. A month ago or so this TMS/URL has been working as expected in QMS.

**Comment by wthaem** [comment]
Set the user-agent to "QMapShack" and it will work again!

**Comment by jcz7021** [comment]
Indeed thanks for the quick fix :-)

I'll try to contact the owner of the zip at http://www.mtb-touring.net/qms/onlinekarten-einbinden/ specified in https://github.com/Maproom/qmapshack/wiki/DocQuickStartEnglish#download-files-from-internet

Because the user agent specified in his OpenStreetMap.tms is "Agent Smith" and this one is not working either
