### ISSUE TITLE
Changed drag`n drop in workspace

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#542]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

Assume you have 2 (GPX) projects in the workspace. 

* Be sure, both projects are selected (tracks can be seen in map window) and closed (no tracks visible in workspace)
* Drag`n drop upper project on lower one
* Result obtained up to and including test version `QMS-256`: projects change their order
* Result obtained with commit `b39b080b82a05aa0fd981f597a99911a4c04f803 (origin/dev, origin/HEAD, dev), [QMS-518] Enable edit for timestamps of waypoints`:
    * Order of projects **not changed**
    * A new third project appears 
        * with name of the dragged (upper) project
        * without content
        * without context menu
        * close first 2 projects (new third project still open and can't be closed due to missing context menu) and restart QMS: no project in workspace
    * Adding more projects, more empty projects can be created with drag`n drop but without a chance to change the project order.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

Compared drag`n drop in above mentioned 2 QMS versions

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

see description above

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

Both QMS version should have the same drag`n drop behavior: The order of projects should change.

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

None

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

None

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

None

### Desktop
[comment]: # (please complete the following information)

 - OS: Windows 10, Qt 5.15.2 (in both QMS versions)
 - QMapShack Version: see above
 - Window Manager:

### Additional context
[comment]: # (Add any other context about the problem here)

None

**Comment by kiozen** [comment]
confirmed
