### ISSUE TITLE
Missing libarrow writes an error but with it QMS fails to start

### ISSUE THREAD

**Issue by frankystone** [Maproom/qmapshack#543]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
Starting QMS from a console shows several Errors and warnings. One Error is a missing lib called libarrow.so.800:

~~~~
$:> qmapshack -d
2022-08-07 10:56:09.940 [debug] Log configuration: logfile= "/tmp/org.qlandkarte.QMapShack.log" write to file= false debug output= true
ERROR 1: libarrow.so.800: cannot open shared object file: No such file or directory
ERROR 1: libarrow.so.800: cannot open shared object file: No such file or directory
ERROR 1: libarrow.so.800: cannot open shared object file: No such file or directory
ERROR 1: libarrow.so.800: cannot open shared object file: No such file or directory
~~~~

So i installed arrow…
With installed arrow the lib is there:

~~~~
$:> locate libarrow
/usr/lib/libarrow.so
/usr/lib/libarrow.so.800
/usr/lib/libarrow.so.800.1.0
[...]
~~~~

but QMS fails to start:

~~~~
$:> LC_ALL=C qmapshack -d
2022-08-07 10:44:36.484 [debug] Log configuration: logfile= "/tmp/org.qlandkarte.QMapShack.log" write to file= false debug output= true
Ungültiger Maschinenbefehl (Speicherabzug geschrieben)
~~~~

After uninstalling arrow, QMS starts and all is fine, except the error shown in the console.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
Because an error is shown in console output i tried to install [arrow](https://archlinux.org/packages/community/x86_64/arrow/).

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Install arrow
2. Try to start QMS

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)
Either the console output is wrong or QMS does not work well with arrow? Or both?

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

~~~~
(gdb) run
Starting program: /home/kaputtnik/Quellcode/build_QMapShack/bin/qmapshack 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffd864c6c0 (LWP 2687)]
[New Thread 0x7fffd5ecb6c0 (LWP 2688)]

Thread 1 "qmapshack" received signal SIGILL, Illegal instruction.
0x00007fffc69c2bc3 in ?? () from /usr/lib/libarrow.so.800
~~~~

### Desktop
[comment]: # (please complete the following information)

 - OS: archlinux
 - QMapShack Version:  Both, Version 1.16.1 and current dev
 - Window Manager:  KDE

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by kiozen** [comment]
This happens when there is a mismatch between libraries and the executable. The system has to provide the very same versions of the libraries the executable has been linked to when it was compiled. Please make sure all libraries are properly installed and QMapShack has been compiled on your system.

As this is out of the scope of this repository (this is software development) I close the ticket.
