### ISSUE TITLE
Qmapshack appimage do not work in Linux Mint 21

### ISSUE THREAD

**Issue by PiusV** [Maproom/qmapshack#544]
Hi,
I update Linux Mint 20.3 to Linux Mint 21. Since them QmapShack Appimage does nor work. I got the following message when I try to start the Appimage in the terminal session.

--- QMapShack.AppImage starting

+ export PATH=/home/pius/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/tmp/.mount_QMapShQioaJX/usr/bin
+ PATH=/home/pius/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/tmp/.mount_QMapShQioaJX/usr/bin
+ link=/home/pius/AppImage/QMapShack/rout
+ trap cleanup EXIT
+ '[' -L /home/pius/AppImage/QMapShack/rout ']'
+ ln -s /tmp/.mount_QMapShQioaJX /home/pius/AppImage/QMapShack/rout
+ /tmp/.mount_QMapShQioaJX/usr/bin/qmapshack
/tmp/.mount_QMapShQioaJX/usr/bin/qmapshack: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full
+ cleanup
+ '[' -L /home/pius/AppImage/QMapShack/rout ']'
+ rm /home/pius/AppImage/QMapShack/rout
+ echo -e '\n\n--- QMapShack.AppImage  finished\n\n'

--- QMapShack.AppImage  finished

Regards
Pius

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
