### ISSUE TITLE
After update Linux Mint Cinnamon from 20.03 to Linux Mint Cinnamon 21 the flatpck Qmapshack doesn't work

### ISSUE THREAD

**Issue by PiusV** [Maproom/qmapshack#545]
### Describe the bug
[comment]: # After update Linux Mint Cinnamon from 20.03 to Linux Mint Cinnamon 21 the flatpck Qmapshack doesn't work

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Go to 'the Folder where the Appimage is storde'
2. Click on 'the Appimage'
3. Control the rights 'They are 777'
4. Start the Appimage in the Terminal Session
5. See error following point

### Expected behavior
[comment]: # The Appimage Qmapshack doesen't start

### Screenshots
[comment]: # (Qmapshack did not start, no screen possible, following text in terminal section)
--- QMapShack.AppImage starting
+ export PATH=/home/pius/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/tmp/.mount_QMapShQioaJX/usr/bin
+ PATH=/home/pius/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/tmp/.mount_QMapShQioaJX/usr/bin
+ link=/home/pius/AppImage/QMapShack/rout
+ trap cleanup EXIT
+ '[' -L /home/pius/AppImage/QMapShack/rout ']'
+ ln -s /tmp/.mount_QMapShQioaJX /home/pius/AppImage/QMapShack/rout
+ /tmp/.mount_QMapShQioaJX/usr/bin/qmapshack
/tmp/.mount_QMapShQioaJX/usr/bin/qmapshack: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full
+ cleanup
+ '[' -L /home/pius/AppImage/QMapShack/rout ']'
+ rm /home/pius/AppImage/QMapShack/rout
+ echo -e '\n\n--- QMapShack.AppImage  finished\n\n'

--- QMapShack.AppImage  finished

### Attachments
[comment]: # (see text above)

### Tracebacks
[comment]: # (not possible)

### Desktop
[comment]: # (please complete the following information)

 - OS: [Linux Mint Cinnamon 21]
 - QMapShack Version:   [1.16.1]
 - Window Manager:  [e.g. Cinnamon]

### Additional context
[comment]: # (none)

**Comment by kiozen** [comment]
@kkarsten62 can you please look into this.

**Comment by kkarsten62** [comment]
I never tested Mint Distros with the QMapShack AppImages. You can try another AppImage from the development download wiki page: https://github.com/kkarsten62/QMapShack.AppImage/wiki
Or you can build your own AppImage as described here: https://github.com/kkarsten62/QMapShack.AppImage.

**Comment by kiozen** [comment]
As this is about packaging, not a real issue of QMapShack and there seems to be a solution I close that ticket.
