### ISSUE TITLE
Qmap Tool Version 1.16.1 Error

### ISSUE THREAD

**Issue by arverne63** [Maproom/qmapshack#546]
Good morning,
At the start of QMap Tool, as well as at each image load the error message below is displayed.
![erreur qmapstool](https://user-images.githubusercontent.com/6421496/183716329-3269decc-5ad6-45e3-9bd4-03c266c785d7.jpg)
Please let me know if there is a possibility to make this message disappear (note that this message did not exist in previous versions of Qmap Tool).
Cordially.
Arverne63

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

https://github.com/Maproom/qmapshack/issues/507

**Comment by arverne63** [comment]
Bonsoir,

Merci pour votre réponse, je n'ai pas compris comment résoudre cette
erreur. je vais repasser à une version précédente.
Bonne soirée.
Cordialement
