### ISSUE TITLE
QMS freezes on zoom when activating multi-layerd online maps

### ISSUE THREAD

**Issue by frankystone** [Maproom/qmapshack#547]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
When zooming in QMS does not react anymore. The blueish circling circle in the middle of the mapview stops circling and the only thing one can do is to kill the process.
This happens if at least two projects are open in the workspace. Or if one of those projects gets deactivated.
I used database projects.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
Current version 1.16.1 works fine, [da8c041](https://github.com/Maproom/qmapshack/commit/da8c0414e495d1443ed58727e07073045323db71) hangs when zooming in.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

Activated waymarkedtrails.tms and openstreetmap_DE.tms

1. double click on a track in the workspace to get the entire track in the screen
2. use the mouse wheel to zoom in/out the map

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)
QMS should zoom without hanging.

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

Console output stops at 
~~~~
`2022-08-11 9:02:10.455 [debug] CGisItemTrk::updateVisuals() "Zur Wanderung" "findWaypointsCloseBy()"`
~~~~
Note the the track called "Zur Wanderung" may be a part of a deactivated database project (not a part of projects in the workspace anymore). That is: If you have two projects in the workspace open and close one, QMS seems to handle the closed project like if it is open. Only if you close a project, and restart QMS, the tracks in the closed project  are not handled by QMS anymore. But this might be an other issue?

Although no crash here is a complete backtrace: [bt.txt](https://github.com/Maproom/qmapshack/files/9306924/bt.txt)

### Desktop
[comment]: # (please complete the following information)

 - OS: archlinux
 - QMapShack Version:  current dev [da8c041](https://github.com/Maproom/qmapshack/commit/da8c0414e495d1443ed58727e07073045323db71) 
 - Window Manager:  KDE

### Additional context
[comment]: # (Add any other context about the problem here)

Maybe related: #357

**Comment by kiozen** [comment]
I can't reproduce that. And the backtrace only reveals that the mutex gets locked but not where another thread is locking it.

**Comment by frankystone** [comment]
Also can't reproduce anymore, so i am closing this.

**Comment by frankystone** [comment]
QMapShack version is now d6cd0c2c

I ran into this again. After some investigation it seems it is only related to `Waymarkedtrails.tms`, not to other `*.tms` files. The only difference to e.g. `OpenTopoMap.tms` is that Waymarkedtrails.tms has layers. So i made new files out of it each containing only one layer, e.g.:
~~~~
<TMS>
<Layer idx="0">
<Title>Waymarked Trails Cycling</Title>
<MinZoomLevel>1</MinZoomLevel>
<MaxZoomLevel>19</MaxZoomLevel>
<ServerUrl>https://tile.waymarkedtrails.org/cycling/%1/%2/%3.png</ServerUrl>
</Layer>
<Copyright>Map data: (c) OpenStreetMap contributors, ODbL CC-BY-SA | Trails by http://www.waymarkedtrails.org/ </Copyright>
</TMS>
~~~~

Activating them let QMS not hang on zooming anymore :smile: 

Maybe this has something to do with caching of tiles, because with Waymarkedtrails.tms there is only one cache folder for all layers. With one-layered tms-files each tms-file get its own cache folder.

Don't know what to do with this issue. I have solved it by myself, but i reopened it because i think this needs some investigation. Feel free to close it again.

**Comment by wthaem** [comment]
(QMS on Windows)

* ***Normal slow scrolling*** with mouse wheel: no problem - QMS doesn't hang. I can see waymarked trails loaded from 6 layers located between Spain and the Arctic on all zoom levels.
* ***Very rapid scrolling*** with mouse wheel (maybe, with short interrupt while scrolling): QMS displays 3 circles (not rotating anymore) and hangs. The number of tiles to be loaded doesn't change anymore.

My vague suspicion: This is an old Windows problem with mouse driver (event handling?) + QMS. We had similar discussions in connection with (still existing) crashes of BRouter (call stack didn't give any insight) and with handling of big numbers of POIs. Nobody could find a satisfactory explanation up to now.

**Comment by kiozen** [comment]
From the mailing list:

```
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff4dcefe5 in QBasicMutex::lockInternal() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ffff4dcf2f3 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x0000555555ada91a in QMutexLocker::QMutexLocker (m=0x7fffd8009970, this=0x7fffffffce00)
   at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h:233
#4  QMutexLocker::QMutexLocker (m=0x7fffd8009970, this=0x7fffffffce00) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h:238
#5  CMapTMS::getLayers (this=0x7fffd80098c0, list=...)
   at /local/QMS-Programs-Installation-Stuff/QMapShack/src/qmapshack/map/CMapTMS.cpp:154
#6  0x0000555555ace24f in CMapPropSetup::slotPropertiesChanged (this=0x555557b04710)
   at /local/QMS-Programs-Installation-Stuff/QMapShack/src/qmapshack/map/CMapPropSetup.cpp:102
#7  0x00007ffff4ff3793 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00005555557b1a49 in IDrawContext::sigScaleChanged (this=this@entry=0x5555574e15c0, _t1=...)
   at /local/QMS-Programs-Installation-Stuff/build_QMapShack/src/qmapshack/qmapshack_autogen/KGLXD3X7AI/moc_IDrawContext.cpp:20
8
#9  0x00005555557f9a62 in IDrawContext::zoom (this=0x5555574e15c0, idx=16)
   at /local/QMS-Programs-Installation-Stuff/QMapShack/src/qmapshack/canvas/IDrawContext.cpp:168
#10 0x00005555557f9a99 in IDrawContext::zoom (this=<optimized out>, in=<optimized out>,  
   needsRedraw=@0x555556b41aa4: CCanvas::eRedrawNone)
   at /local/QMS-Programs-Installation-Stuff/QMapShack/src/qmapshack/canvas/IDrawContext.cpp:153
#11 0x00005555557f1651 in CCanvas::setZoom (this=0x555556b41a60, in=<optimized out>, needsRedraw=<optimized out>)
   at /local/QMS-Programs-Installation-Stuff/QMapShack/src/qmapshack/canvas/CCanvas.cpp:1048
#12 0x00005555557f17f5 in CCanvas::wheelEvent (this=0x555556b41a60, e=0x7fffffffd250)
   at /local/QMS-Programs-Installation-Stuff/QMapShack/src/qmapshack/canvas/CCanvas.cpp:644
#13 0x00007ffff5aee4ee in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff5aab713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
  from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff5ab3833 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff4fbbe3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff5b097d2 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff5b0b1ba in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff5aab713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
  from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff4fbbe3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff539e117 in QGuiApplicationPrivate::processWheelEvent(QWindowSystemInterfacePrivate::WheelEvent*) ()
  from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#22 0x00007ffff5377a2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
  from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#23 0x00007fffdcfa9d6e in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#24 0x00007fffe81a4d3b in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007fffe81fa258 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007fffe81a23e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff50150b8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
  from /lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff4fba75b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff4fc2cf4 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00005555557ae22f in main (argc=<optimized out>, argv=<optimized out>)
   at /local/QMS-Programs-Installation-Stuff/QMapShack/src/qmapshack/main.cpp:75
(gdb)
```

**Comment by runrun1234** [comment]
Thanks, no more freezing on my side :)
