### ISSUE TITLE
Blending in and out Items in a project.

### ISSUE THREAD

**Issue by Yirre** [Maproom/qmapshack#554]
### Is your feature request related to a problem? Please describe.
[comment]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] )

### Describe the solution you'd like
[comment]: # (A clear and concise description of what you want to happen.)

There are check boxes for projects to blend them in/out but not for items in a project It would be convenient when items have also such a check box, Especially when many items are cluttering up the map(display)!

### Describe alternatives you've considered
[comment]: # (A clear and concise description of any alternative solutions or features you've considered.)

Making every item a project.

### Give a reason why someone else should spend time on that request
[comment]: # (Keep in mind that you ask others to spend their spare time for your request. Good reasons are if you are able to prove that the request solves a fundamental problem for everyone, or the request is of general interest for many users. Bad reasons are you just want it to have that way, or argue that software xyz does it.)

I just think it is a nice addition to the easy use of your program.

### Additional context
[comment]: # (Add any other context or screenshots about the feature request here.)

**Comment by frankystone** [comment]
If you use database projects you can turn off specific items in a project. Turning off is done in the database window.

See: https://github.com/Maproom/qmapshack/wiki/DocGisDatabase and the next pages in this wiki

**Comment by Yirre** [comment]
frankystone thank you for the quick response,
Yes, it works but now I have to switch between Database panel and Workspace panel, So IMH I see this as a nice workaround.
When I*m working I like everything in the WORKspace. Thus I keep my request if it is not to much asked for.
