### ISSUE TITLE
[QMS-557] Splitting a "long" track in multiple tracks

### ISSUE THREAD

**Issue by kaiserls** [Maproom/qmapshack#557]
### The parent ticket
[comment]: # (Add ticketnumber behind QMS-# )

QMS-#557

### What do you plan to do
[comment]: # (Describe roughly what you want to do.)
I would like to implement a feature to split a track into multiple tracks.
This allows to load long tracks on old gps devices, which only allow a small number of track points per track, e. g. 500.
This feature is somewhat similar to the "cut" feature but removes the necessity to choose the cut point by hand, which may be hard to get right if the density of track points is varying, and makes it easier to process very long tracks, which would need multiple cuts.

### The result will be
[comment]: # (A list of goals that have to be achieved to consider the ticket as done.)
- [ ] Implement dialog to ask for number of cuts
- [ ] Implement cut algorithm
- [ ] Write "glue" code
- [ ] Design new icon

### Additional comments
- I will provide a pull request
- I am happy about suggestions for improvements

Could one of the developers tell me, if this pull request has a chance to be approved?
Have a nice weekend!
Greetings Lars

![image](https://user-images.githubusercontent.com/71793357/189505437-90d96234-1b15-4e13-b2b3-8381dd801e12.png)

![Screenshot from 2022-09-11 01-43-15](https://user-images.githubusercontent.com/71793357/189505412-acefcae5-99d1-4838-815e-f19546ccf53f.png)

**Comment by kiozen** [comment]
Yes it will be approved. But make it a track filter instead of another stand alone dialog. Add it to the miscellaneous section. There is already a cutting tool for laps.

**Comment by kiozen** [comment]
Closing this one as it is done. But there is a regression. https://github.com/Maproom/qmapshack/issues/560
