### ISSUE TITLE
Missing trackpoints after splitting a track

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#560]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

After applying the "Split track into multiple shorter tracks" filter to a track the union of the shorter tracks can be smaller than the original track.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

1. Create a track with 5 trackpoints.
1. Select "3" as number of tracks in the mentioned track filter.
1. Run the filter and save the new tracks.
1. The last trackpoint of the original track can't be found in the union of the new tracks.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

See previous point

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

The union of the new tracks must be the original track, i.e. the union of all trackpoints of the new tracks must be the set of all trackpoints of the original track.

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

None

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

None

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

None

### Desktop
[comment]: # (please complete the following information)

 - OS: Windows 10
 - QMapShack Version: 
 
     ~~~
     commit ff9ac6dde35e1c1836f2229e76bf47653cd36e3c (origin/dev, origin/HEAD, dev)
     Author: Lars Kaiser <lars.g.kaiser@gmx.de>
     Date:   Sat Sep 17 13:07:13 2022 +0200

     [QMS-557] Simplify filterSplitTrack
     ~~~
     
 - Window Manager: Windows

### Additional context
[comment]: # (Add any other context about the problem here)

When setting the number of new tracks to 1,2, or 4 the bug doesn't happen.

**Comment by kiozen** [comment]
@kaiserls can you please have a look

**Comment by wthaem** [comment]
@kaiserls: Be careful when changing your algorithm: tracks should have 2 points or more!

**Comment by kaiserls** [comment]
You are right with your reports. I shouldn't have hurried with rewriting the splitting filter.

I fixed the algorithm and also distribute the points more evenly over the tracks now. I tested the algorithm with a python script and the program manually. Should I make a new pull request referencing this issue?

**Comment by kiozen** [comment]
Yes, please.
