### ISSUE TITLE
Copy a track and editing the new one opens the wrong track

### ISSUE THREAD

**Issue by beedaddy** [Maproom/qmapshack#561]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

In a (DB-) project with two tracks: Copying (and cloning) the second one and then editing the resulting track (in order to rename it) opens two (!) tabs. The then active tab is not the new track but the first in the track list. 

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

Sorry, I can't tell if this is a new bug or if it exists in previous versions.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Open an database project with two tracks
2. Right-click on the second track and click on "Copy to …"
3. Select the same project and click "OK"
4. Select "Create a clone"
5. Right-click on the new track and select "Edit …"

Now, two (!) tabs open and the active one has data from the first (!) track in the list.

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

Just one tab should open with the correct data (the name of the new track etc.)

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

https://user-images.githubusercontent.com/3264939/190991685-49f815e9-7420-4857-b361-49f70f146157.mp4

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: Arch Linux
 - QMapShack Version:   1.16.1
 - Window Manager:  KDE Plasma (Wayland)

### Additional context
[comment]: # (Add any other context about the problem here)

The problem does **not** occur when I start QMapShack in console with LC_ALL=en : `LC_ALL=en qmapshack`. But it occurs when I open it the "normal" way (with German translation).

**Comment by kkarsten62** [comment]
I can't reproduce it with my MYSQL/MariaDB server database and a simple test project. Did you check it with an another test project?

**Comment by beedaddy** [comment]
@kkarsten62 I forgot to mention that I use SQLite. Yesterday, I could reproduce it with another project. But today (on a different machine, but with the same database (Nextcloud-synced)) the behaviour shows up only with the project I used to create the screencast.

**Comment by beedaddy** [comment]
Since I can't find additional projects with this behaviour, perhaps we can close this issue. Probably something got mixed up in the database. If there is interest to look into the SQLite file, I can make it available (but not publicly).
