### ISSUE TITLE
the app won't start on Ubuntu LTS

### ISSUE THREAD

**Issue by DreadKnight** [Maproom/qmapshack#563]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
Seems there's some library missing from the package, making the app crash at start.
Would be ideal if the appimage was supporting the LTS version of Ubuntu, not some way older one.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
Had to also install libfuse2

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Marked appimage as executable
2. Ran it from terminal
3. Crashes asking for lib
4. Installed libfuse2 manually
5. Getting more errors now, something else missing, see tracebacks

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)
Want to get the app working on LTS Ubuntu by using the appimage binary.

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
```
gigi@gigi-laptop:~/Desktop$ ./QMapShack_1.16.1-x86_64_Ubuntu-18.04.AppImage 
+ set -e
+ echo -e '\n\n--- QMapShack.AppImage starting\n\n'


--- QMapShack.AppImage starting


+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/tmp/.mount_QMapShScPxR0/usr/bin
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/tmp/.mount_QMapShScPxR0/usr/bin
+ link=/home/gigi/Desktop/rout
+ trap cleanup EXIT
+ '[' -L /home/gigi/Desktop/rout ']'
+ ln -s /tmp/.mount_QMapShScPxR0 /home/gigi/Desktop/rout
+ /tmp/.mount_QMapShScPxR0/usr/bin/qmapshack
/tmp/.mount_QMapShScPxR0/usr/bin/qmapshack: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full
+ cleanup
+ '[' -L /home/gigi/Desktop/rout ']'
+ rm /home/gigi/Desktop/rout
+ echo -e '\n\n--- QMapShack.AppImage  finished\n\n'


--- QMapShack.AppImage  finished

```

### Desktop
[comment]: # (please complete the following information)

 - OS: Ubuntu 22.04.1 LTS
 - QMapShack Version:   1.16.1
 - Window Manager:  GNOME

### Additional context
[comment]: # (Add any other context about the problem here)
I usually don't compile stuff and this is for my dad, he would get even more lost.
Maybe there's some other package I can install manually and get it to run.
I've tried installing a few libgio related packages before opening up this issue.

**Comment by kkarsten62** [comment]
Have you checked the latest development builds for QMapShack.AppImage from here?
https://github.com/kkarsten62/QMapShack.AppImage
https://github.com/kkarsten62/QMapShack.AppImage/wiki
https://cloud.karl-karsten.de/s/C5xFS7eqrb5oDSF

**Comment by DreadKnight** [comment]
> Have you checked the latest development builds for QMapShack.AppImage from here? https://github.com/kkarsten62/QMapShack.AppImage https://github.com/kkarsten62/QMapShack.AppImage/wiki https://cloud.karl-karsten.de/s/C5xFS7eqrb5oDSF

I wasn't aware of those. The one provided in the wiki page there works fine for me, cheers! 👍🏻 

Now on to figuring out how to actually open a jpg and define lat/long coordinates for it to export it for OpenCPN 😕

**Comment by kkarsten62** [comment]
Fine, that QMapShack.AppImage will fits to your needs ...

A good source for further informations is also the QMapShack user mailing list.
You can subscribe here: https://sourceforge.net/projects/qlandkartegt/lists/qlandkartegt-users

Feel free to open a new ticket for:
_> Now on to figuring out how to actually open a jpg and define lat/long coordinates for it to export it as a map for OpenCPN_

Or ask in the mailing list.

@kiozen : You can close this ticket - thanks.
