### ISSUE TITLE
Extend the options for map caching (restriction of 1GB/14 days)

### ISSUE THREAD

**Issue by thefoster** [Maproom/qmapshack#575]
### Is your feature request related to a problem? Please describe.
Even in the same area one plans e.g. a tour, the corresponding map data should be able to be kept quasi-"persistent". 

### Describe the solution you'd like
So IMHO it would be an advantage to be able to extend the size to be cached (>1GB) as well as the time before the map data gets invalid (>14d).  

### Describe alternatives you've considered
There is very few software under Linux that can cache map data to be used offline. 
FoxtrotGPS has a better handling of old map data (old data is still displayed rather than nothing), but not the mass of functionalities qmapshack has.

### Give a reason why someone else should spend time on that request
There must be limits in size and/or age of map data, no question; but this should be user-configurable.
This option could save many people data over the net that wouldn't be neccesary to reload (because it hasn't changed)

**Comment by mitxel-m** [comment]
Hi @thefoster 
This topic is also in #468 . You can take a look.

**Comment by thefoster** [comment]
> Hi @thefoster This topic is also in #468 . You can take a look.

Thanks for ponting to that.
Regarding the last comment there:

>  It's not a workaround it's the way the cookie is crumbling. If you want offline maps you should use offline maps. The only reason why you want to abuse the cache is that you do not want to spend the time to prepare an offline map. wink

But e.g. Google Hybrid/Sat isn't a real offline map, nevertheless i'd like to "abuse" that feature to act like an offline map, at least for some areas that don't have a similar grade of detail about the terrain (as Google Maps).

>   See it as a benefit. Instead of starting into the wild with a Swiss map cheese you have a complete map without holes you can rely on.

Agreed for standard maps, but sometimes one may prefer the details from Google cached for a certain area.
Ideally you could choose an area (let's say 20x20km) and right-click "download/cache" this area with maximum detail level.

Right now you'll have to manually zoom in/out all of that area manually to be sure that it will be cached, which is very annoying.

**Comment by kiozen** [comment]
What you describe is called "leaching"  and is refused by most license of terms. You might want to try your luck with Mobac (https://mobac.sourceforge.io/) and create maps using the gmap format witch is supported by QMS.

I will close that ticket as it is a duplicate.
