### ISSUE TITLE
libgio-2.0.so.0: undefined symbol: g_module_open_full

### ISSUE THREAD

**Issue by Raschnow** [Maproom/qmapshack#576]
### Describe the bug
Hi, 
I can not start the Ubuntu appimage under Ubuntu 22.10.
Over terminal, there is the following output:
`
+ set -e
+ echo -e '\n\n--- QMapShack.AppImage starting\n\n'

--- QMapShack.AppImage starting

+ export PATH=/home/ubuntuer/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/tmp/.mount_QMapShkTzfHN/usr/bin
+ PATH=/home/ubuntuer/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/tmp/.mount_QMapShkTzfHN/usr/bin
+ link=/home/ubuntuer/QMapShack/rout
+ trap cleanup EXIT
+ '[' -L /home/ubuntuer/QMapShack/rout ']'
+ ln -s /tmp/.mount_QMapShkTzfHN /home/ubuntuer/QMapShack/rout
+ /tmp/.mount_QMapShkTzfHN/usr/bin/qmapshack
/tmp/.mount_QMapShkTzfHN/usr/bin/qmapshack: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full
+ cleanup
+ '[' -L /home/ubuntuer/QMapShack/rout ']'
+ rm /home/ubuntuer/QMapShack/rout
+ echo -e '\n\n--- QMapShack.AppImage  finished\n\n'

--- QMapShack.AppImage  finished
`
The error 
`symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full
`
is common and seems to be related with the building under Ubuntu 18.04.
You find a lot of these errors over google and is not espacilly a qmapshack thing.

Unfortunatelly I am to stupid to figure out a solution. Sorry for that. Can you please help me out here?

### What have you done to circle down the problem?
Tried to get help over google. Problem is known, but too difficult for me. See for example here: [https://github.com/AppImage/AppImageKit/issues/1162](url)
I really do not know how to start.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. start  the qmapshack-appimage in terminal under Ubuntu 22.10

### Expected behavior
Would be great if you can compile an actual appimage or lead me to a fix for my installation.

### Screenshots
/

### Attachments
/

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: Xubuntu 22.10
 - QMapShack Version:  1.16.1
 - Window Manager:  Xfce

### Additional context
Thanks for that great piece of Software!

**Comment by kiozen** [comment]
@kkarsten62 can you have a look please?

**Comment by kkarsten62** [comment]
According to https://github.com/kkarsten62/QMapShack.AppImage
there is no support for Kubuntu/Xfce.

Please check some other QMapShack.AppImage from wiki page
https://github.com/kkarsten62/QMapShack.AppImage/wiki
Please let me know when some will fit your needs.

Or you can try to build your own AppImage for Kubuntu/Xfce.

**Comment by Raschnow** [comment]
Hi kkarsten62,

the ubuntu 22.04 file is running directly. Thanks for the help. I build it once in the past, but AppImage is for a beginner like me much easier to use. I always need several hours to understand the build-process and to solve the problems.

Once again, thank you very much!
