### ISSUE TITLE
Bug/Error: QMAPShack quit unexpectedly

### ISSUE THREAD

**Issue by Phoenix21-root** [Maproom/qmapshack#581]
QMapShack cannot be opened in MacOS Ventura, shows 'quitting unexpectedly' error message.
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               QMapShack [39681]
Path:                  /Volumes/VOLUME/*/QMapShack.app/Contents/MacOS/QMapShack
Identifier:            org.qlandkarte.QMapShack
Version:               1.16.1 (1.16.1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-01-24 18:00:54.3874 +0900
OS Version:            macOS 13.1 (22C65)
Report Version:        12
Anonymous UUID:        349D34A3-D374-058F-B388-292CF3D72BA5

Time Awake Since Boot: 28000 seconds

System Integrity Protection: enabled

Notes:
dyld_process_snapshot_create_for_process failed with 5

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/Cellar/qt@5/5.15.5_1/lib/QtGui.framework/Versions/5/QtGui
Referenced from: <123891DD-B748-3DED-BCE3-FE20D433C031> /private/var/folders/qc/9_sg6xdx7b58k51fhn2dq3ph0000gn/T/AppTranslocation/4E59C44B-E64A-4EA9-BEAC-F40C9BC686E9/d/QMapShack.app/Contents/Frameworks/QtQuick.framework/Versions/5/QtQuick
Reason: tried: '/opt/homebrew/Cellar/qt@5/5.15.5_1/lib/QtGui.framework/Versions/5/QtGui' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/qt@5/5.15.5_1/lib/QtGui.framework/Versions/5/QtGui' (no such file), '/opt/homebrew/Cellar/qt@5/5.15.5_1/lib/QtGui.framework/Versions/5/QtGui' (no such file), '/Library/Frameworks/QtGui.framework/Versions/5/QtGui' (no such file), '/System/Library/Frameworks/QtGui.framework/Versions/5/QtGui' (no such file, not in dyld cache)Library not loaded: /opt/homebrew/*/QtNetwork.framework/Versions/5/QtNetwork
Referenced from: <C6D9B06C-2321-3B04-9C17-BC015B78DF25> /private/var/folders/qc/9_sg6xdx7b58k51fhn
(terminated at launch; ignore backtrace)

Error Formulating Crash Report:
dyld_process_snapshot_create_for_process failed with 5

Thread 0 Crashed:
0   dyld                          	       0x19994f190 __abort_with_payload + 8
1   dyld                          	       0x199959a00 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x199959a34 abort_with_payload + 16
3   dyld                          	       0x1998e80a4 dyld4::halt(char const*) + 328
4   dyld                          	       0x1998e5098 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4204
5   dyld                          	       0x1998e3dc4 start + 2404

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016d3893c0   x3: 0x0000000000000118
    x4: 0x000000016d388fc0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000033  x14: 0x0000000000000007  x15: 0xffffffffffffffff
   x16: 0x0000000000000209  x17: 0x00000001998e1344  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016d388fc0  x21: 0x0000000000000118  x22: 0x000000016d3893c0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000001f547b340  x26: 0x000000016d38b260  x27: 0x000000016d38b0c8
   x28: 0x0000000000000000   fp: 0x000000016d388f90   lr: 0x0000000199959a00
    sp: 0x000000016d388f50   pc: 0x000000019994f190 cpsr: 0x00001000
   far: 0x000000010386c010  esr: 0x56000080  Address size fault

Binary Images:
       0x1998de000 -        0x199968b63 dyld (*) <487cfdeb-9b07-39bf-bfb9-970b61aea2d1> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.5G resident=0K(0%) swapped_out_or_unallocated=1.5G(100%)
Writable regions: Total=12.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.2M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__AUTH                            1864K      343 
__AUTH_CONST                      24.2M      562 
__CTF                               756        1 
__DATA                            17.4M      606 
__DATA_CONST                      35.6M      618 
__DATA_DIRTY                      1963K      222 
__FONT_DATA                        2352        1 
__LINKEDIT                       781.5M       54 
__OBJC_CONST                      4639K      309 
__OBJC_RO                         65.4M        1 
__OBJC_RW                         1986K        1 
__TEXT                           744.6M      638 
dyld private memory                512K        2 
===========                     =======  ======= 
TOTAL                              1.7G     3361 

-----------
Full Report
-----------

{"app_name":"QMapShack","timestamp":"2023-01-24 18:00:56.00 +0900","app_version":"1.16.1","slice_uuid":"e8e6cd32-c27c-30c7-9286-d875b884f8fa","build_version":"1.16.1","platform":1,"bundleID":"org.qlandkarte.QMapShack","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.1 (22C65)","roots_installed":0,"name":"QMapShack","incident_id":"D941AEF3-205C-4169-AA02-7E3E0C552F89"}
{
  "uptime" : 28000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,4",
  "coalitionID" : 2748,
  "osVersion" : {
    "train" : "macOS 13.1",
    "build" : "22C65",
    "releaseType" : "User"
  },
  "captureTime" : "2023-01-24 18:00:54.3874 +0900",
  "incident" : "D941AEF3-205C-4169-AA02-7E3E0C552F89",
  "pid" : 39681,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-01-24 18:00:49.5101 +0900",
  "procStartAbsTime" : 694281465987,
  "procExitAbsTime" : 694398493032,
  "procName" : "QMapShack",
  "procPath" : "\/Volumes\/VOLUME\/*\/QMapShack.app\/Contents\/MacOS\/QMapShack",
  "bundleInfo" : {"CFBundleShortVersionString":"1.16.1","CFBundleVersion":"1.16.1","CFBundleIdentifier":"org.qlandkarte.QMapShack"},
  "storeInfo" : {"deviceIdentifierForVendor":"D7232BA1-368B-5C96-8119-8133EB4B5955","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.qlandkarte.QMapShack",
  "crashReporterKey" : "349D34A3-D374-058F-B388-292CF3D72BA5",
  "throttleTimeout" : 2147483647,
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/opt\/homebrew\/Cellar\/qt@5\/5.15.5_1\/lib\/QtGui.framework\/Versions\/5\/QtGui","Referenced from: <123891DD-B748-3DED-BCE3-FE20D433C031> \/private\/var\/folders\/qc\/9_sg6xdx7b58k51fhn2dq3ph0000gn\/T\/AppTranslocation\/4E59C44B-E64A-4EA9-BEAC-F40C9BC686E9\/d\/QMapShack.app\/Contents\/Frameworks\/QtQuick.framework\/Versions\/5\/QtQuick","Reason: tried: '\/opt\/homebrew\/Cellar\/qt@5\/5.15.5_1\/lib\/QtGui.framework\/Versions\/5\/QtGui' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/opt\/homebrew\/Cellar\/qt@5\/5.15.5_1\/lib\/QtGui.framework\/Versions\/5\/QtGui' (no such file), '\/opt\/homebrew\/Cellar\/qt@5\/5.15.5_1\/lib\/QtGui.framework\/Versions\/5\/QtGui' (no such file), '\/Library\/Frameworks\/QtGui.framework\/Versions\/5\/QtGui' (no such file), '\/System\/Library\/Frameworks\/QtGui.framework\/Versions\/5\/QtGui' (no such file, not in dyld cache)Library not loaded: \/opt\/homebrew\/*\/QtNetwork.framework\/Versions\/5\/QtNetwork","Referenced from: <C6D9B06C-2321-3B04-9C17-BC015B78DF25> \/private\/var\/folders\/qc\/9_sg6xdx7b58k51fhn"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":444554,"threadState":{"x":[{"value":6},{"value":1},{"value":6127391680},{"value":280},{"value":6127390656},{"value":0},{"value":0},{"value":0},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":51},{"value":7},{"value":18446744073709551615},{"value":521},{"value":6871192388,"symbolLocation":392,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6127390656},{"value":280},{"value":6127391680},{"value":1},{"value":6},{"value":8410084160,"symbolLocation":0,"symbol":"gProcessInfo"},{"value":6127399520},{"value":6127399112},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6871685632},"cpsr":{"value":4096},"fp":{"value":6127390608},"sp":{"value":6127390544},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6871642512,"matchesCrashFrame":1},"far":{"value":4354129936}},"frames":[{"imageOffset":463248,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":506368,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":506420,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":41124,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":0},{"imageOffset":28824,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4204,"imageIndex":0},{"imageOffset":24004,"symbol":"start","symbolLocation":2404,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6871179264,
    "size" : 568164,
    "uuid" : "487cfdeb-9b07-39bf-bfb9-970b61aea2d1",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.5G resident=0K(0%) swapped_out_or_unallocated=1.5G(100%)\nWritable regions: Total=12.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__AUTH                            1864K      343 \n__AUTH_CONST                      24.2M      562 \n__CTF                               756        1 \n__DATA                            17.4M      606 \n__DATA_CONST                      35.6M      618 \n__DATA_DIRTY                      1963K      222 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       781.5M       54 \n__OBJC_CONST                      4639K      309 \n__OBJC_RO                         65.4M        1 \n__OBJC_RW                         1986K        1 \n__TEXT                           744.6M      638 \ndyld private memory                512K        2 \n===========                     =======  ======= \nTOTAL                              1.7G     3361 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "61fd92db295c182621ececc3",
      "factorPackIds" : {

      },
      "deploymentId" : 240000247
    },
    {
      "rolloutId" : "610d52e1fc54bc3389840408",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "6376d83499e1ff5d8f0dcc3f",
        "SIRI_UNDERSTANDING_MORPHUN" : "62ec7220c682040ba94e6a20"
      },
      "deploymentId" : 240000591
    }
  ],
  "experiments" : [

  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_create_for_process failed with 5"
]
}

Model: MacBookPro18,4, BootROM 8419.60.44, proc 10:8:2 processors, 64 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Display: LG ULTRAWIDE, 3440 x 1440 (UWQHD - Ultra-Wide Quad HD), MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Sep  3 2022 02:35:52 version 20.10.965.9.8.7.129 FWID 01-b0e84a9b
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: Anker USB-C Docking Device
USB Device: USB3.0 Hub
USB Device: USB3.0 Hub
USB Device: USB Storage
USB Device: USB 10/100/1000 LAN
USB Device: Anker USB-C Docking Device
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: MX Vertical Advanced Ergonomic Mouse
USB Device: USB Audio
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

And you might want to check https://github.com/d029940/qmapshack for more recent releases.
