### ISSUE TITLE
Version information in window title does not contain VERSION_SUFFIX "development"

### ISSUE THREAD

**Issue by huirad** [Maproom/qmapshack#59]
**Describe the bug**
When I build a development version, then this is indicated in the about dialogue but not in the window title. 

**To Reproduce**
1. Build the current development version of QMapshack and start it
2. Look at the window title: it shows "QMapShack, Version 1.14.0"
3. Open the ABout dialogue. There ther version information is "QMapShack, Version 1.14.0.development"

**Expected behavior**
First of all, the version information in the window title and in the about dialogue should be consistent. Second, the VERSION_SUFFIX should also be part of the version string in the window title.

**Screenshots**
See screenshot:
![grafik](https://user-images.githubusercontent.com/4027039/68022015-4e988d00-fca3-11e9-8570-6bc17a62f319.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - QMapShack Version: 1.14.0.development

**Comment by kiozen** [comment]
they said: "It's not a bug it's a feature" :wink:
