### ISSUE TITLE
I need Qt5Widgets

### ISSUE THREAD

**Issue by guy-maurel** [Maproom/qmapshack#593]
I am a beginner.
I do
`cmake -G Ninja ..`
and get
```
CMake Error at CMakeLists.txt:176 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
```
Do I need to get the sources ?
or where to get the library?

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
