### ISSUE TITLE
How to use WMTS service for relief map in france with high resolution

### ISSUE THREAD

**Issue by erch** [Maproom/qmapshack#595]
IGN France publish relief maps through a WMTS service : https://geoservices.ign.fr/services-web-experts-altimetrie
I would like to use it because they claim to provide a 5m resolution which seems awesome. Unfortunately I have no clue on what to do to use this service in QMapShack. Is someone can have a look and tell me how to proceed ?

Thanks

**Comment by wthaem** [comment]
Layers supporting "normal" image formats (jpg/png) should work as maps (estompage, courbes de niveau, carte des pentes, altitude, seuils de pente pour l'agriculture ...).

**Comment by erch** [comment]
There is already a WMTS service for the maps which I already use (https://geoservices.ign.fr/services-web-issus-des-scans-ign)
On top of the maps I'd like to use their Elevation Data in Qmapshack, either with this WMTS service or by using the elevation files that are also provided for download  : https://geoservices.ign.fr/courbes-de-niveau . They are zip files in shapefiles  format with .dbf, .prj, .shp and .shx, 

Does anyone has already tried the WMTS service to get elevation data ?
Is it possible to convert the shapfiles to a format supported by Qmapshack ?

Thanks for your help.

**Comment by wthaem** [comment]
DEM (Elevation data) files suitable for QMS have elevation data with a grid structure. As far as I have seen in the WMTS capabilities report it won't be easy to convert e.g. elevation data in form of isohypses into this format. In general, GDAL is the tool to try to convert data. Try to get, for example, a GeoTiff format.

**Comment by erch** [comment]
Ok, thanks for your reply and sorry for having posted the request to the wrong channel.

No problem to switch to the mailing list if you want.

 

I’ll try to run the test with the CLI as soon as possible.

 

Eric.

**Comment by wthaem** [comment]
This doesn't work. If you activate the proposed VRT file you get an error message of the form "DEM must have one band with 16bit or 32 bit data".

**Comment by mitxel-m** [comment]
Ok.
A tricky way would be edit that vrt to left only one band. 

Another way woul be edit the wmts file , and left only the call to the layer we want, but then you have to rename ( fake) that file as vrt to appear in the QMS DEM panel.

And I am not sure that they would work, as I can not inspect which kind of data brings the Wmts layer.

( I will try it next week, now time to ride. ;-)  )

**Comment by wthaem** [comment]
The packages on the page [https://geoservices.ign.fr/bdalti](https://geoservices.ign.fr/bdalti) for elevation data of departements consists of asc files, i.e. they have a format that can be handled by QMS via VRT. If the projection can be used directly or if the asc files have to be reprojected with GDAL, I don't know.

**Comment by mitxel-m** [comment]
ASC files lack any  reference to projection /datum, but you can assign it in the VRT.
These ones seems to be EPSG:5698
https://epsg.io/5698

IN QMS vrt builder check advanced options and  filll -a_srs option with its EPSG code.

**Comment by kiozen** [comment]
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

I close the issue as it does not full fill the requirements for issues. But of course you can keep discussing the topic in the closed ticket.
