### ISSUE TITLE
WorldSat.wmts not working?

### ISSUE THREAD

**Issue by royrwood** [Maproom/qmapshack#603]
### Describe the bug
[comment]: I'm trying to use the WorldSat.wmts and WorldTopo.wmts files as my source of online map data, but nothing is displayed in the main view when I have those sources installed and activated.

### What have you done to circle down the problem?
[comment]: I have run qmapshack with the "--debug" flag, but I don't see any errors reported in the output.  I have tried zooming in and out, and I briefly see a temporary window indicating the qmapshack is trying to download tiles, but nothing is displayed or logged.  I have tried other map sources such as OpenMaps and Google, and they work perfectly.

### To Reproduce
[comment]: I installed qmapshack 1.6.1 on Ubuntu, added the WorldSat.wmts file to my "Maps" folder, refreshed the maps, activated the WorldSat map, tried moving/zooming the view, but no tile data was displayed.

### Expected behavior
[comment]: I expected to see map image/tile data

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: I am running Ubuntu 22.10 + Wayland, qmapshack 1.6.1

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by frankystone** [comment]
AFAIK version 1.6.1 contains wmts files which do work because the url has changed. See: #522

Just replace the contents of the file with this: https://github.com/Maproom/qmapshack/blob/dev/src/qmapshack/map/WorldSat.wmts

Or use the the file(s) mentioned here: https://github.com/Maproom/qmapshack/issues/522#issuecomment-1134207805

**Comment by royrwood** [comment]
Thanks!  That works perfectly.
