### ISSUE TITLE
How to add a file to the wiki?

### ISSUE THREAD

**Issue by royrwood** [Maproom/qmapshack#605]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

I would like to add a .tms file to the wiki.  I cam edit the wiki via browser, but I need to git-clone the wiki and push changes to add a file.  Is there a way to submit a pull request for the wiki?

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

I edited the wiki to point to the .tms file I'd like to add, and I've cloned the wiki locally to add the .tms file, but I don't have access permission to push a change to the wiki.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Clone wiki
2. Add file
3. Commit file
4. Try to "git push"
5. Error occurs since I don't have commit privs

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

Could someone else add the file to the "Downloads" folder of the wiki, please?

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

This file should be renamed to "canada_geogratis.tms" and placed in the "Downloads" folder of the wiki.

[canada_geogratis.tms.txt](https://github.com/Maproom/qmapshack/files/11870190/canada_geogratis.tms.txt)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: [e.g. OS X, Debian, Suse, Windows]
 - QMapShack Version:   [e.g. 1.13.1]
 - Window Manager:  [e.g. KDE, GNOME]

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by wthaem** [comment]
@royrwood: Done. The offline help will be updated by kiozen when preparing a new release!

**Comment by royrwood** [comment]
Thanks!
