### ISSUE TITLE
Enhance handling of PROJ.4 files in Windows

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#62]
**Is your feature request related to a problem? Please describe.**

Currently, the Windows QMS version can be compiled with different Proj.4 versions. But the 2 files

* `msvc_64\copyfiles.bat` and
* `msvc_64\QMapShack_Installer.nsi` 

require a fixed Proj.4 version. Any change of the Proj.4 version requires a change of these files.

**Describe the solution you'd like**

Replace lines with a fixed version (similar to proj_6_x.dll) in both files with a wildcard version (proj_6_*.dll). This will make both scripts independent of a fixed Proj.4 version and doesn't need any change in the documentation. (Idea taken from huirad).

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by kiozen** [comment]
Btw, as this is another ticket that totally ignores the template, please do so in the future. I will have to close these tickets as they are a bad example and encourage others to do the same. This will end up in the same chaotic ticket style as we had on BitBucket. That's why I will enforce it.

**Comment by wthaem** [comment]
Sorry for this. Edited content to match template form.
