### ISSUE TITLE
Cannot rename folder in database

### ISSUE THREAD

**Issue by robryk** [Maproom/qmapshack#635]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

Folders in a database cannot be renamed. Inspection of the source code tells me that this is explicitly only supported for "group" type folders (and not "project" nor "other"), but doesn't tell me why.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

I've tried searching for issues about renaming folders and looking for the commit that introduced this restriction renaming. I've found none and that restrictions seems to be there since years, so I gave up assuming that it's unlikely that I can find code review thread for it.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Create a "project" folder in the database via "Add fplder".
2. Fail to find a way to rename it.

Or:

1. Import a GPX file into database via "import from Files".
2. Fail to find a way to rename "project" type folder that this results in.

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

I expect to be able to rename ~any entity in the database (or in a project, for that matter).

### Desktop
[comment]: # (please complete the following information)

 - OS: NixOS
 - QMapShack Version: 1.17.0
 - Window Manager: i3

**Comment by kiozen** [comment]
* Load the project into the workspace and edit the project (right click on the project folder in the workspace) 
* Make sure the project is not read only (the lock in the top right corner has to be open). 
* Click on the project name

All GIS items (waypoint, track, route, area and project) have to be edited on the workspace. To allow an edit in two locations like the workspace  and the database view leads to all kind of synchronization issues. Therefore the rule: These items have to be edited in the workspace exclusively.
