### ISSUE TITLE
Qmapshasck v1.17.0 on Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by macro182** [Maproom/qmapshack#640]
### Is your feature request related to a problem? Please describe.
[comment]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] )

### Describe the solution you'd like
[comment]: # (A clear and concise description of what you want to happen.)

### Describe alternatives you've considered
[comment]: # (A clear and concise description of any alternative solutions or features you've considered.)

### Give a reason why someone else should spend time on that request
[comment]: # (Keep in mind that you ask others to spend their spare time for your request. Good reasons are if you are able to prove that the request solves a fundamental problem for everyone, or the request is of general interest for many users. Bad reasons are you just want it to have that way, or argue that software xyz does it.)

### Additional context
[comment]: # (Add any other context or screenshots about the feature request here.)

**Comment by macro182** [comment]
Hi there,
how can I possibly run v1.17.0 AppImage for Ubuntu 22.04 on an Ubuntu 20.4.6 LTS.

I expected it to work, but it does not.

Thank you!

**Comment by macro182** [comment]
I had already downloaded the 22.04 Appimage. However, it does not work on my Ubuntu 20 even though I have given the correct permission to that file.

Thanks

10 Oct 2023, 09:31 by ***@***.***:

**Comment by kkarsten62** [comment]
In  https://github.com/kkarsten62/QMapShack.AppImage/wiki it is said that AppImages for Ubuntu 18.04 and Ubuntu 20.04 is out of service for the current version of QMS, due to incompatible of the Qt version.

See https://github.com/kkarsten62/QMapShack.AppImage/wiki#qmapshackappimages-out-of-service

**Comment by macro182** [comment]
thanks, now it's clear why it didn't work.

ciao

10 ott 2023, 17:48 da ***@***.***:
