### ISSUE TITLE
Binary Packages for V 1.17.1

### ISSUE THREAD

**Issue by kiozen** [Maproom/qmapshack#653]
@wthaem @kkarsten62 and @d029940  there is a new release, You might want to update your binary packages. 

I will leave that ticket as a reminder for a few weeks and close it.

**Comment by d029940** [comment]
I am preparing it for the Mac. I will create an issue, since a lot of the build scripts needed some changes:
- gdal built from source, since too many dependencies with homebrew package manager
- qt5 & qt6 installed in parallel on the dev machine.

**Comment by kkarsten62** [comment]
I am quite busy this week. I will start mid of next week to build fresh QMapShack.AppImages.

**Comment by d029940** [comment]
I will take this issue number if it is ok?

**Comment by kiozen** [comment]
> I am quite busy this week. I will start mid of next week to build fresh QMapShack.AppImages.

no rush :wink:

**Comment by barbudor** [comment]
Hello
Is there anyone in charge of building Windows binaries ?
If not I can have a look this week-end but I would need some directions
I see a msvc_64 folder but no vsproj files
What dev tools would be required ? VStudio Community Edition ? MinGW ? 
Thanks for hints

**Comment by wthaem** [comment]
For Windows see [https://github.com/wthaem/qmapshack/releases](https://github.com/wthaem/qmapshack/releases)

**Comment by kiozen** [comment]
Thx! Added the link to the release page.

**Comment by d029940** [comment]
Not sure, who is adding the information to the download page.

For MacOS:

[https://github.com/d029940/qmapshack/releases/tag/v1.17.1](https://github.com/d029940/qmapshack/releases/tag/v1.17.1)

Please advise.

**Comment by kiozen** [comment]
Thx. It's me as I have the edit credentials.

**Comment by kkarsten62** [comment]
Here are the QMapShack.AppImages for V_1.17.1

[https://github.com/Maproom/qmapshack/releases/tag/V_1.17.0](https://github.com/Maproom/qmapshack/releases/tag/V_1.17.0)

**Comment by kiozen** [comment]
Thank you all for your tremendous effort creating all these packages. I am well aware that this is quite time consuming and needs a lot of dedication. And I am pretty sure many users really appreciate it even they never do tell us :wink: 

Frohes Fest!
