### ISSUE TITLE
Crash at program start

### ISSUE THREAD

**Issue by drj-e** [Maproom/qmapshack#662]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
on macos 13.4 and arm M1:

QMS is looking for : /usr/lib/libc++.1.dylib
that is part of the crash report:

Process:               QMapShack [86746]
Path:                  /Users/USER/Desktop/QMapShack Kopie.app/Contents/MacOS/QMapShack
Identifier:            org.qlandkarte.QMapShack
Version:               1.17.1 (1.17.1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-01-10 18:06:40.6973 +0100
OS Version:            macOS 13.4 (22F66)
Report Version:        12
Anonymous UUID:        AFACE4F7-30C4-F0AA-8353-DCCDB321B934

Sleep/Wake UUID:       35E384D9-46F9-419D-881B-614954C2E489

Time Awake Since Boot: 640000 seconds
Time Since Wake:       32059 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 4 Symbol missing
Symbol not found: __ZTVNSt3__13pmr25monotonic_buffer_resourceE
Referenced from: <2421DF8C-7779-32B7-AA75-E276668C9B50> /Users/USER/Desktop/QMapShack Kopie.app/Contents/Frameworks/QtXml.framework/Versions/5/QtXml
Expected in:     <54E8FBE1-DF0D-33A2-B8FA-356565C12929> /usr/lib/libc++.1.dylib
(terminated at launch; ignore backtrace)

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
the last version 1.17.0 does complete to launch without problems

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

QMS should not crash

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: [e.g. OS X, Debian, Suse, Windows]
 - QMapShack Version:   [e.g. 1.13.1]
 - Window Manager:  [e.g. KDE, GNOME]

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by kiozen** [comment]
Ignoring the template -> ignoring the ticket.
