### ISSUE TITLE
Feature Request: Route Optimization

### ISSUE THREAD

**Issue by WST1811** [Maproom/qmapshack#67]
I got a lot of Waypoints (20 to 25 or more) and want a Route/Track with the fastest Way between Start and End with touch all Waypoints. Now I have to sort the waypoints in the order in which they should optimally be approached. Here an option would be nice to have an automatic calculation from waypoint 1 over the other points to the last waypoint without having to specify the best order.

**Comment by kiozen** [comment]
This project provides templates to file a feature request or a bug report. As these are constantly ignored the new policy is to close all new issues that do not use these templates.
