### ISSUE TITLE
The label colors defined in the TYP are not used

### ISSUE THREAD

**Issue by cricri-du-lauragais** [Maproom/qmapshack#675]
### Is your feature request related to a problem? Please describe.
it's complicated to know whether a text refers to a type of information with Garmin map, for example about natural objects such as a forest near a village.

### Describe the solution you'd like
garmin TYP allows the choice of color for each text displayed on the map, using the same functionality in QMS.

### Describe alternatives you've considered
no alternative, just use TYP

### Give a reason why someone else should spend time on that request
a map that's easier to interpret when you're planning a route, without having to switch to other sources of information to find your bearings or understand the topography of the terrain.

### Additional context
basecamp screenshot 
![basecamp](https://github.com/Maproom/qmapshack/assets/83398215/23e18c4c-a3db-46a6-8b7f-3720f34d08ab)

**Comment by kiozen** [comment]
What is the problem with the current typ file loading?

![image](https://github.com/Maproom/qmapshack/assets/54329441/bbed13bc-5495-4e08-adeb-f739df967885)

**Comment by cricri-du-lauragais** [comment]
the label colors defined in the TYP are not used, all labels are displayed in black.

![label1](https://github.com/Maproom/qmapshack/assets/83398215/fe1c4187-e18d-47f9-acc7-bb7297e32ae3)
![label2](https://github.com/Maproom/qmapshack/assets/83398215/3470ca8c-33c3-42f5-9e3b-de92ccd4c286)

**Comment by kiozen** [comment]
> the label colors defined in the TYP are not used, all labels are displayed in black.

Ok, so this is the real problem. Changes the title to avoid further confusion.
