### ISSUE TITLE
Send-to-devices only copies a single item when multiple items selected in workspace

### ISSUE THREAD

**Issue by cytrinox** [Maproom/qmapshack#680]
### Describe the bug
When selecting multiple item in workspace and choosing "Send to devices" from context menu, only one item is copied to device. Same for drag&drop. All items are highlighted blue during drag&drop, but only one single item is actually copied.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Load multiple GPX or database items into workspace
2. Select a range of items (or all)
3. Choose **Send to devices** from context menu
4. Only one item is copied

### Expected behavior
All selected items should be send/copied to selected device

### Desktop
[comment]: # (please complete the following information)

 - OS: Debian
 - QMapShack Version:   1.17.1 (also exists in 1.16.x
 - Window Manager:  Gnome

**Comment by kiozen** [comment]
Please test: https://github.com/Maproom/qmapshack/pull/681
