### ISSUE TITLE
ERROR 1: Create mapfile (/sdat/config/mapfile//10008/10008_1_wcs.map) failed.

### ISSUE THREAD

**Issue by tps800** [Maproom/qmapshack#682]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
Qmapshack tries to create a file within "/sdat/config/mapfile" but fails.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
The problem first occured with qmapshack 1.7.1 – the latest available version

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Start qmapshack.
2. Configure some maps.
3. Load a *.gpx-file.
4. See error "ERROR 1: Create mapfile (/sdat/config/mapfile//10008/10008_1_wcs.map) failed."

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)
qmapshack just creating the file within an appropriate path, not trying to use "/sdat/config/mapfile/..."

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

Does not crash.

### Desktop
[comment]: # (please complete the following information)

 - OS: Debian (testing), Ubuntu 24.04
 - QMapShack Version:   1.17.1
 - Window Manager:  xfce 4

### Additional context
[comment]: # (Add any other context about the problem here)

tried to create "/sdat/config/mapfile/..." but without any success.

**Comment by kiozen** [comment]
This is GDAL related. You get the same error when:

` gdal_translate   -projwin 49 12.1 49.1 12 -outsize 60 0 World_Online_SRTM900.wcs test.tif` 

There might be a way to fix it in the wcs file. Or it's a bad configuration of the WCS server. Or...? I couldn't find a clue on Google. 

If you manage to get the above command to work, QMapshack will work, too.
