### ISSUE TITLE
Trying to replace elevation by interpolated elevation data derived from GPS data errors are reported from alglib

### ISSUE THREAD

**Issue by tps800** [Maproom/qmapshack#683]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

Trying to replace elevation by interpolated elevation data derived from GPS data errors are reported from alglib:
```
[QMS] 2024-08-17 20:06:12.565 [warning] Error from alglib:  Spline1DFitCubic: M<4!
[QMS] 2024-08-17 20:06:15.845 [warning] Error from alglib:  Spline1DFitCubic: M<4!
[QMS] 2024-08-17 20:06:44.133 [warning] Error from alglib:  Spline1DFitCubic: M<4!
```

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

This seems to be related to newer versions on alglib. With older versions it works (but these are not available any more with newer versions of tested systems (Debian testing, Ubuntu 24.04).

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Create a workspace, import some gps data
2. click on a track, then "edit"
3. open Interpolate elevation data
4. select preview, see error.

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

no error, show preview of interpolated elevation data as yellow line.

### Desktop
[comment]: # (please complete the following information)

 - OS: Debian testing, Ubuntu 24.04
 - QMapShack Version:   1.17.1
 - Window Manager:  xfce 4

**Comment by kiozen** [comment]
Please test PR: https://github.com/Maproom/qmapshack/pull/684
