### ISSUE TITLE
No speed diagram is shown

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#69]
**Describe the bug**
I want to see the speed diagram, but I can't do so since I updated to QMS 1.14.0

**To Reproduce**
1. Open Details of a track that has speed information
2. See that there is no diagram

**Expected behavior**
Until now, in the fields that now show that there is no data to be shown, the diagram of the speed over the time was displayed, and that's how it should be

**Screenshots**
![grafik](https://user-images.githubusercontent.com/36167579/68124471-ccf96700-ff0f-11e9-8964-6eebad3d4b8f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - QMapShack Version 1.14.0

**Additional context**

**Comment by kiozen** [comment]
* Switch to tab `Diagramme`
* Select the appropriate diagram you want to see.

**Comment by pingurus** [comment]
Thank you!
