### ISSUE TITLE
New cache servers for Norway topo maps

### ISSUE THREAD

**Issue by oddmundno** [Maproom/qmapshack#690]
The old Norwegian topp map cache services do not work anymore. New service available on https://cache.kartverket.no/v1/wmts/1.0.0/WMTSCapabilities.xml

I tried to make wmts file from the xml file, but cant get any map tiles. Please help anyone that knows how to make wmts files.
More info about new service here:
https://www.geonorge.no/aktuelt/Se-siste-nyheter/store-endringer-i-kartverkets-cachetjenester/

Best regards,
Oddmund Nordgård

**Comment by wthaem** [comment]
Try the attached TMS file!

[Norge_new.zip](https://github.com/user-attachments/files/17421292/Norge_new.zip)

**Comment by oddmundno** [comment]
Voila. It works! Thanks so much!
