### ISSUE TITLE
QMS doesn't start from non-ASCII directory

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#70]
**Describe the bug**
QMS doesn't start if it is located in a directory with non-ASCII characters 

*(have seen same issue somewhere in the Internet, don't remember where)*

*Found it again:* https://www.naviboard.de/thread/63434-m%C3%B6glichkeit-ohne-routino-zu-starten-windows/

**To Reproduce**
1. Goto standard `Files` directory obtained from installation of Windows version and start QMS: no problems.
2. Rename `Files` directory so that the new name has non-ASCII characters (in my case `Загрузка`, most likely German Umlaut will do, too).
3. Go againn into renamed directory (no file changes!) and start QMS.
4. First issue: Routino doesn't find XML files (might be Routino issue!) - see snapshot
5. Second issue: QMS complaints about Proj.4 - see snapshot

**Expected behavior**
Once only the name of the directory was changed and no file within the directory, QMS should start smoothly

**Screenshots**
* Screenshot 1: Routino XML problem
* Screenshot 2: Proj.4 problem
![Warning_Routino](https://user-images.githubusercontent.com/55309218/68190857-873fab80-ffae-11e9-95da-28219d186d63.jpg)
![Fatal_Proj4](https://user-images.githubusercontent.com/55309218/68190868-8c045f80-ffae-11e9-9bf7-4dddb4043d68.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QMapShack latest development version

**Additional context**
None

**Comment by kiozen** [comment]
@huirad can you please have a look? This is one of the infamous UTF-8 glitches in Windows. Just pick one of the issues and find out what we have to do with the path to make Windows work. Then we can apply that change everywhere else.

**Comment by wthaem** [comment]
Remember: All files loaded by QMS are in 1 folder - no environment variables used to start QMS!

**Comment by huirad** [comment]
I can reproduce the problem,
I fiddled a bit around with the creation of the file pathes to routino and proj in CAppSetupWin.cpp without being able to reach an improvement 
I also ran `qmapshack -f` to create the QMapShack.log abd there I found 
```
2019-11-09 9:12:55.224 [debug] "GDAL_DATA directory set to M:\\Src\\qmapshack_git_huirad\\msvc_64\\Filesäöü\\data"
2019-11-09 9:12:55.224 [debug] "PROJ_LIB directory set to M:\\Src\\qmapshack_git_huirad\\msvc_64\\Filesäöü\\share\\proj"
2019-11-09 9:12:55.224 [debug] "using file 'M:\\Src\\qmapshack_git_huirad\\msvc_64\\Filesäöü\\translations/qtbase_de.qm' for translations."
2019-11-09 9:12:55.224 [debug] "using file 'M:\\Src\\qmapshack_git_huirad\\msvc_64\\Filesäöü\\translations/qmapshack_de.qm' for translations."
2019-11-09 9:12:56.240 [debug] "ROUTINO" path "M:/Src/qmapshack_git_huirad/msvc_64/Filesäöü/routino-xml/profiles.xml"
```
So that still looks reasonable.

I do not see much value in this use case. Therefore I will not spend more time on it.

**Comment by wthaem** [comment]
Would it be possible to include a check for non-ASCII installation directory into the Windows nsi installer script or in QMS itself? If yes, then a warning "Use only ASCII-named folders for QMS installation" could be shown to the user which is much clearer than the messages seen now.

**Comment by kiozen** [comment]
Don't think that's a good solution. It needs a volunteer to dig deeper and to find a proper solution for that unicode mess on Windows. I labeled the issue accordingly.

**Comment by wthaem** [comment]
Just an additional piece of information:
Using the FileAccessErrorView tool I get the attached picture.
My(renamed) folder is `Filesä`. This can be seen in the third blue line. But the first 2 blue lines show a different and wrong form of this folder name (but well-known to everybody who had trouble with UTF-8 vs. Latin-1). Thus, when going in the EPSG direction a wrong folder name is used.

![NonAsciiFolder](https://user-images.githubusercontent.com/55309218/68531546-b68a4b80-0313-11ea-98be-2a06f04ae184.jpg)

The next image is just the first blue line sshown in a slightly different form. Here too, the 2 different spellings of my folder can be seen and the one at the top certainly doesn't work.


![NonAsciiFolder1](https://user-images.githubusercontent.com/55309218/68531598-4b8d4480-0314-11ea-98ef-de0d88db2948.jpg)

**Comment by wthaem** [comment]
And here is a list of more (QMS) attempts to open files with wrong folder name (found with Process monitor tool):
![WrongFolders](https://user-images.githubusercontent.com/55309218/68540933-7a013300-0399-11ea-842a-5cd0a83b6aab.jpg)

**Comment by wthaem** [comment]
Some additional QMS debug info:

Modified `CAppSetupWin.cpp`:

```
QString CAppSetupWin::routinoPath(QString xmlFile)
{
    QString apppath = QCoreApplication::applicationDirPath();
    apppath = apppath.replace("/", "\\");
    
    qDebug() << "apppath:" << apppath;

    
    QDir dirXml(QString("%1\\routino-xml").arg(apppath).toUtf8());
    
    qDebug() << "abspath:" << dirXml.absolutePath();

    return IAppSetup::path(dirXml.absolutePath(), xmlFile, false, "ROUTINO");
}
```

(2 additional debug statements: both show correct folder name `Filesä` in debug log)

Modified `CRouterRoutino.cpp`:

```
CRouterRoutino::CRouterRoutino(QWidget *parent)
...
    IAppSetup *setup = IAppSetup::getPlatformInstance();
    
    qDebug() << "profilesxml:" << setup->routinoPath("profiles.xml").toUtf8();
    res = Routino_ParseXMLProfiles(setup->routinoPath("profiles.xml").toUtf8());
```
1 additional debug statement: **debug log shows wrong folder name**:
 
 ```
2019-11-10 9:35:29.702 [debug] profilesxml: "D:/QtProjects/QMS/QMapShack/msvc_64/Files\xC3\xA4/routino-xml/profiles.xml"
```  
**Thus, here something went wrong!**

**Comment by wthaem** [comment]
My next debugging step:

Replace in `CRouterRoutino.cpp` line

~~~
res = Routino_ParseXMLProfiles(setup->routinoPath("profiles.xml").toUtf8());
~~~

with line

~~~
res = Routino_ParseXMLProfiles(setup->routinoPath("profiles.xml").toLatin1());
~~~

The debug log (with `toLatin1`) has now the following line:

~~~
profilesxml: "D:/QtProjects/QMS/QMapShack/msvc_64/Files\xE4/routino-xml/profiles.xml"
~~~

**Result when running QMS:**
The Routino error message shown on top of this issue disappears, QMS stops only at the Proj4 error message.

**My conclusions:** 

* File handling within Routino fails, if paths & filenames are given as UTF-8 encoded byte arrays. 
* File handling within Routino is ok, if paths & filenames are given in Latin-1 encoded form.
* *Unclear issue:* How to proceed, if my filename can't be encoded in Latin-1? 
* *There is an implicit Routino assumption about possible filenames. Seemingly, conflicts can only be avoided, if the QMS Windows version never uses non-ASCII folder names.*

The Routino API documentation states simply:

~~~
Global Function Routino_ParseXMLProfiles()

Parse a Routino XML file containing profiles, must be called before selecting a profile.
int Routino_ParseXMLProfiles ( const char* filename )
~~~

and doesn't give a hint about the expected filename encoding.

**Comment by wthaem** [comment]
Added hint to some Wiki pages about ASCII installation folder names for Windows version.
