### ISSUE TITLE
Info of a geocache is not correctly shown in Copy Element Window

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#73]
**Describe the bug**
The Info of a geocache is incomplete regardless of the available space in the "Copy Element" Window

**To Reproduce**
1. Save a geocache to database
2. Open a different version of the Geocache and copy it to a different project in the database
3. See "Copy Element" Window

**Expected behavior**
I expect as much of the description to be shown as is possible with the window size. Ideally I would want information which of the geocache versions is more up to date. Howeveer I don't think that it is a bug that it's not shown.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/36167579/68294696-0b6a5f80-0091-11ea-819f-39758dc733d1.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - QMapShack Version 1.14.0

**Additional context**

**Comment by kiozen** [comment]
Please define 

> information which of the geocache versions is more up to date.

What information should be shown to make you think the cache is more up-to-date?

**Comment by pingurus** [comment]
I totally forgot to answer, sorry.
Useful would either be the date of the latest log and/or the creation date of the QMS object.

**Comment by kiozen** [comment]
@pingurus please test and report
