### ISSUE TITLE
Some TOCs in the Wiki are still broken

### ISSUE THREAD

**Issue by kiozen** [Maproom/qmapshack#74]
**Describe the bug**
For some pages in the Wiki the automatic TOC generation seemed to have failed. Let's collect these pages:

**To Reproduce**
https://github.com/Maproom/qmapshack/wiki/DeveloperCodingGuideline
https://github.com/Maproom/qmapshack/wiki/DeveloperTranslate

**Expected behavior**
A valid TOC.

**Screenshots**
n/a

**Desktop (please complete the following information):**
GitHub Wiki pages

**Additional context**
n/a

**Comment by wthaem** [comment]
Reason is clear: **"#"** appears in code parts but handled as section header line. Will try to find a solution.

**Comment by wthaem** [comment]
Fixed. TOC's have been updated.

**Comment by kiozen** [comment]
Now that you mentioned it I realized that the language markers are done badly. Probably some artefact of Bitbucket's own interpretation of Markdown. Fixed them.

**Comment by wthaem** [comment]
@kiozen: Should the constructs

~~~
```
#!bash
~~~

used in `Troubleshooting.md/Ubuntu-14.04-HowTo.md`

or 

~~~

```
#!XML
~~~

used in `DocMapsTipsOnline.md` and, maybe, some similar ones

be changed in a similar way (as language markers)? 

(If yes, then I can make the changes easily)

**Comment by kiozen** [comment]
Yes please, change them. These strings where added by Bitbucket automatically, when using the Web UI. But they are not Markdown. Markdown says: After the ` ``` ` the language specifier follows.

**Comment by wthaem** [comment]
Done.
