### ISSUE TITLE
Edit track does not respect screen size

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#75]
**Describe the bug**
When opening edit of a track, the window grows out of the screen. I think we already had this issue once on windows, but this time it is on Ubuntu 19.10

**To Reproduce**
1. Create a track
2. open edit window
3. see that the right hand side of the window gets pushed out of the screen

**Expected behavior**
I expect the window size not to change depending on what I open.

**Screenshots**
As you can see, you can't even see the button to change the timestamp
![grafik](https://user-images.githubusercontent.com/36167579/68529465-686b4d00-02ff-11ea-81fe-372cda768f2f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - QMapShack Version 1.14.0

**Additional context**
I doubt this is related to #72, I think I've seen it before.

**Comment by kiozen** [comment]
This pops up now and then. The horizontal screen resolution is simply too small. Either you find a good way to optimize the track edit dialog's horizontal size or you have to live with it.

**Comment by pingurus** [comment]
Isn't it possible to change the scale of the diagrams according to the size of the edit tab?

**Comment by kiozen** [comment]
It's not a problem of the diagrams. These are able to scale perfectly. It's a problem of the dialogs in the tab widget below the diagrams.

**Comment by kiozen** [comment]
A workaround is to use full screen (F11) when opening the track edit dialog.

**Comment by kiozen** [comment]
No progress within half a year. I close it for now.
