### ISSUE TITLE
elevation data imported to vrt file are half pixel shifted in x and y direction

### ISSUE THREAD

**Issue by konrad555** [Maproom/qmapshack#77]
after comparing 50cm elevation tiff from upper austria (https://www.land-oberoesterreich.gv.at/211780.htm) with 10m elevation modell from austria and 1° elevation model from sonny (https://data.opendataportal.at/dataset/dtm-austria) I found that models are shown half pixel shifted in x and y direction in QMAPSHACK.

As a workaround I edited the VRT file to get all 3 elevation sources matched.

For verification I used small V shaped canyons:
![grafik](https://user-images.githubusercontent.com/57573270/68534380-43dd9800-0334-11ea-87d1-4bbdb03aaab7.png)

Before correction in VRT:
![grafik](https://user-images.githubusercontent.com/57573270/68534402-87380680-0334-11ea-88f7-4d18e3f45726.png)

After correction in VRT:
![grafik](https://user-images.githubusercontent.com/57573270/68534409-a20a7b00-0334-11ea-8b8f-575711f9eb0a.png)

Googling I found there are two definitions of elevation data (pixel is area vs pixel is point).
QMAPSHACK seems to use another definition than VRT file.

Change in 10m elevation data VRT:

![grafik](https://user-images.githubusercontent.com/57573270/68545618-067a1880-03cf-11ea-987e-ec36fe3eff7b.png)

Change in 1° elevation data VRT:

![grafik](https://user-images.githubusercontent.com/57573270/68545663-77213500-03cf-11ea-93bb-e381b5c2e6ca.png)

**Comment by kiozen** [comment]
I can't really tell what's precisely wrong or if anything is wrong. There is not enough information about what you are doing, e.g. where does this track come from and why do you think it's valid? 

Anyway, if you think there is an error in the math of QMapShack feel welcome to review the code. The file in question is CDemVRT.cpp. This is code faithfully tested but was never reviewed. 

And I would like to ask you to use the templates next time. (https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite) As the report is quite detailed I do not close it asap as usual. But please stick to the rule next time else the issue will be closed.

**Comment by konrad555** [comment]
I compared elevation data from different sources, the elevation data with 50cm pixel size are the best availabe it makes no big difference if the elevation data is referenced to the middle of the pixel or to the corner. 
When you use elevation data with 10m pixel size the error may be 5m.
When useing 1° pixel size the error may be around 10m.

**Comment by konrad555** [comment]
I have created a 8x8 pixel grid with 100m pixel size to test elevation, slope and hillshading at once.
The advantage of this grid is that it can be used as map source and as elevation source (200_150_100_50m.tif)
[8x8.zip](https://github.com/Maproom/qmapshack/files/3867552/8x8.zip)
.
After importing tif to QMAPSHACK I draw an outline of the map (Outline8x8.gpx) and an outline of the area were 50m are shown (50m.gpx), 0° slope is shown in the middle of this area.

Importing Outline8x8.gpx (yellow points in pic below) and 50m.gpx (bluepoints) in SAGA shows that the positionof the map outline is correct but postion of 50m area and slope 0° point is out of center half pixel size (50m x and y)

SAGA GIS:
![grafik](https://user-images.githubusercontent.com/57573270/69212664-390bda00-0b62-11ea-9242-d874defa57f1.png)

QMAPSHACK:
![grafik](https://user-images.githubusercontent.com/57573270/69213150-8d638980-0b63-11ea-8379-8366f7ff04ed.png)

**Comment by kiozen** [comment]
`IDem.cpp` defines:

```c++
    void hillshading(QVector<qint16>& data, qreal w, qreal h, QImage &img);
    void slopecolor(QVector<qint16>& data, qreal w, qreal h, QImage &img);
    void elevationLimit(QVector<qint16>& data, qreal w, qreal h, QImage &img);
```

**Comment by kiozen** [comment]
No progress within half a year. I close it for now.
