### ISSUE TITLE
Edit button for locked tracks

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#78]
**Is your feature request related to a problem? Please describe.**
What is the reason for the edit button not being shown on locked tracks in the project edit?
![grafik](https://user-images.githubusercontent.com/36167579/68549677-2f180780-03fb-11ea-8442-e2f20831c593.png)

**Describe the solution you'd like**
I would like to be able to press the edit button just like for the other track, to go and unlock and then edit this currently locked track.

**Describe alternatives you've considered**
Looking for the track in the workspace view, then rightclick and edit. Takes much longer :wink: 

**Additional context**
Not sure if the current state is a bug or a feature, but I guess it was a concious design choice. Thus a feature request from my side.

**Comment by kiozen** [comment]
This is intentional and should stay. The locked state (aka read-only) influences how items are represented. And if I publish a report/diary I do not want to see the edit icons. You can lock/unlock a complete project by the lock button in the project edit.

**Comment by pingurus** [comment]
I see, thank you!
