### ISSUE TITLE
Possibility to 'star' Waypoints

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#79]
**Is your feature request related to a problem? Please describe.**
When planning geocaching trips, I always have Geocaches I want to look for in any case and some that I don't specifically want to find. I plan my route with those I specifically want to find and then I import other geocaches aswell, since they are on my way. Now when I replan my route, I don't know anymore which are those that I specifically want to find and which I can remove.

**Describe the solution you'd like**
One can add a start to a project, to mark it as the active one. The same way, I'd like to mark any waypoint as an important one.

**Describe alternatives you've considered**
An alternative would be adding offline notes to the saved geocaches, and show in the workspace tree if a geocache has an offline note. This is more complicated (probably) and the use-case is not that broad. However, one could also implement both, since the offline note can be useful in other cases aswell.

**Additional context**

**Comment by kiozen** [comment]
Tagging a project as active project is much more than just adding a star. It is a mode and all new items are automatically added to the active project. Therefore we shouldn't use anything that is looking equal to that in the GUI.

Adding notes that are not part of the GPX definitions and are only QMapShack internal for all items is more the way to go. This information can be shown in the info text. And be subject to filtering.

**Comment by pingurus** [comment]
If I see it correctly, the geocaches in QMS don't use the `wpt.cmt` field of the `CGisItemWpt`.
So my idea would be, that we add a tab to the geocache edit view to edit the comment. Then we can show an icon next to every `IGisItem` that has a comment, so we achieve what I wished for.

**Comment by kiozen** [comment]
But the chances are real that another user asks for the same feature for tracks, routes, areas. That why I think we should add it in a more general way to `IGisItem`

**Comment by pingurus** [comment]
I just checked, we do have `virtual const QString& getComment() const = 0;` in `IGisItem.h`. My naive approach would be to enable the comment for the geocaches and display an icon whenever `gisItem->getComment()!=""`. This would be minimal effort and usable for any `IGisItem`.

**Comment by kiozen** [comment]
What you want to have is a way to rate items internally. `comment` and `description` are part of the GPX definition. Usually they are used for other stuff. If you add rating GPX can't really handle it. 

You can add rating information to GPX fields. But to make QMapShack aware of the rating it would need a defined syntax and/or escape sequence that might upset devices or other software.

That's why I would suggest to make an QMapShack internal field/structure (int: rating, string: keywords) for rating times.

**Comment by pingurus** [comment]
Ah, now I see what you want to do! :smile:
So we add both a numeric rating and keywords?
Connected to this would be:

- [ ] display and edit this for all GisItems and Geocaches
- [ ] enable ordering by rating
- [ ] enable filtering by rating and keywords

Anything else?

**Comment by kiozen** [comment]
Geocache == IGisItem :wink: 

* Store the information in the qmb files
* I would skip it in the GPX files
* You might highlight items with additional information in the workspace tree widget
* Show information in getInfo()
* ...

**Comment by pingurus** [comment]
> Geocache == IGisItem

Of course, but two different UIs for editing :smile:

**Comment by kiozen** [comment]
No. Use an extra dialog for that. One for all IGisItems.

**Comment by pingurus** [comment]
> That's why I would suggest to make an QMapShack internal field/structure (int: rating, string: keywords) for rating times.

Since all of this should be the same for all GisItems the only logical place for this to go is `IGisItem`. However description, comment and links are also shared by every GisItem but defined in every GisItem by it's own. Won't it be a mess starting to place the rating and the tags into `IGisItem`, since then common fields are spread all over the place?

I know this would need a gigantic effort, but can't we straighten out the data structures of the GisItems a "bit"? I mean `wpt_t` is defined in `IGisItem.h`, `CTrackData` is a class on it's own and `rte_t` is defined in `CGisItemRte.h`. In the same way the GisItems are all derived from `IGisItem` the GisDatas could all be derived from `IGisData`.

**Comment by kiozen** [comment]
You might want to edit the staring/scoring in a bulk by selecting all items you want to tag in the workspace list. In that case a small edit dialog helps.

In the details dialogs you don't want to display that information in editable GUI elements but nicely rendered with an option to edit. In that case you need an extra edit dialog, too.
