### ISSUE TITLE
QMapShack doesn't show the correct elevation for fit files from GPSMAP 66s

### ISSUE THREAD

**Issue by beedaddy** [Maproom/qmapshack#8]
**Describe the bug**
QMapShack constantly shows 12607m elevation for fit files which come from the GPSMAP 66s. Fit files from the Forerunner 45 work, though. Perhaps it doesn't help a thing but what I noticed: Converting these files to CSV shows that the FR45 uses altitude *and* enhanced_altitude but the GPSMAP 66 only uses enhanced_altitude.

**To Reproduce**

1. Open a fit file from the GPSMAP 66
2. Right-click on the track and choose "Edit..."
3. You can see that the elevation always is 12607

**Expected behavior**
It should show the correct elevation values.

**Screenshots**
![Screenshot_20190912_075515](https://user-images.githubusercontent.com/3264939/64857883-1cb16580-d626-11e9-9da6-50d5615dcdfd.png)

**Desktop (please complete the following information):**
 - OS: Linux (Arch Linux)
 - Using QMapShack version 1.13.2

**Additional context**
Converting the problematic fit file to gpx with gpsbabel results in a gpx which elevation values are shown correctly. So the data is present in the fit file.
[problemdatei.fit.zip](https://github.com/Maproom/qmapshack/files/3609713/problemdatei.fit.zip)

**Comment by kiozen** [comment]
@beedaddy can you please test the fix.

**Comment by beedaddy** [comment]
@kiozen Thanks! I can confirm that the fix works. All of my GPSMA66-fit-files show reasonable values now. I also did a quick check with a fit file after updating to the latest firmware version of the 66s. Nothing changed here (that is, the fix is needed and works here, too), so, if the problem is a Garmin bug, it still exists in firmware 3.40.
