### ISSUE TITLE
Hide trackpoint doesn't hide the trackpoint

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#81]
**Describe the bug**
I want to hide some trackpoints and while it did hide those around before, it doesn't want to hie this one. (I already removed the other trackpoints around, before it came to my mind to file a bug report)

**To Reproduce**
I am not really sure in which cases this happens, just try to hide trackpoints and see if they are really all hidden. Maybe it has to do something with the "Pausenknödel" filter which I usuall don't use, but I did now.

**Expected behavior**
I expect the points to be hidden.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/36167579/68995236-aaf6d180-088b-11ea-8315-7c43954f35f0.png)
When pressing the hide button, no point is hidden. Even if I select more points, they get hidden, but this single one doesn't.

**Desktop (please complete the following information):**
 - OS: Windows
 - QMapShack Version1.14.0

**Comment by kiozen** [comment]
I use the hide track point function quite frequently and observed no problems so far. You need to provide an example track to reproduce the problem.

**Comment by pingurus** [comment]
I just checked and after restarting QMS I can hide the point. 
I guess I can't provide a way to reproduce this, so I'll close the issue.
