### ISSUE TITLE
Restructure Gis Data

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#82]
**Is your feature request related to a problem? Please describe.**
To implement #79, I would like to restructure the way data is saved in GisItems, since this feature is added for all GisItems. Instead of only adding it to `IGisItem` I have to add it to every GisItem, since their data storage is not inherited.

**Describe the solution you'd like**
I'm not sure which one is best, see my ideas below. I prefer (2.), since that seems cleaner to me.

**Describe alternatives you've considered**
They all have in common, that I create `SGisData` containing all the common data and derive `SWptData` and so forth from it.

1. Add the member variable `SGisData gisData` to `IGisData`.
    Pro:
    * Easy to implement
    * I can simply write the common functions in `IGisItem`

    Con:
    * Casting needed for every single access in GisItems, since they will assign their own GisData to `gisData`
2. Making `IGisItem` declare only pure virtual methods and no member variables. Add a templated `CGisItem` derived from `IGisItem`, that takes as a template parameter a GisData structure and implements all common methods. Then derive the GisItems from both `IGisItem` for dynamic polymorphism and `CGisItem` for the implementation of the common methods
    Pro:
    * No casting needed in GisItems
    
    Con:
    * more complex   

**Additional context**

**Comment by kiozen** [comment]
I do not see your problem. Especially not regarding #79. `IGisItem` is inherited by `CGisItemWpt`, `CGisItemTrk`, `CGisItemRte` and `CGisItemArea`. Therefore every member of `IGisItem` is part of the 4 GIS item implementations. Regarding #79 this is some value for rating and a string. You might organize this as structure/class. All GIS items have access and it's an implementation detail if you want to add code to each getInfo() implementation to show that information or if you implement IGisItem::getInfo() or if you add the stuff as a structure/class with an API to render getInfo().

**Comment by pingurus** [comment]
Yes, the inheritance works fine and I can code it that way, no problem.

I just get the feeling that the code gets a bit messy, since then there are bits of data spread everywhere. I think it get's harder to find access to the code that way.

For example when I wrote the filter, it took me some time to figure out where which data of the track was. Some was in `CTrackData trk`, some as a member variable of `CGisItemTrk`.

Again, it is no problem to write #79 with the code being as it is. However I do think, that refactoring the code the way I suggested will make life easier some point in future, since it makes the code clearer structured. If you do not think that this is improving things, I can of course spend my  time with other things (for exmaple #79) :smile:

**Comment by pingurus** [comment]
@kiozen Is there any chance you'd approve a PR that implements (2.)?

**Comment by kiozen** [comment]
Probably not. Usually  templated code gets a pain in the ass to read and maintain.

And as said, I still  do not really see a real need. 

* Each GIS item has it's own simple data structure. 
* Data common to all GIS Items should be in IGisItem. 

The track Item is a bit different as it grew too complex. That's why it's a bit different. However all other items are designed in the same pattern.
