### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by CrNMGuy** [Maproom/qmapshack#83]
Hi guys, 

I noticed a recurrent crash on the UI

To reproduce : 
On the map window, right click
Select Add a track
Add a second point, then click Left hold, add click Right
Application Crash

On Windows 10 
Version 1.14.0

**Comment by kiozen** [comment]
I can't reproduce. but I have to admit that I do not really understand "then click Left hold, add click Right"

**Comment by CrNMGuy** [comment]
When you are in Add track Mode, the first point is when activate the mode
You left click to ad a second one
Then you want to add a third point, when click left, you hold left and click right
The application immediatly crash

**Comment by runrun1234** [comment]
yes now I can get it too ; the last step needs to be quickly excecuted:
First push (and hold) left button then immediately after push right button ; release both buttons : app stops.

**Comment by CrNMGuy** [comment]
That's it !
it's not intended but already loose my work 5 times :)
