### ISSUE TITLE
mouse release event

### ISSUE THREAD

**Issue by CrNMGuy** [Maproom/qmapshack#85]
Not a problem, more a UI thing

When on the map window, right click to open context menu don't release mouse button down when done quickly 

A quick right click (like < 400 ms ?) should release mouse button and don't allow to engage context menu item by releasing physical mous button
A long click should allow to release on context menu item for quick action

What do you thing ?

**Comment by kiozen** [comment]
This request is closed because it does not use the templates:
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

Furthermore the description is not comprehensible.
