### ISSUE TITLE
Mouse button release

### ISSUE THREAD

**Issue by CrNMGuy** [Maproom/qmapshack#86]
**Is your feature request related to a problem? Please describe.**
When on the map window, right click to open context menu don't release mouse button down when done quickly and allow context menu item to be engaged

**Describe the solution you'd like**
A quick right click (like < 400 ms ?) should release mouse button and don't allow to engage context menu item by releasing physical mous button
A long click should allow to release on context menu item for quick action

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by kiozen** [comment]
Thanks for using the template. But it's still not written in a comprehensible way. At least I do not get what's the problem and what you want.

**Comment by CrNMGuy** [comment]
when fast right click, context menu item (like waypoint) is engaged without me wanting that action to be done.
a fast right click should only open context menu without engaging action (mouse moves a little bit when right clicking)

**Comment by pingurus** [comment]
To reproduce:

Drag the map towards south east (making it show stuff that is north-west of the screen). Whilst holding the left mouse button pressed, press the right mouse button and release it. If you're unlucky, you've now clicked some context menu entry.

Whilst the reproduction way of doing it is rather unrealistic, it did happen to me that I switched between left and right mouse button too fast, causing exactly this behaviour. At least I think this is what the OP describes.

**Comment by CrNMGuy** [comment]
> To reproduce:
> 
> Drag the map towards south east

On my side it's not while dragging map, just wanted to open context menu

**Comment by kiozen** [comment]
The current behaviour is the default behaviour of Qt and I am very reluctant to fiddle around with that.

* A right mouse button click summons the menu. It does not matter if that is done fast or slow.
* If you keep the right mouse button pressed, move the mouse over a menu item and release the right mouse you will trigger the menu action. 

If a single right mouse click triggers a menu action I can think of two scenarios:

* The user is of the frantic kind and simply moves the mouse while pressing the right mouse button
* The hardware is shitty and has a severe jitter in the positioning while the right mouse button is pressed.

Both cases do not qualify to change the default behavior of Qt.

**Comment by CrNMGuy** [comment]
ok
