### ISSUE TITLE
Drop zones grow out of Window

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#90]
**Describe the bug**
When I dock the Database window to the right side of the window the drop zones grow out of the screen. This does not happen when the Database window floats around or is docked on the left side.

**To Reproduce**
1. Add Database window
2. Drag it to the right side of the screen

**Expected behavior**
I expect to be able to see all drop zones. (The fourth one is missing, the third is cut)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/36167579/71724580-0c213700-2e31-11ea-9f51-b2909aea00e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - QMapShack Version 1.14.0

**Additional context**
I can't remember when this bug was introduced, but at some point this worked correctly

**Comment by kiozen** [comment]
I can't confirm the bug on Linux.

![image](https://user-images.githubusercontent.com/54329441/71811890-1b44f680-3076-11ea-97ad-4df0306c7dc0.png)

If it is Windows specific someone with a Windows system has to check.

**Comment by pingurus** [comment]
After restarting Windows (!?) this doesn't occur anymore. Can't reproduce it either.
My only guess would be that it has something to do with having two screens, but I can't test that now.
