### ISSUE TITLE
Missing SQLITE files mentioned in msvc_64/copyfiles.bat (Windows version)

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#91]
**Describe the bug**
In the `msvc_64/copyfiles.bat` section 2.2.10 (sqlite) the 2 files
* `sqldiff.exe`
* `sqlite3_analyzer.exe`

should be copied. These files don't exist (are not downloaded from somewhere) when following the Windows installation instructions in the Wiki pages `BuildWindowsVisualStudio`and `BuildWindowsGdalWithAdditionalFormats`

**To Reproduce**

Run `msvc_64\copyfiles.bat`and check output.

**Expected behavior**

Either the 2 files are not necessary when running QMS. Then they should be dropped from the batch file or the installation instructions in the Wiki should describe how to find/download these 2 files.

**Screenshots**

none

**Desktop (please complete the following information):**
 - OS: Windows  10
 - QMapShack Version: latest dev version 

**Additional context**

none

**Comment by huirad** [comment]
Actually the files do exist when follwoing the instruction in Wiki page [BuildWindowsGdalWithAdditionalFormats](https://github.com/Maproom/qmapshack/wiki/BuildWindowsGdalWithAdditionalFormats). They are part of the sqlite-tools packed mentioned in the section "Additional binaries needed to compile PROJ.4 version 6". 
So there should be no issue for copyfiles.bat to find them if you followed the instructions.

True, the files are not strictly necessary to run QMS. The are included in the binary distribution as they may be useful for problem analysis related to sqlite databases as used by QMS.

@wthaem: is this explanation sufficient for you to close the issue?

**Comment by wthaem** [comment]
Thanks. I found the files by checking again the downloaded packages ansd was just on the way to close the issue.
