### ISSUE TITLE
why are routes limited?

### ISSUE THREAD

**Issue by think-nice-things** [Maproom/qmapshack#93]
QMapShack does allow to edit \<ele\> and \<desc\> for tracks (\<trkpt\>) **but not for routes**.

Is there a reason why qmapshack implements only a subset of features for routes compared to tracks?

Is this difference between routes and tracks something which has been decided by purpose?

**Comment by kiozen** [comment]
I close this issue because it does meet the form issues should be written. Please read:

https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite

Answer in short:
So far no one considered routes important enough to spent much valuable spare time into routes.
