### ISSUE TITLE
Strange database vs. workspace behavior - missing refresh?

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#94]
_(triggered by recent discussion in German newsgroup  `www.naviboard.de`)_

**Describe the bug**

When copying and editing data items there appears an inconsistency between database and workspace which might be caused by a missing refresh in the database and/or workspace windows.

**To Reproduce**

_Compare attached snapshot!_

1. The first column in the snapshot shows the initial state of a database and the workspace after QMS start
1. Open DB projects `pp, qq` in workspace (column 2)
1. Copy `WPT1` to `qq`
1. Save `qq` to DB. In query window choose `Don't replace item` (column 3)
1. Rename `WPT1` in `qq`
1. Save `qq`. No query window in this step! (column 4). Workspace and database are consistent. Each window shows 2 (different?!) data objects.
1. Close both projects in workspace (this is a workspace operation which shouldn't change the database - everything was saved in the previous step)
1. Re-open both projects in workspace (column 5)
1. Compare columns 4 and 5 - in both cases database and workspace are consistent __but closing workspace projects and re-opening them changed the database content!__ Instead of 2 data items in database (column 4) there is now only 1!
1. Looking into the `items` table in the database file(!) reveals that there is only 1 item (`WPT1renamed`)

**Expected behavior**

* There shouldn't be any difference between columns 4 and 5 because there was no database change (only closing and opening operations).
* At least after the renaming step the user expects 2 different data items - and he can identify them in the workspace and in the database. 
* The loss of 1 data item in column 5 is quite surprising and shouldn't happen.

**Screenshots**

attached

**Desktop (please complete the following information):**
 - OS: Windows10
 - QMapShack latest version in repo

**Additional context**

* Can it happen that a data item has 2 different names? If yes, then how to identify this fact in the workspace or database windows? And how would this be saved into the database file? Seeing 2 different names for data items the user assumes that there are 2 different data items.

![DatabaseInconsistency](https://user-images.githubusercontent.com/55309218/72066963-2603c380-32e2-11ea-9985-9e62af0ff124.png)

**Comment by kiozen** [comment]
Yes, this seems to be a glitch in updating the database treewidget. In column 4 both entries should read WPT1renamed. The update is triggered when toggling the expanded state of the folder. 

If I recall correctly this was accepted behaviour because fixing it is very complicated and takes quite some processing time. You have to search for the updated item in the database view, update the item and send events to the workspace to tell the item on the workspace to update itself from the database. 

This is one reason why there is the "Sync. with Database" function in the workspace.

**Comment by wthaem** [comment]
Is there a way to inform the user that he has to do something additional (refresh somehow manually) when going from a situation as shown in column 3 to column 4 (renaming of object in one project with same object in other project)? E.g.: "You are going to rename/edit item x in project y which also belongs to project z. Please click `Sync. ...`after this operation". 

Or is even this a difficult task? 

And how to distinguish the case discussed here from the case where there are 2 different data items in 2 different projects having by chance the same name?

Would it be possible to add some optical indicator of the form "Copy of some other object - be  careful  when editing ..." to the copied item?

**Comment by wthaem** [comment]
Additional question w.r.t. "Sync. with database": Up to now this menu entry has been discussed in the Wiki only in connection with a QMS multi-user version. 

Having unsaved changes (in a single-user version) in the workspace and clicking this menu entry in the database window pops-up a message of the form

~~~
The project x is about to update itself from the database. However there are changes not saved.
~~~

This message seems to be ambiguous. Is the proper meaning for a single-use version as follows:


"The project x __in the workspace__ is about to update itself from the __internal QMS client database__. However there are changes __in the workspace__ not saved."?

or should it read

"The project x __in the database window (i.e. the internal QMS client database data)__ is about to update itself from the __external database (file)__. However there are changes in the __internal database__ not saved __to the external one__."?

Maybe, both types of sync happen at the same time?


Having the multi-user version in mind the term "database" is ambiguous, too. It can be what is seen in the database window of the used QMS client or the SQLite/MySql database file. I.e. does the sync take place between the database file and the data within the QMS client, too?

**Comment by kiozen** [comment]
"Sync. with database" will reload the item from the database. The database view is just a representation of that. So there is no internal database or external database or any other ambiguity. The database is the single source if truth.

To be honest I think this whole case is just a corner case. Yes there is an inconsistency updating the GUI. No reason to deny. But I doubt that many users will ever notice. And I doubt that bombarding the user with even more message boxes that explain things to the word will help. Users don't read and refuse to understand complex stuff. You know all these discussions with overwhelmed users from the past. For some users using a database is just alien technology. Complex explanations do not help.

It would be nicer to fix the inconsistency. But from the current point of view I can't see a solution that does not backfire. Just imagine one of these hunters and collectors starts to change icon of 10k waypoints that are linked by two folders. This will take some time right now. It will take ages if you have to check the database tree and the workspace tree for updates.

**Comment by wthaem** [comment]
Ok. Thanks for discussing. Let's stick to your philosophy and let's close the issue.
