### ISSUE TITLE
total length of a non calculated route should be shown in its info window

### ISSUE THREAD

**Issue by lucamp** [Maproom/qmapshack#96]
feature request

Hi,
during the creation of a new route the "Route Metrics" window appears at top left of the map's corner showing the total distance of the route based on a straight line. (image 01.jpg)
Once saved and selected the length is missing from its info windows (image 02.jpg), but choosing "move route points" to edit and a new windows appears with the "Route Metrics" and distance is shown (image 03.jpg).

**Describe the solution you'd like**
Even if the route has not been passed to a route engine and it is based just on the straight lines, the total length should be displayed in its info. Since there will be no time associated the user know it has not been calculated; if this is not enough a text like "not calculated" could appears near it.

Thanks for qmapshack,
Luca

**Additional context**
![01](https://user-images.githubusercontent.com/15078341/72621583-d193c000-3941-11ea-827b-400a2830a1de.jpg)
![02](https://user-images.githubusercontent.com/15078341/72621597-d9536480-3941-11ea-81af-b9cd8c44c5b4.jpg)
![03](https://user-images.githubusercontent.com/15078341/72621610-dfe1dc00-3941-11ea-80aa-56cf30ffac2a.jpg)

**Comment by kiozen** [comment]
As there is no progress I close it for now.

**Comment by kiozen** [comment]
-
