### ISSUE TITLE
Allow "Save (Print) Map" to produce tiled PNG/JPEG

### ISSUE THREAD

**Issue by jfbourdon** [Maproom/qmapshack#97]
**The problem**
When I want to save a large map as PNG/JPEG at high resolution, the operation fail because the number of pixels is too large. I suspect that my computer is running out of RAM, but anyway, a +100 Mpx PNG is not easily manageable.

**The solution**
Give the possibility to produce several smaller PNG/JPEG as tiles of the selected area on the map. It would be a plus if the tiles could have a world file attached so they could be displayed in a SIG like QGIS.

**Alternatives considered**
For now, I do the tiling manually by selecting and exporting several smaller portions of the map with a little bit of overlap and then stitch everything in GIMP to export as a TIFF.

**Additional context**
I have very little knowledge of C++, but I think than I can manage to (eventually) hack something in the CPrintDialog.cpp file to simulate this.

**Comment by kiozen** [comment]
This is out of scope of QMapShack. QMapShack is not a tool to cut and merge maps. 

However the is QMapTool. It does not have a really cutting tool, but you can make everything around the desired area transparent and stitch several of those maps to one.

And I would expect QGis to be the tool of your choice if it comes to cutting and merging maps.

**Comment by jfbourdon** [comment]
I wasn't clear enough in my explanations. I don't wish to cut and merge maps in QMapShack. I wish to export maps as PNG/JPEG but in chucks instead of one (too) big file as it's the case currently.

In my example below, my AOI is 622 x 663 pixels. If I click save, I'll get a file of that size. However, I would like to have the option to save four files of roughly 311 x 332 pixels. The size in my example is small, but if my AOI is 10000 by 10000 pixels, it makes sens to chuck it in smaller pieces. The number of pieces would be user-definable.

![TilesPNG](https://user-images.githubusercontent.com/32580398/73122823-1e395580-3f57-11ea-8513-39b3b35a4607.jpg)

**Comment by kiozen** [comment]
But what is the use-case for such a large image? And why the worldfile? 

See, I don't like to spend my spare time on a single use-case. If it is a common use-case for several users it's getting interesting. If it's something I would like to use myself motivation will rocket high. So far it's just a peculiar request and I still do not understand it's real intend and benefit.

**Comment by jfbourdon** [comment]
The use-case would be to be able to reimport the image in a GIS (thus why the worldfile) for other work. For me it could be useful because QMapShack is one of the few GIS that can decode Garmin's JNX files. That being said, I agree that this is probably (certainly) not a common use-case. I'll simply look into it myself and if I ever manage to do something useful, I'll do a pull request. I think the issue can be closed for now.

**Comment by kiozen** [comment]
This is exporting maps into other file formats and not in the scope of QMapShack. But it would fit into QMapTool.
