### ISSUE TITLE
Support for Mapsforge maps

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#98]
**Is your feature request related to a problem? Please describe.**
There once has been a feature request for the support of Mapsforge maps back on bitbucket (at least I think so), which was declined because of the hassle to implement it, since mapsforge is written in Java (again, this is what stuck in my memory).
I think the support of the Mapsforge vector maps would give the users more possibility to style their own maps relatively easily. I myself built garmin img maps for that purpose until now and it would be great to be able to just download a map and apply your own style to it.

**Describe the solution you'd like**
I found a working [Mapsforge Tileserver](https://github.com/telemaxx/mapsforgesrv_with_gradle), that could be integrated into QMS just the way Brouter is integrated. Not sure though about licenses.

**Describe alternatives you've considered**
Alternatively we could just add an entry to the wiki describing how to set up the server on localhost and adding the corresponding tms file to QMS.

**Additional context**
I think the image quality is not that great, but I don't know what's the cause of that.

**Comment by kiozen** [comment]
Do we need a change for this? From my point of view it's just another tile server.

**Comment by pingurus** [comment]
Well, it is more convenient, if you only have to activate a map the way you are used to without having to start the tileserver separately. Sure, it's no big effort but nevertheless.
If however stylemenus are supported in a future version of the tileserver, it would be much easier if one could toggle the style options in QMS instead of fiddling with the XML file.

So for now I'll add an entry to the wiki and whenever the stylemenus are supported we can reconsider adding support, right?

**Comment by kiozen** [comment]
Well, Norbert spent quite an effort to make BRouter easy to install and to maintain on all operating systems. Therefore it was ok to integrate such a solution. To install, embed and maintain a local tileserver we should make sure to keep up with that level. I am not sure if it is worth it.

**Comment by pingurus** [comment]
What do you think of my [wiki edits](https://github.com/Maproom/qmapshack/wiki/DocBasicsMapDem#mapsforge-maps)?

**Comment by kiozen** [comment]
Link to  openandromaps.org is not working

The rest is working on my Linux box.

**Comment by pingurus** [comment]
> Link to openandromaps.org is not working

Just checked, it works for me in Firefox on Windows. Any Idea what I have to change?

**Comment by wthaem** [comment]
Nothing! I changed some broken formats on this Wiki page including the wrong link!
