### ISSUE TITLE
Can't load FIT file on 32bit

### ISSUE THREAD

**Issue by FabianInostroza** [Maproom/qmapshack#99]
**Describe the bug**
Can't load FIT files, the following error is shown
![Captura de pantalla -2020-01-26 18-04-58](https://user-images.githubusercontent.com/8893928/73141748-64c9a580-4066-11ea-86be-815dc7bfd416.png)

**To Reproduce**
1. Download the attached zipped fit file
[2019-12-29-21-33-01.fit.zip](https://github.com/Maproom/qmapshack/files/4114342/2019-12-29-21-33-01.fit.zip)
2. Unzip the file and try to open it on qmapshack

**Expected behavior**
File is loaded with no issues

**Desktop (please complete the following information):**
 - OS: Debian Buster 32bits
 - QMapShack Version 1.14.0

**Additional context**
The issue doens't happen in 64bit versions of the application (same version), I tried on Debian testing 64bits and windows 10 64bits.

**Comment by kiozen** [comment]
32bit versions are not supported. See https://github.com/Maproom/qmapshack/wiki
